[package]
name = "celeste-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bv = "0.11.1"
anyhow = "1.0.62"
lazy_static = "1.4.0"
regex = "1.6.0"
hex = "0.4.3"
rustc-hash = "1.1.0"
work-queue = "0.1.3"
crossbeam = "0.8.2"
image = "0.24.3"
full_moon = "0.19.0"
