// GENERATED by `transpile --kernel` (plans/kernel-plan.md). Do not edit.
//
// The STEADY-CLASS lane kernel: shape (player), pm1 freeze=0 dash_time=0.
// Shared prefix per 16-row slice, 64 monomorphized button suffixes.
#![allow(unused_variables, unused_mut, unused_imports, clippy::all)]
use celeste_engine::kernel::*;
use celeste_core::pico8_num::{Pico8Num as P8, Pico8NumInterval as IV};
use celeste_core::cart_data::CartData;
use celeste_core::collision_cache::CollisionCache;

pub const SHAPE_HASH: u64 = 0xa9e20c0af79aea86;
pub struct G<'a> { pub cart: &'a CartData, pub cache: &'a CollisionCache }

/// Block-uniform inputs, bound per block (kind-checked).
pub struct Uni {
    pub c20: P8,
    pub c38: bool,
    pub c39: P8,
    pub c41: bool,
    pub c42: bool,
    pub c43: bool,
    pub c44: P8,
    pub c45: P8,
    pub c46: P8,
    pub c47: P8,
    pub c48: P8,
    pub c49: P8,
    pub c84: P8,
    pub c85: P8,
    pub c86: P8,
    pub c87: P8,
    pub c88: P8,
    pub c159: P8,
    pub c161: P8,
    pub c162: P8,
    pub c174: P8,
    pub c177: P8,
    pub c180: P8,
    pub c182: bool,
    pub c184: P8,
    pub c186: bool,
    pub c188: P8,
    pub c190: bool,
    pub c191: P8,
    pub c193: bool,
    pub c194: P8,
    pub c196: bool,
    pub c198: P8,
    pub c204: P8,
    pub c238: bool,
    pub c246: (P8, P8),
    pub c248: bool,
    pub c250: P8,
    pub c251: P8,
    pub c253: P8,
    pub c254: (P8, P8),
    pub c257: bool,
    pub c259: P8,
    pub c260: P8,
    pub c268: bool,
    pub c270: P8,
    pub c272: P8,
    pub c273: P8,
    pub c276: bool,
    pub c278: P8,
    pub c279: P8,
    pub c287: bool,
    pub c289: P8,
    pub c291: P8,
    pub c292: P8,
    pub c295: bool,
    pub c299: P8,
    pub c300: P8,
    pub c309: bool,
    pub c310: bool,
    pub c312: bool,
    pub c364: bool,
    pub c365: bool,
    pub c366: P8,
    pub c367: P8,
    pub c368: P8,
    pub c369: P8,
    pub c370: P8,
    pub c371: P8,
    pub c372: P8,
    pub c373: P8,
    pub c374: bool,
    pub c375: bool,
    pub c376: P8,
    pub c377: P8,
    pub c378: P8,
    pub c379: P8,
    pub c380: P8,
    pub c381: P8,
    pub c382: P8,
    pub c383: P8,
    pub c384: bool,
    pub c385: bool,
    pub c386: P8,
    pub c387: P8,
    pub c388: P8,
    pub c389: P8,
    pub c390: P8,
    pub c391: P8,
    pub c392: P8,
    pub c393: P8,
    pub c399: bool,
    pub c400: P8,
    pub c401: P8,
    pub c402: P8,
    pub c403: P8,
    pub c404: (P8, P8),
    pub c405: (P8, P8),
}

pub const UNI_CELLS: &[(u32, &str)] = &[
    (20, "num"),
    (38, "bool"),
    (39, "num"),
    (41, "bool"),
    (42, "bool"),
    (43, "bool"),
    (44, "num"),
    (45, "num"),
    (46, "num"),
    (47, "num"),
    (48, "num"),
    (49, "num"),
    (84, "num"),
    (85, "num"),
    (86, "num"),
    (87, "num"),
    (88, "num"),
    (159, "num"),
    (161, "num"),
    (162, "num"),
    (174, "num"),
    (177, "num"),
    (180, "num"),
    (182, "bool"),
    (184, "num"),
    (186, "bool"),
    (188, "num"),
    (190, "bool"),
    (191, "num"),
    (193, "bool"),
    (194, "num"),
    (196, "bool"),
    (198, "num"),
    (204, "num"),
    (238, "bool"),
    (246, "ival"),
    (248, "bool"),
    (250, "num"),
    (251, "num"),
    (253, "num"),
    (254, "ival"),
    (257, "bool"),
    (259, "num"),
    (260, "num"),
    (268, "bool"),
    (270, "num"),
    (272, "num"),
    (273, "num"),
    (276, "bool"),
    (278, "num"),
    (279, "num"),
    (287, "bool"),
    (289, "num"),
    (291, "num"),
    (292, "num"),
    (295, "bool"),
    (299, "num"),
    (300, "num"),
    (309, "bool"),
    (310, "bool"),
    (312, "bool"),
    (364, "bool"),
    (365, "bool"),
    (366, "num"),
    (367, "num"),
    (368, "num"),
    (369, "num"),
    (370, "num"),
    (371, "num"),
    (372, "num"),
    (373, "num"),
    (374, "bool"),
    (375, "bool"),
    (376, "num"),
    (377, "num"),
    (378, "num"),
    (379, "num"),
    (380, "num"),
    (381, "num"),
    (382, "num"),
    (383, "num"),
    (384, "bool"),
    (385, "bool"),
    (386, "num"),
    (387, "num"),
    (388, "num"),
    (389, "num"),
    (390, "num"),
    (391, "num"),
    (392, "num"),
    (393, "num"),
    (399, "bool"),
    (400, "num"),
    (401, "num"),
    (402, "num"),
    (403, "num"),
    (404, "ival"),
    (405, "ival"),
];

/// Folds consumed these uniform cells' witness values; bind must
/// guard them (raw bits) or send the block to the interpreter.
pub const PIN_CELLS: &[(u32, i32)] = &[
    (45, 65536i32),
    (48, 262144i32),
    (49, 327680i32),
];

/// Per-lane inputs: 16 rows per slice.
pub struct RowsIn {
    pub c297: ZN,
    pub c302: ZN,
    pub c316: ZN,
    pub c317: ZN,
    pub c394: ZN,
    pub c395: ZN,
    pub c396: ZN,
    pub c397: ZN,
    pub c398: u16,
    pub c406: ZN,
    pub c407: ZN,
}

pub const VARY_CELLS: &[(u32, &str)] = &[
    (297, "num"),
    (302, "num"),
    (316, "num"),
    (317, "num"),
    (394, "num"),
    (395, "num"),
    (396, "num"),
    (397, "num"),
    (398, "bool"),
    (406, "num"),
    (407, "num"),
];

/// Button-independent outputs: one per fork config.
pub struct KOutShared {
    pub c38: bool,
    pub c39: P8,
    pub c84: P8,
    pub c87: P8,
    pub c246: (P8, P8),
    pub c254: (P8, P8),
    pub c297: ZN,
    pub c300: ZN,
    pub c316: ZN,
    pub c317: ZN,
    pub c398: ZB,
    pub c404: ZI,
    pub c405: ZI,
}

/// Button-dependent outputs: one per (config, variant).
pub struct KOut {
    /// Lanes that EXIST in this fork configuration.
    pub valid: u16,
    pub deopt: u16,
    pub bd: bool,
    pub c302: ZN,
    pub c309: bool,
    pub c310: bool,
    pub c406: ZN,
    pub c407: ZN,
}

pub const OUT_CELLS: &[u32] = &[
    38,
    39,
    84,
    87,
    246,
    254,
    297,
    300,
    302,
    309,
    310,
    316,
    317,
    398,
    404,
    405,
    406,
    407,
];

/// Cells that end every frame as a fresh UnknownBool (the next
/// frame's button inputs); the boundary writes UBool, no data.
pub const OUT_UBOOL_CELLS: &[u32] = &[
    145,
    146,
    147,
    148,
    149,
    150,
];

use celeste_engine::runtime2::{Rt2, Col, AV};

/// Bind the block-uniform inputs. None = off-shape / off-kind /
/// pin mismatch: the block takes the reference path.
pub fn bind(b: &Rt2) -> Option<Uni> {
    if b.shape_hash != SHAPE_HASH { return None; }
    for (cell, pin) in PIN_CELLS {
        match &b.cols[*cell as usize] {
            Col::U(AV::Num(n)) if n.as_raw_u32() as i32 == *pin => {}
            _ => return None,
        }
    }
    Some(Uni {
        c20: match &b.cols[20] { Col::U(AV::Num(n)) => *n, _ => return None },
        c38: match &b.cols[38] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c39: match &b.cols[39] { Col::U(AV::Num(n)) => *n, _ => return None },
        c41: match &b.cols[41] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c42: match &b.cols[42] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c43: match &b.cols[43] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c44: match &b.cols[44] { Col::U(AV::Num(n)) => *n, _ => return None },
        c45: match &b.cols[45] { Col::U(AV::Num(n)) => *n, _ => return None },
        c46: match &b.cols[46] { Col::U(AV::Num(n)) => *n, _ => return None },
        c47: match &b.cols[47] { Col::U(AV::Num(n)) => *n, _ => return None },
        c48: match &b.cols[48] { Col::U(AV::Num(n)) => *n, _ => return None },
        c49: match &b.cols[49] { Col::U(AV::Num(n)) => *n, _ => return None },
        c84: match &b.cols[84] { Col::U(AV::Num(n)) => *n, _ => return None },
        c85: match &b.cols[85] { Col::U(AV::Num(n)) => *n, _ => return None },
        c86: match &b.cols[86] { Col::U(AV::Num(n)) => *n, _ => return None },
        c87: match &b.cols[87] { Col::U(AV::Num(n)) => *n, _ => return None },
        c88: match &b.cols[88] { Col::U(AV::Num(n)) => *n, _ => return None },
        c159: match &b.cols[159] { Col::U(AV::Num(n)) => *n, _ => return None },
        c161: match &b.cols[161] { Col::U(AV::Num(n)) => *n, _ => return None },
        c162: match &b.cols[162] { Col::U(AV::Num(n)) => *n, _ => return None },
        c174: match &b.cols[174] { Col::U(AV::Num(n)) => *n, _ => return None },
        c177: match &b.cols[177] { Col::U(AV::Num(n)) => *n, _ => return None },
        c180: match &b.cols[180] { Col::U(AV::Num(n)) => *n, _ => return None },
        c182: match &b.cols[182] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c184: match &b.cols[184] { Col::U(AV::Num(n)) => *n, _ => return None },
        c186: match &b.cols[186] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c188: match &b.cols[188] { Col::U(AV::Num(n)) => *n, _ => return None },
        c190: match &b.cols[190] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c191: match &b.cols[191] { Col::U(AV::Num(n)) => *n, _ => return None },
        c193: match &b.cols[193] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c194: match &b.cols[194] { Col::U(AV::Num(n)) => *n, _ => return None },
        c196: match &b.cols[196] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c198: match &b.cols[198] { Col::U(AV::Num(n)) => *n, _ => return None },
        c204: match &b.cols[204] { Col::U(AV::Num(n)) => *n, _ => return None },
        c238: match &b.cols[238] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c246: match &b.cols[246] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c248: match &b.cols[248] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c250: match &b.cols[250] { Col::U(AV::Num(n)) => *n, _ => return None },
        c251: match &b.cols[251] { Col::U(AV::Num(n)) => *n, _ => return None },
        c253: match &b.cols[253] { Col::U(AV::Num(n)) => *n, _ => return None },
        c254: match &b.cols[254] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c257: match &b.cols[257] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c259: match &b.cols[259] { Col::U(AV::Num(n)) => *n, _ => return None },
        c260: match &b.cols[260] { Col::U(AV::Num(n)) => *n, _ => return None },
        c268: match &b.cols[268] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c270: match &b.cols[270] { Col::U(AV::Num(n)) => *n, _ => return None },
        c272: match &b.cols[272] { Col::U(AV::Num(n)) => *n, _ => return None },
        c273: match &b.cols[273] { Col::U(AV::Num(n)) => *n, _ => return None },
        c276: match &b.cols[276] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c278: match &b.cols[278] { Col::U(AV::Num(n)) => *n, _ => return None },
        c279: match &b.cols[279] { Col::U(AV::Num(n)) => *n, _ => return None },
        c287: match &b.cols[287] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c289: match &b.cols[289] { Col::U(AV::Num(n)) => *n, _ => return None },
        c291: match &b.cols[291] { Col::U(AV::Num(n)) => *n, _ => return None },
        c292: match &b.cols[292] { Col::U(AV::Num(n)) => *n, _ => return None },
        c295: match &b.cols[295] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c299: match &b.cols[299] { Col::U(AV::Num(n)) => *n, _ => return None },
        c300: match &b.cols[300] { Col::U(AV::Num(n)) => *n, _ => return None },
        c309: match &b.cols[309] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c310: match &b.cols[310] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c312: match &b.cols[312] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c364: match &b.cols[364] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c365: match &b.cols[365] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c366: match &b.cols[366] { Col::U(AV::Num(n)) => *n, _ => return None },
        c367: match &b.cols[367] { Col::U(AV::Num(n)) => *n, _ => return None },
        c368: match &b.cols[368] { Col::U(AV::Num(n)) => *n, _ => return None },
        c369: match &b.cols[369] { Col::U(AV::Num(n)) => *n, _ => return None },
        c370: match &b.cols[370] { Col::U(AV::Num(n)) => *n, _ => return None },
        c371: match &b.cols[371] { Col::U(AV::Num(n)) => *n, _ => return None },
        c372: match &b.cols[372] { Col::U(AV::Num(n)) => *n, _ => return None },
        c373: match &b.cols[373] { Col::U(AV::Num(n)) => *n, _ => return None },
        c374: match &b.cols[374] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c375: match &b.cols[375] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c376: match &b.cols[376] { Col::U(AV::Num(n)) => *n, _ => return None },
        c377: match &b.cols[377] { Col::U(AV::Num(n)) => *n, _ => return None },
        c378: match &b.cols[378] { Col::U(AV::Num(n)) => *n, _ => return None },
        c379: match &b.cols[379] { Col::U(AV::Num(n)) => *n, _ => return None },
        c380: match &b.cols[380] { Col::U(AV::Num(n)) => *n, _ => return None },
        c381: match &b.cols[381] { Col::U(AV::Num(n)) => *n, _ => return None },
        c382: match &b.cols[382] { Col::U(AV::Num(n)) => *n, _ => return None },
        c383: match &b.cols[383] { Col::U(AV::Num(n)) => *n, _ => return None },
        c384: match &b.cols[384] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c385: match &b.cols[385] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c386: match &b.cols[386] { Col::U(AV::Num(n)) => *n, _ => return None },
        c387: match &b.cols[387] { Col::U(AV::Num(n)) => *n, _ => return None },
        c388: match &b.cols[388] { Col::U(AV::Num(n)) => *n, _ => return None },
        c389: match &b.cols[389] { Col::U(AV::Num(n)) => *n, _ => return None },
        c390: match &b.cols[390] { Col::U(AV::Num(n)) => *n, _ => return None },
        c391: match &b.cols[391] { Col::U(AV::Num(n)) => *n, _ => return None },
        c392: match &b.cols[392] { Col::U(AV::Num(n)) => *n, _ => return None },
        c393: match &b.cols[393] { Col::U(AV::Num(n)) => *n, _ => return None },
        c399: match &b.cols[399] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c400: match &b.cols[400] { Col::U(AV::Num(n)) => *n, _ => return None },
        c401: match &b.cols[401] { Col::U(AV::Num(n)) => *n, _ => return None },
        c402: match &b.cols[402] { Col::U(AV::Num(n)) => *n, _ => return None },
        c403: match &b.cols[403] { Col::U(AV::Num(n)) => *n, _ => return None },
        c404: match &b.cols[404] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c405: match &b.cols[405] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
    })
}

/// Gather rows [lo, lo+16) into lane arrays; short slices pad by
/// repeating the last row (padded outputs are ignored by width).
pub fn rows(b: &Rt2, lo: usize) -> Option<RowsIn> {
    let at = |i: usize| -> usize { (lo + i).min(b.width - 1) };
    Some(RowsIn {
        c297: match &b.cols[297] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c302: match &b.cols[302] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c316: match &b.cols[316] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c317: match &b.cols[317] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c394: match &b.cols[394] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c395: match &b.cols[395] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c396: match &b.cols[396] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c397: match &b.cols[397] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c398: match &b.cols[398] {
            Col::V(v) => {
                let mut m = 0u16;
                for i in 0..W { if matches!(v[at(i)], AV::Bool(true)) { m |= 1 << i; } else if !matches!(v[at(i)], AV::Bool(false)) { return None; } }
                m
            }
            Col::U(AV::Bool(t)) => if *t { 0xffff } else { 0 },
            _ => return None,
        },
        c406: match &b.cols[406] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c407: match &b.cols[407] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
    })
}

/// Write one (config, variant) result onto a width-`n` sliced block
/// (the block already carries the input row values).
pub fn apply(sh: &KOutShared, kv: &KOut, b: &mut Rt2, n: usize) {
    b.cols[38] = Col::U(AV::Bool(sh.c38));
    b.cols[39] = Col::U(AV::Num(sh.c39));
    b.cols[84] = Col::U(AV::Num(sh.c84));
    b.cols[87] = Col::U(AV::Num(sh.c87));
    b.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
    b.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
    b.cols[297] = Col::N(sh.c297[..n].to_vec());
    b.cols[300] = Col::N(sh.c300[..n].to_vec());
    b.cols[302] = Col::N(kv.c302[..n].to_vec());
    b.cols[309] = Col::U(AV::Bool(kv.c309));
    b.cols[310] = Col::U(AV::Bool(kv.c310));
    b.cols[316] = Col::N(sh.c316[..n].to_vec());
    b.cols[317] = Col::N(sh.c317[..n].to_vec());
    b.cols[398] = Col::V((0..n).map(|i| AV::Bool(sh.c398.val & (1 << i) != 0)).collect());
    b.cols[404] = Col::I((0..n).map(|i| (sh.c404.lo[i], sh.c404.hi[i])).collect());
    b.cols[405] = Col::I((0..n).map(|i| (sh.c405.lo[i], sh.c405.hi[i])).collect());
    b.cols[406] = Col::N(kv.c406[..n].to_vec());
    b.cols[407] = Col::N(kv.c407[..n].to_vec());
    for cell in OUT_UBOOL_CELLS {
        b.cols[*cell as usize] = Col::U(AV::UBool);
    }
}

/// One wide output block per chunk: structure + uniforms cloned
/// once, varying/output columns start empty and grow by appends.
pub fn acc_init(chunk: &Rt2) -> Rt2 {
    let mut acc = Rt2::empty(0, chunk.globals.len(), &[], chunk.cart.clone(), chunk.cache.clone());
    acc.strings = chunk.strings.clone();
    acc.globals = chunk.globals.clone();
    acc.structure = chunk.structure.clone();
    acc.cols = chunk.cols.clone();
    acc.shape_hash = chunk.shape_hash;
    acc.cols[297] = Col::N(Vec::new());
    acc.cols[300] = Col::N(Vec::new());
    acc.cols[302] = Col::N(Vec::new());
    acc.cols[309] = Col::V(Vec::new());
    acc.cols[310] = Col::V(Vec::new());
    acc.cols[316] = Col::N(Vec::new());
    acc.cols[317] = Col::N(Vec::new());
    acc.cols[398] = Col::V(Vec::new());
    acc.cols[404] = Col::I(Vec::new());
    acc.cols[405] = Col::I(Vec::new());
    acc.cols[406] = Col::N(Vec::new());
    acc.cols[407] = Col::N(Vec::new());
    acc.cols[394] = Col::N(Vec::new());
    acc.cols[395] = Col::N(Vec::new());
    acc.cols[396] = Col::N(Vec::new());
    acc.cols[397] = Col::N(Vec::new());
    for cell in OUT_UBOOL_CELLS {
        acc.cols[*cell as usize] = Col::U(AV::UBool);
    }
    acc
}

/// Append one (config, variant)'s live lanes onto the accumulator.
/// `lo` is the slice base in `chunk` (identity columns read there).
#[allow(unused_variables)]
pub fn append_out(acc: &mut Rt2, chunk: &Rt2, lo: usize, n: usize, live: u16, sh: &KOutShared, kv: &KOut, bd: &mut bool) {
    // fresh: no fork config has written yet, so a uniform slot
    // still holds the chunk's INPUT value (legitimately different).
    let fresh = acc.width == 0;
    for i in 0..n {
        if live & (1 << i) == 0 { continue; }
        if !fresh { if let Col::U(AV::Bool(prev)) = &acc.cols[38] { if *prev != sh.c38 { *bd = true; } } }
        acc.cols[38] = Col::U(AV::Bool(sh.c38));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[39] { if *prev != sh.c39 { *bd = true; } } }
        acc.cols[39] = Col::U(AV::Num(sh.c39));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[84] { if *prev != sh.c84 { *bd = true; } } }
        acc.cols[84] = Col::U(AV::Num(sh.c84));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[87] { if *prev != sh.c87 { *bd = true; } } }
        acc.cols[87] = Col::U(AV::Num(sh.c87));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[246] { if (*a, *b) != sh.c246 { *bd = true; } } }
        acc.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[254] { if (*a, *b) != sh.c254 { *bd = true; } } }
        acc.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
        if let Col::N(v) = &mut acc.cols[297] { v.push(sh.c297[i]); }
        if let Col::N(v) = &mut acc.cols[300] { v.push(sh.c300[i]); }
        if let Col::N(v) = &mut acc.cols[302] { v.push(kv.c302[i]); }
        if let Col::V(v) = &mut acc.cols[309] { v.push(AV::Bool(kv.c309)); }
        if let Col::V(v) = &mut acc.cols[310] { v.push(AV::Bool(kv.c310)); }
        if let Col::N(v) = &mut acc.cols[316] { v.push(sh.c316[i]); }
        if let Col::N(v) = &mut acc.cols[317] { v.push(sh.c317[i]); }
        if let Col::V(v) = &mut acc.cols[398] { v.push(AV::Bool(sh.c398.val & (1 << i) != 0)); }
        if let Col::I(v) = &mut acc.cols[404] { v.push((sh.c404.lo[i], sh.c404.hi[i])); }
        if let Col::I(v) = &mut acc.cols[405] { v.push((sh.c405.lo[i], sh.c405.hi[i])); }
        if let Col::N(v) = &mut acc.cols[406] { v.push(kv.c406[i]); }
        if let Col::N(v) = &mut acc.cols[407] { v.push(kv.c407[i]); }
        let val = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[394] { v.push(val); }
        let val = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[395] { v.push(val); }
        let val = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[396] { v.push(val); }
        let val = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[397] { v.push(val); }
        acc.width += 1;
    }
}

/// Cells the pre-dedup key covers, in key-bit order.
pub const KEY_CELLS: &[u32] = &[
    38,
    39,
    84,
    87,
    246,
    254,
    297,
    300,
    302,
    309,
    310,
    316,
    317,
    398,
    404,
    405,
    406,
    407,
    394,
    395,
    396,
    397,
];

#[allow(unused_variables)]
pub fn row_keys(chunk: &Rt2, lo: usize, n: usize, sh: &KOutShared, kv: &KOut, plan: &KeyPlan, keys: &mut [(u64, u64); W]) {
    let mut h1 = [0u64; W];
    let mut h2 = [0u64; W];
    // cell 38 (bool)
    if plan.rem & (1 << 0) == 0 {
        assert!(plan.det & (1 << 0) == 0, "det clamp on non-numeric cell 38");
        for i in 0..W {
            let v = AV::Bool(sh.c38);
            h1[i] = h1[i].wrapping_add(cell_mix(38u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(38u64, v, 0x27d4_eb2f));
        }
    }
    // cell 39 (P8)
    if plan.rem & (1 << 1) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (39u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (39u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c39;
            let v = if plan.det & (1 << 1) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 84 (P8)
    if plan.rem & (1 << 2) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c84;
            let v = if plan.det & (1 << 2) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 87 (P8)
    if plan.rem & (1 << 3) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (87u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (87u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c87;
            let v = if plan.det & (1 << 3) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 246 ((P8, P8))
    if plan.rem & (1 << 4) == 0 {
        assert!(plan.det & (1 << 4) == 0, "det clamp on non-numeric cell 246");
        for i in 0..W {
            let v = AV::Ival(sh.c246.0, sh.c246.1);
            h1[i] = h1[i].wrapping_add(cell_mix(246u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(246u64, v, 0x27d4_eb2f));
        }
    }
    // cell 254 ((P8, P8))
    if plan.rem & (1 << 5) == 0 {
        assert!(plan.det & (1 << 5) == 0, "det clamp on non-numeric cell 254");
        for i in 0..W {
            let v = AV::Ival(sh.c254.0, sh.c254.1);
            h1[i] = h1[i].wrapping_add(cell_mix(254u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(254u64, v, 0x27d4_eb2f));
        }
    }
    // cell 297 (ZN)
    if plan.rem & (1 << 6) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c297[i];
            let v = if plan.det & (1 << 6) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 300 (ZN)
    if plan.rem & (1 << 7) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c300[i];
            let v = if plan.det & (1 << 7) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 302 (ZN)
    if plan.rem & (1 << 8) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = kv.c302[i];
            let v = if plan.det & (1 << 8) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 309 (bool)
    if plan.rem & (1 << 9) == 0 {
        assert!(plan.det & (1 << 9) == 0, "det clamp on non-numeric cell 309");
        for i in 0..W {
            let v = AV::Bool(kv.c309);
            h1[i] = h1[i].wrapping_add(cell_mix(309u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(309u64, v, 0x27d4_eb2f));
        }
    }
    // cell 310 (bool)
    if plan.rem & (1 << 10) == 0 {
        assert!(plan.det & (1 << 10) == 0, "det clamp on non-numeric cell 310");
        for i in 0..W {
            let v = AV::Bool(kv.c310);
            h1[i] = h1[i].wrapping_add(cell_mix(310u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(310u64, v, 0x27d4_eb2f));
        }
    }
    // cell 316 (ZN)
    if plan.rem & (1 << 11) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c316[i];
            let v = if plan.det & (1 << 11) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 317 (ZN)
    if plan.rem & (1 << 12) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c317[i];
            let v = if plan.det & (1 << 12) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 398 (ZB)
    if plan.rem & (1 << 13) == 0 {
        assert!(plan.det & (1 << 13) == 0, "det clamp on non-numeric cell 398");
        for i in 0..W {
            let v = AV::Bool(sh.c398.val & (1 << i) != 0);
            h1[i] = h1[i].wrapping_add(cell_mix(398u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(398u64, v, 0x27d4_eb2f));
        }
    }
    // cell 404 (ZI)
    if plan.rem & (1 << 14) == 0 {
        assert!(plan.det & (1 << 14) == 0, "det clamp on non-numeric cell 404");
        for i in 0..W {
            let v = AV::Ival(sh.c404.lo[i], sh.c404.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(404u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(404u64, v, 0x27d4_eb2f));
        }
    }
    // cell 405 (ZI)
    if plan.rem & (1 << 15) == 0 {
        assert!(plan.det & (1 << 15) == 0, "det clamp on non-numeric cell 405");
        for i in 0..W {
            let v = AV::Ival(sh.c405.lo[i], sh.c405.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(405u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(405u64, v, 0x27d4_eb2f));
        }
    }
    // cell 406 (ZN)
    if plan.rem & (1 << 16) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = kv.c406[i];
            let v = if plan.det & (1 << 16) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 407 (ZN)
    if plan.rem & (1 << 17) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = kv.c407[i];
            let v = if plan.det & (1 << 17) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 394 (IN_N)
    if plan.rem & (1 << 18) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 18) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 395 (IN_N)
    if plan.rem & (1 << 19) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 19) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 396 (IN_N)
    if plan.rem & (1 << 20) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 20) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 397 (IN_N)
    if plan.rem & (1 << 21) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 21) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    for i in 0..W {
        keys[i] = (mix64(h1[i]), mix64(h2[i]));
    }
}

#[inline(never)]
pub fn frame(u: &Uni, rin: &RowsIn, g: &G, out: &mut impl FnMut(u8, &KOutShared, &KOut)) {
    let r_c297: ZN = rin.c297;
    let r_c302: ZN = rin.c302;
    let r_c316: ZN = rin.c316;
    let r_c317: ZN = rin.c317;
    let r_c394: ZN = rin.c394;
    let r_c395: ZN = rin.c395;
    let r_c396: ZN = rin.c396;
    let r_c397: ZN = rin.c397;
    let r_c398: ZB = ZB { val: rin.c398, known: ALL };
    let r_c406: ZN = rin.c406;
    let r_c407: ZN = rin.c407;
    let n4: P8 = u.c84 + P8::from_raw(65536i32);
    let n6: P8 = n4 % P8::from_raw(1966080i32);
    let n77: ZN = zn_add(r_c316, zn_splat(u.c402));
    let n85: ZN = zn_add(r_c317, zn_splat(u.c403));
    let n105: (P8, P8) = si_add(u.c246, (P8::from_raw(65536i32), P8::from_raw(65536i32)));
    let n114: (P8, P8) = { let r = IV::new((P8::from_raw(-65536i32), P8::from_raw(65536i32)).0, (P8::from_raw(-65536i32), P8::from_raw(65536i32)).1).scale_positive(P8::from_raw(163840i32)); (r.low, r.high) };
    let n116: (P8, P8) = si_add((u.c251, u.c251), n114);
    let n241: ZI = zi_add(zi_splat(u.c404.0, u.c404.1), zi_of_zn(r_c406));
    let n243: ZI = zi_add(n241, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n274: ZN = zn_add(n85, zn_splat(P8::from_raw(0i32)));
    let n668: ZI = zi_add(zi_splat(u.c405.0, u.c405.1), zi_of_zn(r_c407));
    let n669: ZI = zi_add(n668, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n1449: P8 = u.c87 + P8::from_raw(65536i32);
    let n1483: bool = !u.c310;
    let n1492: bool = u.c300 < u.c88;
    let n1493: P8 = if n1492 { u.c88 } else { u.c300 };
    let n1495: ZB = zn_gt(r_c302, zn_splat(P8::from_raw(0i32)));
    let n1496: ZN = zn_sub(r_c302, zn_splat(P8::from_raw(65536i32)));
    let n1497: ZN = zsel_n(n1495, n1496, r_c302);
    let n1503: ZN = zn_sub(r_c297, zn_splat(P8::from_raw(65536i32)));
    for c0 in 0..2usize {
    let (f0, f0_fv): (ZI, u16) = zi_fork_flr(n243, c0);
    let valid0: u16 = ALL & f0_fv;
    if valid0 == 0 { continue; }
    let n248: ZN = zi_flr(f0);
    let n251: ZI = zi_sub(f0, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n252: ZI = zi_sub(n251, zi_of_zn(n248));
    let n255: ZB = zn_gt(n248, zn_splat(P8::from_raw(0i32)));
    let n256: ZB = zn_lt(n248, zn_splat(P8::from_raw(0i32)));
    let n257: ZB = zsel_b(n255, n255, n256);
    let n261: ZN = zsel_n(n255, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)));
    let n263: ZN = zsel_n(n257, n261, zn_splat(P8::from_raw(0i32)));
    let n266: ZN = zn_abs(n248);
    let n272: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n266);
    let n273: ZN = zn_add(n77, n263);
    let n275: ZB = zn_tile_flag_at(g.cache, g.cart, n273, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n294: ZB = zsel_b(n275, n275, zb_splat(false));
    let n297: ZB = zsel_b(n294, n294, zb_splat(false));
    let n300: ZB = zb_not(n297);
    let n301: ZB = zsel_b(n272, n300, n272);
    let n304: ZB = zb_not(n300);
    let n305: ZB = zsel_b(n272, n304, n272);
    let n307: ZN = zn_add(r_c316, n263);
    let n308: ZN = zsel_n(n301, n307, r_c316);
    let n311: ZN = zsel_n(n305, zn_splat(P8::from_raw(0i32)), r_c406);
    let n314: ZI = zsel_i(n305, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n252);
    let n316: ZN = zsel_n(n301, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n318: ZB = zsel_b(n305, zb_splat(false), zb_splat(true));
    let n320: ZB = zn_le(n316, n266);
    let n321: ZN = zn_add(n308, zn_splat(u.c402));
    let n322: ZN = zn_add(n321, n263);
    let n323: ZB = zn_tile_flag_at(g.cache, g.cart, n322, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n334: ZB = zsel_b(n323, n323, zb_splat(false));
    let n337: ZB = zsel_b(n334, n334, zb_splat(false));
    let n340: ZB = zb_not(n337);
    let n341: ZB = zsel_b(n318, n320, n318);
    let n344: ZB = zsel_b(n341, n340, n341);
    let n347: ZB = zb_not(n340);
    let n348: ZB = zsel_b(n341, n347, n341);
    let n350: ZN = zn_add(n308, n263);
    let n351: ZN = zsel_n(n344, n350, n308);
    let n354: ZN = zn_add(n316, zn_splat(P8::from_raw(65536i32)));
    let n355: ZN = zsel_n(n348, zn_splat(P8::from_raw(0i32)), n311);
    let n358: ZI = zsel_i(n348, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n314);
    let n360: ZN = zsel_n(n344, n354, n316);
    let n362: ZB = zsel_b(n348, zb_splat(false), n318);
    let n364: ZB = zn_le(n360, n266);
    let n365: ZN = zn_add(n351, zn_splat(u.c402));
    let n366: ZN = zn_add(n365, n263);
    let n367: ZB = zn_tile_flag_at(g.cache, g.cart, n366, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n378: ZB = zsel_b(n367, n367, zb_splat(false));
    let n381: ZB = zsel_b(n378, n378, zb_splat(false));
    let n384: ZB = zb_not(n381);
    let n385: ZB = zsel_b(n362, n364, n362);
    let n388: ZB = zsel_b(n385, n384, n385);
    let n391: ZB = zb_not(n384);
    let n392: ZB = zsel_b(n385, n391, n385);
    let n394: ZN = zn_add(n351, n263);
    let n395: ZN = zsel_n(n388, n394, n351);
    let n398: ZN = zn_add(n360, zn_splat(P8::from_raw(65536i32)));
    let n399: ZN = zsel_n(n392, zn_splat(P8::from_raw(0i32)), n355);
    let n402: ZI = zsel_i(n392, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n358);
    let n404: ZN = zsel_n(n388, n398, n360);
    let n406: ZB = zsel_b(n392, zb_splat(false), n362);
    let n408: ZB = zn_le(n404, n266);
    let n409: ZN = zn_add(n395, zn_splat(u.c402));
    let n410: ZN = zn_add(n409, n263);
    let n411: ZB = zn_tile_flag_at(g.cache, g.cart, n410, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n422: ZB = zsel_b(n411, n411, zb_splat(false));
    let n425: ZB = zsel_b(n422, n422, zb_splat(false));
    let n428: ZB = zb_not(n425);
    let n429: ZB = zsel_b(n406, n408, n406);
    let n432: ZB = zsel_b(n429, n428, n429);
    let n435: ZB = zb_not(n428);
    let n436: ZB = zsel_b(n429, n435, n429);
    let n438: ZN = zn_add(n395, n263);
    let n439: ZN = zsel_n(n432, n438, n395);
    let n442: ZN = zn_add(n404, zn_splat(P8::from_raw(65536i32)));
    let n443: ZN = zsel_n(n436, zn_splat(P8::from_raw(0i32)), n399);
    let n446: ZI = zsel_i(n436, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n402);
    let n448: ZN = zsel_n(n432, n442, n404);
    let n450: ZB = zsel_b(n436, zb_splat(false), n406);
    let n452: ZB = zn_le(n448, n266);
    let n453: ZN = zn_add(n439, zn_splat(u.c402));
    let n454: ZN = zn_add(n453, n263);
    let n455: ZB = zn_tile_flag_at(g.cache, g.cart, n454, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n466: ZB = zsel_b(n455, n455, zb_splat(false));
    let n469: ZB = zsel_b(n466, n466, zb_splat(false));
    let n472: ZB = zb_not(n469);
    let n473: ZB = zsel_b(n450, n452, n450);
    let n476: ZB = zsel_b(n473, n472, n473);
    let n479: ZB = zb_not(n472);
    let n480: ZB = zsel_b(n473, n479, n473);
    let n482: ZN = zn_add(n439, n263);
    let n483: ZN = zsel_n(n476, n482, n439);
    let n486: ZN = zn_add(n448, zn_splat(P8::from_raw(65536i32)));
    let n487: ZN = zsel_n(n480, zn_splat(P8::from_raw(0i32)), n443);
    let n490: ZI = zsel_i(n480, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n446);
    let n492: ZN = zsel_n(n476, n486, n448);
    let n494: ZB = zsel_b(n480, zb_splat(false), n450);
    let n496: ZB = zn_le(n492, n266);
    let n497: ZN = zn_add(n483, zn_splat(u.c402));
    let n498: ZN = zn_add(n497, n263);
    let n499: ZB = zn_tile_flag_at(g.cache, g.cart, n498, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n510: ZB = zsel_b(n499, n499, zb_splat(false));
    let n513: ZB = zsel_b(n510, n510, zb_splat(false));
    let n516: ZB = zb_not(n513);
    let n517: ZB = zsel_b(n494, n496, n494);
    let n520: ZB = zsel_b(n517, n516, n517);
    let n523: ZB = zb_not(n516);
    let n524: ZB = zsel_b(n517, n523, n517);
    let n526: ZN = zn_add(n483, n263);
    let n527: ZN = zsel_n(n520, n526, n483);
    let n530: ZN = zn_add(n492, zn_splat(P8::from_raw(65536i32)));
    let n531: ZN = zsel_n(n524, zn_splat(P8::from_raw(0i32)), n487);
    let n534: ZI = zsel_i(n524, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n490);
    let n536: ZN = zsel_n(n520, n530, n492);
    let n538: ZB = zsel_b(n524, zb_splat(false), n494);
    let n540: ZB = zn_le(n536, n266);
    let n541: ZN = zn_add(n527, zn_splat(u.c402));
    let n542: ZN = zn_add(n541, n263);
    let n543: ZB = zn_tile_flag_at(g.cache, g.cart, n542, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n554: ZB = zsel_b(n543, n543, zb_splat(false));
    let n557: ZB = zsel_b(n554, n554, zb_splat(false));
    let n560: ZB = zb_not(n557);
    let n561: ZB = zsel_b(n538, n540, n538);
    let n564: ZB = zsel_b(n561, n560, n561);
    let n567: ZB = zb_not(n560);
    let n568: ZB = zsel_b(n561, n567, n561);
    let n570: ZN = zn_add(n527, n263);
    let n571: ZN = zsel_n(n564, n570, n527);
    let n574: ZN = zn_add(n536, zn_splat(P8::from_raw(65536i32)));
    let n575: ZN = zsel_n(n568, zn_splat(P8::from_raw(0i32)), n531);
    let n578: ZI = zsel_i(n568, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n534);
    let n580: ZN = zsel_n(n564, n574, n536);
    let n582: ZB = zsel_b(n568, zb_splat(false), n538);
    let n584: ZB = zn_le(n580, n266);
    let n585: ZN = zn_add(n571, zn_splat(u.c402));
    let n586: ZN = zn_add(n585, n263);
    let n587: ZB = zn_tile_flag_at(g.cache, g.cart, n586, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n598: ZB = zsel_b(n587, n587, zb_splat(false));
    let n601: ZB = zsel_b(n598, n598, zb_splat(false));
    let n604: ZB = zb_not(n601);
    let n605: ZB = zsel_b(n582, n584, n582);
    let n608: ZB = zsel_b(n605, n604, n605);
    let n611: ZB = zb_not(n604);
    let n612: ZB = zsel_b(n605, n611, n605);
    let n614: ZN = zn_add(n571, n263);
    let n615: ZN = zsel_n(n608, n614, n571);
    let n618: ZN = zn_add(n580, zn_splat(P8::from_raw(65536i32)));
    let n619: ZN = zsel_n(n612, zn_splat(P8::from_raw(0i32)), n575);
    let n622: ZI = zsel_i(n612, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n578);
    let n624: ZN = zsel_n(n608, n618, n580);
    let n626: ZB = zsel_b(n612, zb_splat(false), n582);
    let n628: ZB = zn_le(n624, n266);
    let n629: ZN = zn_add(n615, zn_splat(u.c402));
    let n630: ZN = zn_add(n629, n263);
    let n631: ZB = zn_tile_flag_at(g.cache, g.cart, n630, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n642: ZB = zsel_b(n631, n631, zb_splat(false));
    let n645: ZB = zsel_b(n642, n642, zb_splat(false));
    let n648: ZB = zb_not(n645);
    let n649: ZB = zsel_b(n626, n628, n626);
    let n652: ZB = zsel_b(n649, n648, n649);
    let n655: ZB = zb_not(n648);
    let n656: ZB = zsel_b(n649, n655, n649);
    let n658: ZN = zn_add(n615, n263);
    let n659: ZN = zsel_n(n652, n658, n615);
    let n662: ZN = zsel_n(n656, zn_splat(P8::from_raw(0i32)), n619);
    let n665: ZI = zsel_i(n656, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n622);
    let n697: ZN = zn_add(n659, zn_splat(u.c402));
    let n698: ZN = zn_add(n697, zn_splat(P8::from_raw(0i32)));
    let n1515: ZN = zn_abs(n662);
    let n1516: ZB = zn_gt(n1515, zn_splat(P8::from_raw(65536i32)));
    let n1517: ZB = zn_gt(n662, zn_splat(P8::from_raw(0i32)));
    let n1518: ZB = zsel_b(n1517, zb_splat(true), n1517);
    let n1520: ZN = zsel_n(n1517, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n1521: ZB = zn_lt(n662, zn_splat(P8::from_raw(0i32)));
    let n1522: ZB = zsel_b(n1518, n1518, n1521);
    let n1524: ZN = zsel_n(n1518, n1520, zn_splat(P8::from_raw(-65536i32)));
    let n1525: ZN = zsel_n(n1522, n1524, zn_splat(P8::from_raw(0i32)));
    let n1527: ZN = zn_mul(n1525, zn_splat(P8::from_raw(65536i32)));
    let n1528: ZB = zn_gt(n662, n1527);
    let n1530: ZN = zn_sub(n662, zn_splat(P8::from_raw(9830i32)));
    let n1531: ZN = zn_max(n1530, n1527);
    let n1532: ZN = zn_add(n662, zn_splat(P8::from_raw(9830i32)));
    let n1533: ZN = zn_min(n1532, n1527);
    let n1534: ZN = zsel_n(n1528, n1531, n1533);
    let n1536: ZB = zn_gt(n662, zn_splat(P8::from_raw(65536i32)));
    let n1557: ZN = zn_add(n697, zn_splat(P8::from_raw(65536i32)));
    let n1590: ZN = zn_add(n697, zn_splat(P8::from_raw(-196608i32)));
    let n1604: ZN = zn_add(n697, zn_splat(P8::from_raw(196608i32)));
    for c1 in 0..2usize {
    let (f1, f1_fv): (ZI, u16) = zi_fork_flr(n669, c1);
    let valid1: u16 = valid0 & f1_fv;
    if valid1 == 0 { continue; }
    let n675: ZN = zi_flr(f1);
    let n678: ZI = zi_sub(f1, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n679: ZI = zi_sub(n678, zi_of_zn(n675));
    let n680: ZB = zn_gt(n675, zn_splat(P8::from_raw(0i32)));
    let n681: ZB = zn_lt(n675, zn_splat(P8::from_raw(0i32)));
    let n682: ZB = zsel_b(n680, n680, n681);
    let n685: ZN = zsel_n(n680, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)));
    let n687: ZN = zsel_n(n682, n685, zn_splat(P8::from_raw(0i32)));
    let n690: ZN = zn_abs(n675);
    let n695: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n690);
    let n696: ZB = zn_gt(n687, zn_splat(P8::from_raw(0i32)));
    let n709: ZB = zsel_b(n696, zb_splat(true), n696);
    let n712: ZN = zn_add(n85, n687);
    let n722: ZB = zsel_b(n709, zb_splat(false), n709);
    let n725: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n712, u.c401, u.c400, P8::from_raw(0i32));
    let n726: ZB = zsel_b(n725, n725, zb_splat(false));
    let n729: ZB = zsel_b(n726, n726, zb_splat(false));
    let n732: ZB = zsel_b(n722, zb_splat(true), n729);
    let n735: ZB = zb_not(n732);
    let n736: ZB = zsel_b(n695, n735, n695);
    let n739: ZB = zb_not(n735);
    let n740: ZB = zsel_b(n695, n739, n695);
    let n742: ZN = zn_add(r_c317, n687);
    let n743: ZN = zsel_n(n736, n742, r_c317);
    let n746: ZN = zsel_n(n740, zn_splat(P8::from_raw(0i32)), r_c407);
    let n749: ZI = zsel_i(n740, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n679);
    let n751: ZN = zsel_n(n736, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n753: ZB = zsel_b(n740, zb_splat(false), zb_splat(true));
    let n755: ZB = zn_le(n751, n690);
    let n756: ZN = zn_add(n743, zn_splat(u.c403));
    let n768: ZN = zn_add(n756, n687);
    let n778: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n768, u.c401, u.c400, P8::from_raw(0i32));
    let n779: ZB = zsel_b(n778, n778, zb_splat(false));
    let n782: ZB = zsel_b(n779, n779, zb_splat(false));
    let n785: ZB = zsel_b(n722, zb_splat(true), n782);
    let n787: ZB = zb_not(n785);
    let n788: ZB = zsel_b(n753, n755, n753);
    let n791: ZB = zsel_b(n788, n787, n788);
    let n794: ZB = zb_not(n787);
    let n795: ZB = zsel_b(n788, n794, n788);
    let n797: ZN = zn_add(n743, n687);
    let n798: ZN = zsel_n(n791, n797, n743);
    let n801: ZN = zn_add(n751, zn_splat(P8::from_raw(65536i32)));
    let n802: ZN = zsel_n(n795, zn_splat(P8::from_raw(0i32)), n746);
    let n805: ZI = zsel_i(n795, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n749);
    let n807: ZN = zsel_n(n791, n801, n751);
    let n809: ZB = zsel_b(n795, zb_splat(false), n753);
    let n811: ZB = zn_le(n807, n690);
    let n812: ZN = zn_add(n798, zn_splat(u.c403));
    let n824: ZN = zn_add(n812, n687);
    let n834: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n824, u.c401, u.c400, P8::from_raw(0i32));
    let n835: ZB = zsel_b(n834, n834, zb_splat(false));
    let n838: ZB = zsel_b(n835, n835, zb_splat(false));
    let n841: ZB = zsel_b(n722, zb_splat(true), n838);
    let n843: ZB = zb_not(n841);
    let n844: ZB = zsel_b(n809, n811, n809);
    let n847: ZB = zsel_b(n844, n843, n844);
    let n850: ZB = zb_not(n843);
    let n851: ZB = zsel_b(n844, n850, n844);
    let n853: ZN = zn_add(n798, n687);
    let n854: ZN = zsel_n(n847, n853, n798);
    let n857: ZN = zn_add(n807, zn_splat(P8::from_raw(65536i32)));
    let n858: ZN = zsel_n(n851, zn_splat(P8::from_raw(0i32)), n802);
    let n861: ZI = zsel_i(n851, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n805);
    let n863: ZN = zsel_n(n847, n857, n807);
    let n865: ZB = zsel_b(n851, zb_splat(false), n809);
    let n867: ZB = zn_le(n863, n690);
    let n868: ZN = zn_add(n854, zn_splat(u.c403));
    let n880: ZN = zn_add(n868, n687);
    let n890: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n880, u.c401, u.c400, P8::from_raw(0i32));
    let n891: ZB = zsel_b(n890, n890, zb_splat(false));
    let n894: ZB = zsel_b(n891, n891, zb_splat(false));
    let n897: ZB = zsel_b(n722, zb_splat(true), n894);
    let n899: ZB = zb_not(n897);
    let n900: ZB = zsel_b(n865, n867, n865);
    let n903: ZB = zsel_b(n900, n899, n900);
    let n906: ZB = zb_not(n899);
    let n907: ZB = zsel_b(n900, n906, n900);
    let n909: ZN = zn_add(n854, n687);
    let n910: ZN = zsel_n(n903, n909, n854);
    let n913: ZN = zn_add(n863, zn_splat(P8::from_raw(65536i32)));
    let n914: ZN = zsel_n(n907, zn_splat(P8::from_raw(0i32)), n858);
    let n917: ZI = zsel_i(n907, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n861);
    let n919: ZN = zsel_n(n903, n913, n863);
    let n921: ZB = zsel_b(n907, zb_splat(false), n865);
    let n923: ZB = zn_le(n919, n690);
    let n924: ZN = zn_add(n910, zn_splat(u.c403));
    let n936: ZN = zn_add(n924, n687);
    let n946: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n936, u.c401, u.c400, P8::from_raw(0i32));
    let n947: ZB = zsel_b(n946, n946, zb_splat(false));
    let n950: ZB = zsel_b(n947, n947, zb_splat(false));
    let n953: ZB = zsel_b(n722, zb_splat(true), n950);
    let n955: ZB = zb_not(n953);
    let n956: ZB = zsel_b(n921, n923, n921);
    let n959: ZB = zsel_b(n956, n955, n956);
    let n962: ZB = zb_not(n955);
    let n963: ZB = zsel_b(n956, n962, n956);
    let n965: ZN = zn_add(n910, n687);
    let n966: ZN = zsel_n(n959, n965, n910);
    let n969: ZN = zn_add(n919, zn_splat(P8::from_raw(65536i32)));
    let n970: ZN = zsel_n(n963, zn_splat(P8::from_raw(0i32)), n914);
    let n973: ZI = zsel_i(n963, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n917);
    let n975: ZN = zsel_n(n959, n969, n919);
    let n977: ZB = zsel_b(n963, zb_splat(false), n921);
    let n979: ZB = zn_le(n975, n690);
    let n980: ZN = zn_add(n966, zn_splat(u.c403));
    let n992: ZN = zn_add(n980, n687);
    let n1002: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n992, u.c401, u.c400, P8::from_raw(0i32));
    let n1003: ZB = zsel_b(n1002, n1002, zb_splat(false));
    let n1006: ZB = zsel_b(n1003, n1003, zb_splat(false));
    let n1009: ZB = zsel_b(n722, zb_splat(true), n1006);
    let n1011: ZB = zb_not(n1009);
    let n1012: ZB = zsel_b(n977, n979, n977);
    let n1015: ZB = zsel_b(n1012, n1011, n1012);
    let n1018: ZB = zb_not(n1011);
    let n1019: ZB = zsel_b(n1012, n1018, n1012);
    let n1021: ZN = zn_add(n966, n687);
    let n1022: ZN = zsel_n(n1015, n1021, n966);
    let n1025: ZN = zn_add(n975, zn_splat(P8::from_raw(65536i32)));
    let n1026: ZN = zsel_n(n1019, zn_splat(P8::from_raw(0i32)), n970);
    let n1029: ZI = zsel_i(n1019, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n973);
    let n1031: ZN = zsel_n(n1015, n1025, n975);
    let n1033: ZB = zsel_b(n1019, zb_splat(false), n977);
    let n1035: ZB = zn_le(n1031, n690);
    let n1036: ZN = zn_add(n1022, zn_splat(u.c403));
    let n1048: ZN = zn_add(n1036, n687);
    let n1058: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n1048, u.c401, u.c400, P8::from_raw(0i32));
    let n1059: ZB = zsel_b(n1058, n1058, zb_splat(false));
    let n1062: ZB = zsel_b(n1059, n1059, zb_splat(false));
    let n1065: ZB = zsel_b(n722, zb_splat(true), n1062);
    let n1067: ZB = zb_not(n1065);
    let n1068: ZB = zsel_b(n1033, n1035, n1033);
    let n1071: ZB = zsel_b(n1068, n1067, n1068);
    let n1074: ZB = zb_not(n1067);
    let n1075: ZB = zsel_b(n1068, n1074, n1068);
    let n1077: ZN = zn_add(n1022, n687);
    let n1078: ZN = zsel_n(n1071, n1077, n1022);
    let n1081: ZN = zn_add(n1031, zn_splat(P8::from_raw(65536i32)));
    let n1082: ZN = zsel_n(n1075, zn_splat(P8::from_raw(0i32)), n1026);
    let n1085: ZI = zsel_i(n1075, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1029);
    let n1087: ZN = zsel_n(n1071, n1081, n1031);
    let n1089: ZB = zsel_b(n1075, zb_splat(false), n1033);
    let n1091: ZB = zn_le(n1087, n690);
    let n1092: ZN = zn_add(n1078, zn_splat(u.c403));
    let n1104: ZN = zn_add(n1092, n687);
    let n1114: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n1104, u.c401, u.c400, P8::from_raw(0i32));
    let n1115: ZB = zsel_b(n1114, n1114, zb_splat(false));
    let n1118: ZB = zsel_b(n1115, n1115, zb_splat(false));
    let n1121: ZB = zsel_b(n722, zb_splat(true), n1118);
    let n1123: ZB = zb_not(n1121);
    let n1124: ZB = zsel_b(n1089, n1091, n1089);
    let n1127: ZB = zsel_b(n1124, n1123, n1124);
    let n1130: ZB = zb_not(n1123);
    let n1131: ZB = zsel_b(n1124, n1130, n1124);
    let n1133: ZN = zn_add(n1078, n687);
    let n1134: ZN = zsel_n(n1127, n1133, n1078);
    let n1137: ZN = zn_add(n1087, zn_splat(P8::from_raw(65536i32)));
    let n1138: ZN = zsel_n(n1131, zn_splat(P8::from_raw(0i32)), n1082);
    let n1141: ZI = zsel_i(n1131, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1085);
    let n1143: ZN = zsel_n(n1127, n1137, n1087);
    let n1145: ZB = zsel_b(n1131, zb_splat(false), n1089);
    let n1147: ZB = zn_le(n1143, n690);
    let n1148: ZN = zn_add(n1134, zn_splat(u.c403));
    let n1160: ZN = zn_add(n1148, n687);
    let n1170: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n1160, u.c401, u.c400, P8::from_raw(0i32));
    let n1171: ZB = zsel_b(n1170, n1170, zb_splat(false));
    let n1174: ZB = zsel_b(n1171, n1171, zb_splat(false));
    let n1177: ZB = zsel_b(n722, zb_splat(true), n1174);
    let n1179: ZB = zb_not(n1177);
    let n1180: ZB = zsel_b(n1145, n1147, n1145);
    let n1183: ZB = zsel_b(n1180, n1179, n1180);
    let n1186: ZB = zb_not(n1179);
    let n1187: ZB = zsel_b(n1180, n1186, n1180);
    let n1189: ZN = zn_add(n1134, n687);
    let n1190: ZN = zsel_n(n1183, n1189, n1134);
    let n1193: ZN = zsel_n(n1187, zn_splat(P8::from_raw(0i32)), n1138);
    let n1196: ZI = zsel_i(n1187, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1141);
    let n1208: ZN = zn_add(n1190, zn_splat(u.c403));
    let n1455: ZN = zn_add(n1208, zn_splat(P8::from_raw(0i32)));
    let n1463: ZN = zn_add(n1208, zn_splat(P8::from_raw(65536i32)));
    let n1471: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n1463, u.c401, u.c400, P8::from_raw(0i32));
    let n1472: ZB = zsel_b(n1471, n1471, zb_splat(false));
    let n1474: ZB = zsel_b(n1472, n1472, zb_splat(false));
    let n1477: ZB = zn_tile_flag_at(g.cache, g.cart, n698, n1463, u.c401, u.c400, P8::from_raw(262144i32));
    let n1499: ZN = zsel_n(n1474, zn_splat(P8::from_raw(393216i32)), n1497);
    let n1501: ZN = zsel_n(n1474, zn_splat(n1493), zn_splat(u.c300));
    let n1507: ZB = zb_not(n1474);
    let n1510: ZN = zsel_n(n1477, zn_splat(P8::from_raw(3276i32)), zn_splat(P8::from_raw(39321i32)));
    let n1513: ZN = zsel_n(n1507, zn_splat(P8::from_raw(26214i32)), n1510);
    let n1537: ZN = zn_sub(n662, n1513);
    let n1538: ZN = zn_max(n1537, zn_splat(P8::from_raw(65536i32)));
    let n1539: ZN = zn_add(n662, n1513);
    let n1540: ZN = zn_min(n1539, zn_splat(P8::from_raw(65536i32)));
    let n1541: ZN = zsel_n(n1536, n1538, n1540);
    let n1543: ZN = zsel_n(n1516, n1534, n1541);
    let n1545: ZB = zn_eq(n1543, zn_splat(P8::from_raw(0i32)));
    let n1546: ZB = zb_not(n1545);
    let n1547: ZB = zn_lt(n1543, zn_splat(P8::from_raw(0i32)));
    let n1549: ZB = zsel_b(n1546, n1547, r_c398);
    let n1551: ZN = zn_abs(n1193);
    let n1552: ZB = zn_le(n1551, zn_splat(P8::from_raw(9830i32)));
    let n1555: ZN = zsel_n(n1552, zn_splat(P8::from_raw(6881i32)), zn_splat(P8::from_raw(13762i32)));
    let n1558: ZB = zn_tile_flag_at(g.cache, g.cart, n1557, n1455, u.c401, u.c400, P8::from_raw(0i32));
    let n1566: ZB = zsel_b(n1558, n1558, zb_splat(false));
    let n1568: ZB = zsel_b(n1566, n1566, zb_splat(false));
    let n1570: ZB = zn_tile_flag_at(g.cache, g.cart, n1557, n1455, u.c401, u.c400, P8::from_raw(262144i32));
    let n1571: ZB = zb_not(n1570);
    let n1572: ZB = zsel_b(n1568, n1571, n1568);
    let n1574: ZN = zsel_n(n1572, zn_splat(P8::from_raw(26214i32)), zn_splat(P8::from_raw(131072i32)));
    let n1576: ZB = zn_gt(n1193, n1574);
    let n1577: ZN = zn_sub(n1193, n1555);
    let n1578: ZN = zn_max(n1577, n1574);
    let n1579: ZN = zn_add(n1193, n1555);
    let n1580: ZN = zn_min(n1579, n1574);
    let n1581: ZN = zsel_n(n1576, n1578, n1580);
    let n1583: ZN = zsel_n(n1507, n1581, n1193);
    let n1584: ZB = zn_gt(n1499, zn_splat(P8::from_raw(0i32)));
    let n1585: ZN = zsel_n(n1584, zn_splat(P8::from_raw(0i32)), n1499);
    let n1588: ZN = zsel_n(n1584, zn_splat(P8::from_raw(-131072i32)), n1583);
    let n1591: ZB = zn_tile_flag_at(g.cache, g.cart, n1590, n1455, u.c401, u.c400, P8::from_raw(0i32));
    let n1599: ZB = zsel_b(n1591, n1591, zb_splat(false));
    let n1601: ZB = zsel_b(n1599, n1599, zb_splat(false));
    let n1605: ZB = zn_tile_flag_at(g.cache, g.cart, n1604, n1455, u.c401, u.c400, P8::from_raw(0i32));
    let n1613: ZB = zsel_b(n1605, n1605, zb_splat(false));
    let n1615: ZB = zsel_b(n1613, n1613, zb_splat(false));
    let n1617: ZB = zsel_b(n1601, n1601, n1615);
    let n1619: ZN = zsel_n(n1601, zn_splat(P8::from_raw(-65536i32)), zn_splat(P8::from_raw(65536i32)));
    let n1620: ZN = zsel_n(n1617, n1619, zn_splat(P8::from_raw(0i32)));
    let n1622: ZB = zn_eq(n1620, zn_splat(P8::from_raw(0i32)));
    let n1623: ZB = zb_not(n1622);
    let n1624: ZN = zn_neg(n1620);
    let n1625: ZN = zn_mul(n1624, zn_splat(P8::from_raw(131072i32)));
    let n1629: ZN = zsel_n(n1623, n1625, n1543);
    let n1630: ZN = zsel_n(n1584, n1543, n1629);
    let n1648: ZN = if n1483 { n1585 } else { n1499 };
    let n1649: ZN = if n1483 { n1588 } else { n1583 };
    let n1650: ZN = zsel_n(n1623, zn_splat(P8::from_raw(-131072i32)), n1649);
    let n1651: ZN = zsel_n(n1584, n1649, n1650);
    let n1652: ZN = if n1483 { n1651 } else { n1649 };
    let n1653: ZN = if n1483 { n1630 } else { n1543 };
    let ok_v0: u16 = ALL;
    let bd_v0: bool = true;
    let ok_v16: u16 = ALL;
    let bd_v16: bool = true;
    let ok_v32: u16 = ALL;
    let bd_v32: bool = true;
    let ok_v48: u16 = ALL;
    let bd_v48: bool = true;
    let osh = KOutShared {
        c38: true,
        c39: P8::from_raw(983040i32),
        c84: n6,
        c87: n1449,
        c246: n105,
        c254: n116,
        c297: n1503,
        c300: n1501,
        c316: n659,
        c317: n1190,
        c398: n1549,
        c404: n665,
        c405: n1196,
    };
    // 4 of 64 free assignments are distinct successors
    out(0, &osh, &KOut {
        valid: valid1,
        deopt: !ok_v0,
        bd: bd_v0,
        c302: n1499,
        c309: false,
        c310: false,
        c406: n1543,
        c407: n1583,
    });
    out(16, &osh, &KOut {
        valid: valid1,
        deopt: !ok_v16,
        bd: bd_v16,
        c302: n1648,
        c309: false,
        c310: true,
        c406: n1653,
        c407: n1652,
    });
    out(32, &osh, &KOut {
        valid: valid1,
        deopt: !ok_v32,
        bd: bd_v32,
        c302: n1499,
        c309: true,
        c310: false,
        c406: n1543,
        c407: n1583,
    });
    out(48, &osh, &KOut {
        valid: valid1,
        deopt: !ok_v48,
        bd: bd_v48,
        c302: n1648,
        c309: true,
        c310: true,
        c406: n1653,
        c407: n1652,
    });
    }
    }
}
