// GENERATED by `transpile --kernel` (plans/kernel-plan.md). Do not edit.
//
// The STEADY-CLASS lane kernel: shape (player), pm1 freeze=0 dash_time=0.
// Shared prefix per 16-row slice, 64 monomorphized button suffixes.
#![allow(unused_variables, unused_mut, unused_imports, clippy::all)]
use celeste_engine::kernel::*;
use celeste_core::pico8_num::{Pico8Num as P8, Pico8NumInterval as IV};
use celeste_core::cart_data::CartData;
use celeste_core::collision_cache::CollisionCache;

pub const SHAPE_HASH: u64 = 0xa9e20c0af79aea86;
pub struct G<'a> { pub cart: &'a CartData, pub cache: &'a CollisionCache }

/// Block-uniform inputs, bound per block (kind-checked).
pub struct Uni {
    pub c20: P8,
    pub c38: bool,
    pub c39: P8,
    pub c41: bool,
    pub c42: bool,
    pub c43: bool,
    pub c44: P8,
    pub c45: P8,
    pub c46: P8,
    pub c47: P8,
    pub c48: P8,
    pub c49: P8,
    pub c84: P8,
    pub c85: P8,
    pub c86: P8,
    pub c87: P8,
    pub c88: P8,
    pub c159: P8,
    pub c161: P8,
    pub c162: P8,
    pub c174: P8,
    pub c177: P8,
    pub c180: P8,
    pub c182: bool,
    pub c184: P8,
    pub c186: bool,
    pub c188: P8,
    pub c190: bool,
    pub c191: P8,
    pub c193: bool,
    pub c194: P8,
    pub c196: bool,
    pub c198: P8,
    pub c204: P8,
    pub c238: bool,
    pub c246: (P8, P8),
    pub c248: bool,
    pub c250: P8,
    pub c251: P8,
    pub c253: P8,
    pub c254: (P8, P8),
    pub c257: bool,
    pub c259: P8,
    pub c260: P8,
    pub c268: bool,
    pub c270: P8,
    pub c272: P8,
    pub c273: P8,
    pub c276: bool,
    pub c278: P8,
    pub c279: P8,
    pub c287: bool,
    pub c289: P8,
    pub c291: P8,
    pub c292: P8,
    pub c295: bool,
    pub c299: P8,
    pub c300: P8,
    pub c309: bool,
    pub c310: bool,
    pub c312: bool,
    pub c364: bool,
    pub c365: bool,
    pub c366: P8,
    pub c367: P8,
    pub c368: P8,
    pub c369: P8,
    pub c370: P8,
    pub c371: P8,
    pub c372: P8,
    pub c373: P8,
    pub c374: bool,
    pub c375: bool,
    pub c376: P8,
    pub c377: P8,
    pub c378: P8,
    pub c379: P8,
    pub c380: P8,
    pub c381: P8,
    pub c382: P8,
    pub c383: P8,
    pub c384: bool,
    pub c385: bool,
    pub c386: P8,
    pub c387: P8,
    pub c388: P8,
    pub c389: P8,
    pub c390: P8,
    pub c391: P8,
    pub c392: P8,
    pub c393: P8,
    pub c399: bool,
    pub c400: P8,
    pub c401: P8,
    pub c402: P8,
    pub c403: P8,
    pub c404: (P8, P8),
    pub c405: (P8, P8),
}

pub const UNI_CELLS: &[(u32, &str)] = &[
    (20, "num"),
    (38, "bool"),
    (39, "num"),
    (41, "bool"),
    (42, "bool"),
    (43, "bool"),
    (44, "num"),
    (45, "num"),
    (46, "num"),
    (47, "num"),
    (48, "num"),
    (49, "num"),
    (84, "num"),
    (85, "num"),
    (86, "num"),
    (87, "num"),
    (88, "num"),
    (159, "num"),
    (161, "num"),
    (162, "num"),
    (174, "num"),
    (177, "num"),
    (180, "num"),
    (182, "bool"),
    (184, "num"),
    (186, "bool"),
    (188, "num"),
    (190, "bool"),
    (191, "num"),
    (193, "bool"),
    (194, "num"),
    (196, "bool"),
    (198, "num"),
    (204, "num"),
    (238, "bool"),
    (246, "ival"),
    (248, "bool"),
    (250, "num"),
    (251, "num"),
    (253, "num"),
    (254, "ival"),
    (257, "bool"),
    (259, "num"),
    (260, "num"),
    (268, "bool"),
    (270, "num"),
    (272, "num"),
    (273, "num"),
    (276, "bool"),
    (278, "num"),
    (279, "num"),
    (287, "bool"),
    (289, "num"),
    (291, "num"),
    (292, "num"),
    (295, "bool"),
    (299, "num"),
    (300, "num"),
    (309, "bool"),
    (310, "bool"),
    (312, "bool"),
    (364, "bool"),
    (365, "bool"),
    (366, "num"),
    (367, "num"),
    (368, "num"),
    (369, "num"),
    (370, "num"),
    (371, "num"),
    (372, "num"),
    (373, "num"),
    (374, "bool"),
    (375, "bool"),
    (376, "num"),
    (377, "num"),
    (378, "num"),
    (379, "num"),
    (380, "num"),
    (381, "num"),
    (382, "num"),
    (383, "num"),
    (384, "bool"),
    (385, "bool"),
    (386, "num"),
    (387, "num"),
    (388, "num"),
    (389, "num"),
    (390, "num"),
    (391, "num"),
    (392, "num"),
    (393, "num"),
    (399, "bool"),
    (400, "num"),
    (401, "num"),
    (402, "num"),
    (403, "num"),
    (404, "ival"),
    (405, "ival"),
];

/// Folds consumed these uniform cells' witness values; bind must
/// guard them (raw bits) or send the block to the interpreter.
pub const PIN_CELLS: &[(u32, i32)] = &[
    (44, 0i32),
    (45, 65536i32),
    (48, 262144i32),
    (49, 327680i32),
];

/// Per-lane inputs: 16 rows per slice.
pub struct RowsIn {
    pub c297: ZN,
    pub c302: ZN,
    pub c316: ZN,
    pub c317: ZN,
    pub c394: ZN,
    pub c395: ZN,
    pub c396: ZN,
    pub c397: ZN,
    pub c398: u16,
    pub c406: ZN,
    pub c407: ZN,
}

pub const VARY_CELLS: &[(u32, &str)] = &[
    (297, "num"),
    (302, "num"),
    (316, "num"),
    (317, "num"),
    (394, "num"),
    (395, "num"),
    (396, "num"),
    (397, "num"),
    (398, "bool"),
    (406, "num"),
    (407, "num"),
];

/// Button-independent outputs: one per fork config.
pub struct KOutShared {
    pub c38: bool,
    pub c39: P8,
    pub c84: P8,
    pub c87: P8,
    pub c246: (P8, P8),
    pub c254: (P8, P8),
    pub c297: ZN,
    pub c300: ZN,
    pub c302: ZN,
    pub c309: bool,
    pub c310: bool,
    pub c316: ZN,
    pub c317: ZN,
    pub c398: ZB,
    pub c404: ZI,
    pub c405: ZI,
    pub c406: ZN,
    pub c407: ZN,
}

/// Button-dependent outputs: one per (config, variant).
pub struct KOut {
    /// Lanes that EXIST in this fork configuration.
    pub valid: u16,
    pub deopt: u16,
    pub bd: bool,
}

pub const OUT_CELLS: &[u32] = &[
    38,
    39,
    84,
    87,
    246,
    254,
    297,
    300,
    302,
    309,
    310,
    316,
    317,
    398,
    404,
    405,
    406,
    407,
];

/// Cells that end every frame as a fresh UnknownBool (the next
/// frame's button inputs); the boundary writes UBool, no data.
pub const OUT_UBOOL_CELLS: &[u32] = &[
    145,
    146,
    147,
    148,
    149,
    150,
];

use celeste_engine::runtime2::{Rt2, Col, AV};

/// Bind the block-uniform inputs. None = off-shape / off-kind /
/// pin mismatch: the block takes the reference path.
pub fn bind(b: &Rt2) -> Option<Uni> {
    if b.shape_hash != SHAPE_HASH { return None; }
    for (cell, pin) in PIN_CELLS {
        match &b.cols[*cell as usize] {
            Col::U(AV::Num(n)) if n.as_raw_u32() as i32 == *pin => {}
            _ => return None,
        }
    }
    Some(Uni {
        c20: match &b.cols[20] { Col::U(AV::Num(n)) => *n, _ => return None },
        c38: match &b.cols[38] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c39: match &b.cols[39] { Col::U(AV::Num(n)) => *n, _ => return None },
        c41: match &b.cols[41] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c42: match &b.cols[42] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c43: match &b.cols[43] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c44: match &b.cols[44] { Col::U(AV::Num(n)) => *n, _ => return None },
        c45: match &b.cols[45] { Col::U(AV::Num(n)) => *n, _ => return None },
        c46: match &b.cols[46] { Col::U(AV::Num(n)) => *n, _ => return None },
        c47: match &b.cols[47] { Col::U(AV::Num(n)) => *n, _ => return None },
        c48: match &b.cols[48] { Col::U(AV::Num(n)) => *n, _ => return None },
        c49: match &b.cols[49] { Col::U(AV::Num(n)) => *n, _ => return None },
        c84: match &b.cols[84] { Col::U(AV::Num(n)) => *n, _ => return None },
        c85: match &b.cols[85] { Col::U(AV::Num(n)) => *n, _ => return None },
        c86: match &b.cols[86] { Col::U(AV::Num(n)) => *n, _ => return None },
        c87: match &b.cols[87] { Col::U(AV::Num(n)) => *n, _ => return None },
        c88: match &b.cols[88] { Col::U(AV::Num(n)) => *n, _ => return None },
        c159: match &b.cols[159] { Col::U(AV::Num(n)) => *n, _ => return None },
        c161: match &b.cols[161] { Col::U(AV::Num(n)) => *n, _ => return None },
        c162: match &b.cols[162] { Col::U(AV::Num(n)) => *n, _ => return None },
        c174: match &b.cols[174] { Col::U(AV::Num(n)) => *n, _ => return None },
        c177: match &b.cols[177] { Col::U(AV::Num(n)) => *n, _ => return None },
        c180: match &b.cols[180] { Col::U(AV::Num(n)) => *n, _ => return None },
        c182: match &b.cols[182] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c184: match &b.cols[184] { Col::U(AV::Num(n)) => *n, _ => return None },
        c186: match &b.cols[186] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c188: match &b.cols[188] { Col::U(AV::Num(n)) => *n, _ => return None },
        c190: match &b.cols[190] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c191: match &b.cols[191] { Col::U(AV::Num(n)) => *n, _ => return None },
        c193: match &b.cols[193] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c194: match &b.cols[194] { Col::U(AV::Num(n)) => *n, _ => return None },
        c196: match &b.cols[196] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c198: match &b.cols[198] { Col::U(AV::Num(n)) => *n, _ => return None },
        c204: match &b.cols[204] { Col::U(AV::Num(n)) => *n, _ => return None },
        c238: match &b.cols[238] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c246: match &b.cols[246] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c248: match &b.cols[248] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c250: match &b.cols[250] { Col::U(AV::Num(n)) => *n, _ => return None },
        c251: match &b.cols[251] { Col::U(AV::Num(n)) => *n, _ => return None },
        c253: match &b.cols[253] { Col::U(AV::Num(n)) => *n, _ => return None },
        c254: match &b.cols[254] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c257: match &b.cols[257] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c259: match &b.cols[259] { Col::U(AV::Num(n)) => *n, _ => return None },
        c260: match &b.cols[260] { Col::U(AV::Num(n)) => *n, _ => return None },
        c268: match &b.cols[268] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c270: match &b.cols[270] { Col::U(AV::Num(n)) => *n, _ => return None },
        c272: match &b.cols[272] { Col::U(AV::Num(n)) => *n, _ => return None },
        c273: match &b.cols[273] { Col::U(AV::Num(n)) => *n, _ => return None },
        c276: match &b.cols[276] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c278: match &b.cols[278] { Col::U(AV::Num(n)) => *n, _ => return None },
        c279: match &b.cols[279] { Col::U(AV::Num(n)) => *n, _ => return None },
        c287: match &b.cols[287] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c289: match &b.cols[289] { Col::U(AV::Num(n)) => *n, _ => return None },
        c291: match &b.cols[291] { Col::U(AV::Num(n)) => *n, _ => return None },
        c292: match &b.cols[292] { Col::U(AV::Num(n)) => *n, _ => return None },
        c295: match &b.cols[295] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c299: match &b.cols[299] { Col::U(AV::Num(n)) => *n, _ => return None },
        c300: match &b.cols[300] { Col::U(AV::Num(n)) => *n, _ => return None },
        c309: match &b.cols[309] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c310: match &b.cols[310] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c312: match &b.cols[312] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c364: match &b.cols[364] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c365: match &b.cols[365] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c366: match &b.cols[366] { Col::U(AV::Num(n)) => *n, _ => return None },
        c367: match &b.cols[367] { Col::U(AV::Num(n)) => *n, _ => return None },
        c368: match &b.cols[368] { Col::U(AV::Num(n)) => *n, _ => return None },
        c369: match &b.cols[369] { Col::U(AV::Num(n)) => *n, _ => return None },
        c370: match &b.cols[370] { Col::U(AV::Num(n)) => *n, _ => return None },
        c371: match &b.cols[371] { Col::U(AV::Num(n)) => *n, _ => return None },
        c372: match &b.cols[372] { Col::U(AV::Num(n)) => *n, _ => return None },
        c373: match &b.cols[373] { Col::U(AV::Num(n)) => *n, _ => return None },
        c374: match &b.cols[374] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c375: match &b.cols[375] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c376: match &b.cols[376] { Col::U(AV::Num(n)) => *n, _ => return None },
        c377: match &b.cols[377] { Col::U(AV::Num(n)) => *n, _ => return None },
        c378: match &b.cols[378] { Col::U(AV::Num(n)) => *n, _ => return None },
        c379: match &b.cols[379] { Col::U(AV::Num(n)) => *n, _ => return None },
        c380: match &b.cols[380] { Col::U(AV::Num(n)) => *n, _ => return None },
        c381: match &b.cols[381] { Col::U(AV::Num(n)) => *n, _ => return None },
        c382: match &b.cols[382] { Col::U(AV::Num(n)) => *n, _ => return None },
        c383: match &b.cols[383] { Col::U(AV::Num(n)) => *n, _ => return None },
        c384: match &b.cols[384] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c385: match &b.cols[385] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c386: match &b.cols[386] { Col::U(AV::Num(n)) => *n, _ => return None },
        c387: match &b.cols[387] { Col::U(AV::Num(n)) => *n, _ => return None },
        c388: match &b.cols[388] { Col::U(AV::Num(n)) => *n, _ => return None },
        c389: match &b.cols[389] { Col::U(AV::Num(n)) => *n, _ => return None },
        c390: match &b.cols[390] { Col::U(AV::Num(n)) => *n, _ => return None },
        c391: match &b.cols[391] { Col::U(AV::Num(n)) => *n, _ => return None },
        c392: match &b.cols[392] { Col::U(AV::Num(n)) => *n, _ => return None },
        c393: match &b.cols[393] { Col::U(AV::Num(n)) => *n, _ => return None },
        c399: match &b.cols[399] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c400: match &b.cols[400] { Col::U(AV::Num(n)) => *n, _ => return None },
        c401: match &b.cols[401] { Col::U(AV::Num(n)) => *n, _ => return None },
        c402: match &b.cols[402] { Col::U(AV::Num(n)) => *n, _ => return None },
        c403: match &b.cols[403] { Col::U(AV::Num(n)) => *n, _ => return None },
        c404: match &b.cols[404] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c405: match &b.cols[405] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
    })
}

/// Gather rows [lo, lo+16) into lane arrays; short slices pad by
/// repeating the last row (padded outputs are ignored by width).
pub fn rows(b: &Rt2, lo: usize) -> Option<RowsIn> {
    let at = |i: usize| -> usize { (lo + i).min(b.width - 1) };
    Some(RowsIn {
        c297: match &b.cols[297] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c302: match &b.cols[302] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c316: match &b.cols[316] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c317: match &b.cols[317] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c394: match &b.cols[394] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c395: match &b.cols[395] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c396: match &b.cols[396] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c397: match &b.cols[397] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c398: match &b.cols[398] {
            Col::V(v) => {
                let mut m = 0u16;
                for i in 0..W { if matches!(v[at(i)], AV::Bool(true)) { m |= 1 << i; } else if !matches!(v[at(i)], AV::Bool(false)) { return None; } }
                m
            }
            Col::U(AV::Bool(t)) => if *t { 0xffff } else { 0 },
            _ => return None,
        },
        c406: match &b.cols[406] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c407: match &b.cols[407] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
    })
}

/// Write one (config, variant) result onto a width-`n` sliced block
/// (the block already carries the input row values).
pub fn apply(sh: &KOutShared, kv: &KOut, b: &mut Rt2, n: usize) {
    b.cols[38] = Col::U(AV::Bool(sh.c38));
    b.cols[39] = Col::U(AV::Num(sh.c39));
    b.cols[84] = Col::U(AV::Num(sh.c84));
    b.cols[87] = Col::U(AV::Num(sh.c87));
    b.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
    b.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
    b.cols[297] = Col::N(sh.c297[..n].to_vec());
    b.cols[300] = Col::N(sh.c300[..n].to_vec());
    b.cols[302] = Col::N(sh.c302[..n].to_vec());
    b.cols[309] = Col::U(AV::Bool(sh.c309));
    b.cols[310] = Col::U(AV::Bool(sh.c310));
    b.cols[316] = Col::N(sh.c316[..n].to_vec());
    b.cols[317] = Col::N(sh.c317[..n].to_vec());
    b.cols[398] = Col::V((0..n).map(|i| AV::Bool(sh.c398.val & (1 << i) != 0)).collect());
    b.cols[404] = Col::I((0..n).map(|i| (sh.c404.lo[i], sh.c404.hi[i])).collect());
    b.cols[405] = Col::I((0..n).map(|i| (sh.c405.lo[i], sh.c405.hi[i])).collect());
    b.cols[406] = Col::N(sh.c406[..n].to_vec());
    b.cols[407] = Col::N(sh.c407[..n].to_vec());
    for cell in OUT_UBOOL_CELLS {
        b.cols[*cell as usize] = Col::U(AV::UBool);
    }
}

/// One wide output block per chunk: structure + uniforms cloned
/// once, varying/output columns start empty and grow by appends.
pub fn acc_init(chunk: &Rt2) -> Rt2 {
    let mut acc = Rt2::empty(0, chunk.globals.len(), &[], chunk.cart.clone(), chunk.cache.clone());
    acc.strings = chunk.strings.clone();
    acc.globals = chunk.globals.clone();
    acc.structure = chunk.structure.clone();
    acc.cols = chunk.cols.clone();
    acc.shape_hash = chunk.shape_hash;
    acc.cols[297] = Col::N(Vec::new());
    acc.cols[300] = Col::N(Vec::new());
    acc.cols[302] = Col::N(Vec::new());
    acc.cols[316] = Col::N(Vec::new());
    acc.cols[317] = Col::N(Vec::new());
    acc.cols[398] = Col::V(Vec::new());
    acc.cols[404] = Col::I(Vec::new());
    acc.cols[405] = Col::I(Vec::new());
    acc.cols[406] = Col::N(Vec::new());
    acc.cols[407] = Col::N(Vec::new());
    acc.cols[394] = Col::N(Vec::new());
    acc.cols[395] = Col::N(Vec::new());
    acc.cols[396] = Col::N(Vec::new());
    acc.cols[397] = Col::N(Vec::new());
    for cell in OUT_UBOOL_CELLS {
        acc.cols[*cell as usize] = Col::U(AV::UBool);
    }
    acc
}

/// Append one (config, variant)'s live lanes onto the accumulator.
/// `lo` is the slice base in `chunk` (identity columns read there).
#[allow(unused_variables)]
pub fn append_out(acc: &mut Rt2, chunk: &Rt2, lo: usize, n: usize, live: u16, sh: &KOutShared, kv: &KOut, bd: &mut bool) {
    // fresh: no fork config has written yet, so a uniform slot
    // still holds the chunk's INPUT value (legitimately different).
    let fresh = acc.width == 0;
    for i in 0..n {
        if live & (1 << i) == 0 { continue; }
        if !fresh { if let Col::U(AV::Bool(prev)) = &acc.cols[38] { if *prev != sh.c38 { *bd = true; } } }
        acc.cols[38] = Col::U(AV::Bool(sh.c38));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[39] { if *prev != sh.c39 { *bd = true; } } }
        acc.cols[39] = Col::U(AV::Num(sh.c39));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[84] { if *prev != sh.c84 { *bd = true; } } }
        acc.cols[84] = Col::U(AV::Num(sh.c84));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[87] { if *prev != sh.c87 { *bd = true; } } }
        acc.cols[87] = Col::U(AV::Num(sh.c87));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[246] { if (*a, *b) != sh.c246 { *bd = true; } } }
        acc.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[254] { if (*a, *b) != sh.c254 { *bd = true; } } }
        acc.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
        if let Col::N(v) = &mut acc.cols[297] { v.push(sh.c297[i]); }
        if let Col::N(v) = &mut acc.cols[300] { v.push(sh.c300[i]); }
        if let Col::N(v) = &mut acc.cols[302] { v.push(sh.c302[i]); }
        if !fresh { if let Col::U(AV::Bool(prev)) = &acc.cols[309] { if *prev != sh.c309 { *bd = true; } } }
        acc.cols[309] = Col::U(AV::Bool(sh.c309));
        if !fresh { if let Col::U(AV::Bool(prev)) = &acc.cols[310] { if *prev != sh.c310 { *bd = true; } } }
        acc.cols[310] = Col::U(AV::Bool(sh.c310));
        if let Col::N(v) = &mut acc.cols[316] { v.push(sh.c316[i]); }
        if let Col::N(v) = &mut acc.cols[317] { v.push(sh.c317[i]); }
        if let Col::V(v) = &mut acc.cols[398] { v.push(AV::Bool(sh.c398.val & (1 << i) != 0)); }
        if let Col::I(v) = &mut acc.cols[404] { v.push((sh.c404.lo[i], sh.c404.hi[i])); }
        if let Col::I(v) = &mut acc.cols[405] { v.push((sh.c405.lo[i], sh.c405.hi[i])); }
        if let Col::N(v) = &mut acc.cols[406] { v.push(sh.c406[i]); }
        if let Col::N(v) = &mut acc.cols[407] { v.push(sh.c407[i]); }
        let val = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[394] { v.push(val); }
        let val = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[395] { v.push(val); }
        let val = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[396] { v.push(val); }
        let val = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[397] { v.push(val); }
        acc.width += 1;
    }
}

/// Cells the pre-dedup key covers, in key-bit order.
pub const KEY_CELLS: &[u32] = &[
    38,
    39,
    84,
    87,
    246,
    254,
    297,
    300,
    302,
    309,
    310,
    316,
    317,
    398,
    404,
    405,
    406,
    407,
    394,
    395,
    396,
    397,
];

#[allow(unused_variables)]
pub fn row_keys(chunk: &Rt2, lo: usize, n: usize, sh: &KOutShared, kv: &KOut, plan: &KeyPlan, keys: &mut [(u64, u64); W]) {
    let mut h1 = [0u64; W];
    let mut h2 = [0u64; W];
    // cell 38 (bool)
    if plan.rem & (1 << 0) == 0 {
        assert!(plan.det & (1 << 0) == 0, "det clamp on non-numeric cell 38");
        for i in 0..W {
            let v = AV::Bool(sh.c38);
            h1[i] = h1[i].wrapping_add(cell_mix(38u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(38u64, v, 0x27d4_eb2f));
        }
    }
    // cell 39 (P8)
    if plan.rem & (1 << 1) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (39u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (39u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c39;
            let v = if plan.det & (1 << 1) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 84 (P8)
    if plan.rem & (1 << 2) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c84;
            let v = if plan.det & (1 << 2) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 87 (P8)
    if plan.rem & (1 << 3) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (87u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (87u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c87;
            let v = if plan.det & (1 << 3) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 246 ((P8, P8))
    if plan.rem & (1 << 4) == 0 {
        assert!(plan.det & (1 << 4) == 0, "det clamp on non-numeric cell 246");
        for i in 0..W {
            let v = AV::Ival(sh.c246.0, sh.c246.1);
            h1[i] = h1[i].wrapping_add(cell_mix(246u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(246u64, v, 0x27d4_eb2f));
        }
    }
    // cell 254 ((P8, P8))
    if plan.rem & (1 << 5) == 0 {
        assert!(plan.det & (1 << 5) == 0, "det clamp on non-numeric cell 254");
        for i in 0..W {
            let v = AV::Ival(sh.c254.0, sh.c254.1);
            h1[i] = h1[i].wrapping_add(cell_mix(254u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(254u64, v, 0x27d4_eb2f));
        }
    }
    // cell 297 (ZN)
    if plan.rem & (1 << 6) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c297[i];
            let v = if plan.det & (1 << 6) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 300 (ZN)
    if plan.rem & (1 << 7) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c300[i];
            let v = if plan.det & (1 << 7) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 302 (ZN)
    if plan.rem & (1 << 8) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c302[i];
            let v = if plan.det & (1 << 8) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 309 (bool)
    if plan.rem & (1 << 9) == 0 {
        assert!(plan.det & (1 << 9) == 0, "det clamp on non-numeric cell 309");
        for i in 0..W {
            let v = AV::Bool(sh.c309);
            h1[i] = h1[i].wrapping_add(cell_mix(309u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(309u64, v, 0x27d4_eb2f));
        }
    }
    // cell 310 (bool)
    if plan.rem & (1 << 10) == 0 {
        assert!(plan.det & (1 << 10) == 0, "det clamp on non-numeric cell 310");
        for i in 0..W {
            let v = AV::Bool(sh.c310);
            h1[i] = h1[i].wrapping_add(cell_mix(310u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(310u64, v, 0x27d4_eb2f));
        }
    }
    // cell 316 (ZN)
    if plan.rem & (1 << 11) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c316[i];
            let v = if plan.det & (1 << 11) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 317 (ZN)
    if plan.rem & (1 << 12) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c317[i];
            let v = if plan.det & (1 << 12) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 398 (ZB)
    if plan.rem & (1 << 13) == 0 {
        assert!(plan.det & (1 << 13) == 0, "det clamp on non-numeric cell 398");
        for i in 0..W {
            let v = AV::Bool(sh.c398.val & (1 << i) != 0);
            h1[i] = h1[i].wrapping_add(cell_mix(398u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(398u64, v, 0x27d4_eb2f));
        }
    }
    // cell 404 (ZI)
    if plan.rem & (1 << 14) == 0 {
        assert!(plan.det & (1 << 14) == 0, "det clamp on non-numeric cell 404");
        for i in 0..W {
            let v = AV::Ival(sh.c404.lo[i], sh.c404.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(404u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(404u64, v, 0x27d4_eb2f));
        }
    }
    // cell 405 (ZI)
    if plan.rem & (1 << 15) == 0 {
        assert!(plan.det & (1 << 15) == 0, "det clamp on non-numeric cell 405");
        for i in 0..W {
            let v = AV::Ival(sh.c405.lo[i], sh.c405.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(405u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(405u64, v, 0x27d4_eb2f));
        }
    }
    // cell 406 (ZN)
    if plan.rem & (1 << 16) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c406[i];
            let v = if plan.det & (1 << 16) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 407 (ZN)
    if plan.rem & (1 << 17) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c407[i];
            let v = if plan.det & (1 << 17) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 394 (IN_N)
    if plan.rem & (1 << 18) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 18) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 395 (IN_N)
    if plan.rem & (1 << 19) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 19) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 396 (IN_N)
    if plan.rem & (1 << 20) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 20) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 397 (IN_N)
    if plan.rem & (1 << 21) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 21) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    for i in 0..W {
        keys[i] = (mix64(h1[i]), mix64(h2[i]));
    }
}

pub struct Pre {
    bd_pre: bool,
    ok_pre: u16,
    valid: u16,
}

#[inline(never)]
pub fn frame(u: &Uni, rin: &RowsIn, g: &G, out: &mut impl FnMut(u8, &KOutShared, &KOut)) {
    let r_c297: ZN = rin.c297;
    let r_c302: ZN = rin.c302;
    let r_c316: ZN = rin.c316;
    let r_c317: ZN = rin.c317;
    let r_c394: ZN = rin.c394;
    let r_c395: ZN = rin.c395;
    let r_c396: ZN = rin.c396;
    let r_c397: ZN = rin.c397;
    let r_c398: ZB = ZB { val: rin.c398, known: ALL };
    let r_c406: ZN = rin.c406;
    let r_c407: ZN = rin.c407;
    let n9: P8 = u.c84 + P8::from_raw(65536i32);
    let n11: P8 = n9 % P8::from_raw(1966080i32);
    let n82: ZN = zn_add(r_c316, zn_splat(u.c402));
    let n90: ZN = zn_add(r_c317, zn_splat(u.c403));
    let n110: (P8, P8) = si_add(u.c246, (P8::from_raw(65536i32), P8::from_raw(65536i32)));
    let n119: (P8, P8) = { let r = IV::new((P8::from_raw(-65536i32), P8::from_raw(65536i32)).0, (P8::from_raw(-65536i32), P8::from_raw(65536i32)).1).scale_positive(P8::from_raw(163840i32)); (r.low, r.high) };
    let n121: (P8, P8) = si_add((u.c251, u.c251), n119);
    let n246: ZI = zi_add(zi_splat(u.c404.0, u.c404.1), zi_of_zn(r_c406));
    let n248: ZI = zi_add(n246, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n279: ZN = zn_add(n90, zn_splat(P8::from_raw(0i32)));
    let n674: ZI = zi_add(zi_splat(u.c405.0, u.c405.1), zi_of_zn(r_c407));
    let n675: ZI = zi_add(n674, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n1464: P8 = u.c87 + P8::from_raw(65536i32);
    let n1498: bool = u.c300 < u.c88;
    let n1499: P8 = if n1498 { u.c88 } else { u.c300 };
    let n1501: ZB = zn_gt(r_c302, zn_splat(P8::from_raw(0i32)));
    let n1502: ZN = zn_sub(r_c302, zn_splat(P8::from_raw(65536i32)));
    let n1503: ZN = zsel_n(n1501, n1502, r_c302);
    let n1509: ZN = zn_sub(r_c297, zn_splat(P8::from_raw(65536i32)));
    let bd0: bool = false || true;
    for c0 in 0..2usize {
    let (f0, f0_fv): (ZI, u16) = zi_fork_flr(n248, c0);
    let valid0: u16 = ALL & f0_fv;
    if valid0 == 0 { continue; }
    let n253: ZN = zi_flr(f0);
    let n256: ZI = zi_sub(f0, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n257: ZI = zi_sub(n256, zi_of_zn(n253));
    let n260: ZB = zn_gt(n253, zn_splat(P8::from_raw(0i32)));
    let n261: ZB = zn_lt(n253, zn_splat(P8::from_raw(0i32)));
    let n262: ZB = zsel_b(n260, n260, n261);
    let n266: ZN = zsel_n(n260, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)));
    let n268: ZN = zsel_n(n262, n266, zn_splat(P8::from_raw(0i32)));
    let n271: ZN = zn_abs(n253);
    let n277: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n271);
    let n278: ZN = zn_add(n82, n268);
    let n280: ZB = zn_tile_flag_at(g.cache, g.cart, n278, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n300: ZB = zsel_b(n280, n280, zb_splat(false));
    let n303: ZB = zsel_b(n300, n300, zb_splat(false));
    let n306: ZB = zb_not(n303);
    let n307: ZB = zsel_b(n277, n306, n277);
    let n310: ZB = zb_not(n306);
    let n311: ZB = zsel_b(n277, n310, n277);
    let n313: ZN = zn_add(r_c316, n268);
    let n314: ZN = zsel_n(n307, n313, r_c316);
    let n317: ZN = zsel_n(n311, zn_splat(P8::from_raw(0i32)), r_c406);
    let n320: ZI = zsel_i(n311, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n257);
    let n322: ZN = zsel_n(n307, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n324: ZB = zsel_b(n311, zb_splat(false), zb_splat(true));
    let n326: ZB = zn_le(n322, n271);
    let n327: ZN = zn_add(n314, zn_splat(u.c402));
    let n328: ZN = zn_add(n327, n268);
    let n329: ZB = zn_tile_flag_at(g.cache, g.cart, n328, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n340: ZB = zsel_b(n329, n329, zb_splat(false));
    let n343: ZB = zsel_b(n340, n340, zb_splat(false));
    let n346: ZB = zb_not(n343);
    let n347: ZB = zsel_b(n324, n326, n324);
    let n350: ZB = zsel_b(n347, n346, n347);
    let n353: ZB = zb_not(n346);
    let n354: ZB = zsel_b(n347, n353, n347);
    let n356: ZN = zn_add(n314, n268);
    let n357: ZN = zsel_n(n350, n356, n314);
    let n360: ZN = zn_add(n322, zn_splat(P8::from_raw(65536i32)));
    let n361: ZN = zsel_n(n354, zn_splat(P8::from_raw(0i32)), n317);
    let n364: ZI = zsel_i(n354, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n320);
    let n366: ZN = zsel_n(n350, n360, n322);
    let n368: ZB = zsel_b(n354, zb_splat(false), n324);
    let n370: ZB = zn_le(n366, n271);
    let n371: ZN = zn_add(n357, zn_splat(u.c402));
    let n372: ZN = zn_add(n371, n268);
    let n373: ZB = zn_tile_flag_at(g.cache, g.cart, n372, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n384: ZB = zsel_b(n373, n373, zb_splat(false));
    let n387: ZB = zsel_b(n384, n384, zb_splat(false));
    let n390: ZB = zb_not(n387);
    let n391: ZB = zsel_b(n368, n370, n368);
    let n394: ZB = zsel_b(n391, n390, n391);
    let n397: ZB = zb_not(n390);
    let n398: ZB = zsel_b(n391, n397, n391);
    let n400: ZN = zn_add(n357, n268);
    let n401: ZN = zsel_n(n394, n400, n357);
    let n404: ZN = zn_add(n366, zn_splat(P8::from_raw(65536i32)));
    let n405: ZN = zsel_n(n398, zn_splat(P8::from_raw(0i32)), n361);
    let n408: ZI = zsel_i(n398, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n364);
    let n410: ZN = zsel_n(n394, n404, n366);
    let n412: ZB = zsel_b(n398, zb_splat(false), n368);
    let n414: ZB = zn_le(n410, n271);
    let n415: ZN = zn_add(n401, zn_splat(u.c402));
    let n416: ZN = zn_add(n415, n268);
    let n417: ZB = zn_tile_flag_at(g.cache, g.cart, n416, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n428: ZB = zsel_b(n417, n417, zb_splat(false));
    let n431: ZB = zsel_b(n428, n428, zb_splat(false));
    let n434: ZB = zb_not(n431);
    let n435: ZB = zsel_b(n412, n414, n412);
    let n438: ZB = zsel_b(n435, n434, n435);
    let n441: ZB = zb_not(n434);
    let n442: ZB = zsel_b(n435, n441, n435);
    let n444: ZN = zn_add(n401, n268);
    let n445: ZN = zsel_n(n438, n444, n401);
    let n448: ZN = zn_add(n410, zn_splat(P8::from_raw(65536i32)));
    let n449: ZN = zsel_n(n442, zn_splat(P8::from_raw(0i32)), n405);
    let n452: ZI = zsel_i(n442, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n408);
    let n454: ZN = zsel_n(n438, n448, n410);
    let n456: ZB = zsel_b(n442, zb_splat(false), n412);
    let n458: ZB = zn_le(n454, n271);
    let n459: ZN = zn_add(n445, zn_splat(u.c402));
    let n460: ZN = zn_add(n459, n268);
    let n461: ZB = zn_tile_flag_at(g.cache, g.cart, n460, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n472: ZB = zsel_b(n461, n461, zb_splat(false));
    let n475: ZB = zsel_b(n472, n472, zb_splat(false));
    let n478: ZB = zb_not(n475);
    let n479: ZB = zsel_b(n456, n458, n456);
    let n482: ZB = zsel_b(n479, n478, n479);
    let n485: ZB = zb_not(n478);
    let n486: ZB = zsel_b(n479, n485, n479);
    let n488: ZN = zn_add(n445, n268);
    let n489: ZN = zsel_n(n482, n488, n445);
    let n492: ZN = zn_add(n454, zn_splat(P8::from_raw(65536i32)));
    let n493: ZN = zsel_n(n486, zn_splat(P8::from_raw(0i32)), n449);
    let n496: ZI = zsel_i(n486, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n452);
    let n498: ZN = zsel_n(n482, n492, n454);
    let n500: ZB = zsel_b(n486, zb_splat(false), n456);
    let n502: ZB = zn_le(n498, n271);
    let n503: ZN = zn_add(n489, zn_splat(u.c402));
    let n504: ZN = zn_add(n503, n268);
    let n505: ZB = zn_tile_flag_at(g.cache, g.cart, n504, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n516: ZB = zsel_b(n505, n505, zb_splat(false));
    let n519: ZB = zsel_b(n516, n516, zb_splat(false));
    let n522: ZB = zb_not(n519);
    let n523: ZB = zsel_b(n500, n502, n500);
    let n526: ZB = zsel_b(n523, n522, n523);
    let n529: ZB = zb_not(n522);
    let n530: ZB = zsel_b(n523, n529, n523);
    let n532: ZN = zn_add(n489, n268);
    let n533: ZN = zsel_n(n526, n532, n489);
    let n536: ZN = zn_add(n498, zn_splat(P8::from_raw(65536i32)));
    let n537: ZN = zsel_n(n530, zn_splat(P8::from_raw(0i32)), n493);
    let n540: ZI = zsel_i(n530, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n496);
    let n542: ZN = zsel_n(n526, n536, n498);
    let n544: ZB = zsel_b(n530, zb_splat(false), n500);
    let n546: ZB = zn_le(n542, n271);
    let n547: ZN = zn_add(n533, zn_splat(u.c402));
    let n548: ZN = zn_add(n547, n268);
    let n549: ZB = zn_tile_flag_at(g.cache, g.cart, n548, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n560: ZB = zsel_b(n549, n549, zb_splat(false));
    let n563: ZB = zsel_b(n560, n560, zb_splat(false));
    let n566: ZB = zb_not(n563);
    let n567: ZB = zsel_b(n544, n546, n544);
    let n570: ZB = zsel_b(n567, n566, n567);
    let n573: ZB = zb_not(n566);
    let n574: ZB = zsel_b(n567, n573, n567);
    let n576: ZN = zn_add(n533, n268);
    let n577: ZN = zsel_n(n570, n576, n533);
    let n580: ZN = zn_add(n542, zn_splat(P8::from_raw(65536i32)));
    let n581: ZN = zsel_n(n574, zn_splat(P8::from_raw(0i32)), n537);
    let n584: ZI = zsel_i(n574, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n540);
    let n586: ZN = zsel_n(n570, n580, n542);
    let n588: ZB = zsel_b(n574, zb_splat(false), n544);
    let n590: ZB = zn_le(n586, n271);
    let n591: ZN = zn_add(n577, zn_splat(u.c402));
    let n592: ZN = zn_add(n591, n268);
    let n593: ZB = zn_tile_flag_at(g.cache, g.cart, n592, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n604: ZB = zsel_b(n593, n593, zb_splat(false));
    let n607: ZB = zsel_b(n604, n604, zb_splat(false));
    let n610: ZB = zb_not(n607);
    let n611: ZB = zsel_b(n588, n590, n588);
    let n614: ZB = zsel_b(n611, n610, n611);
    let n617: ZB = zb_not(n610);
    let n618: ZB = zsel_b(n611, n617, n611);
    let n620: ZN = zn_add(n577, n268);
    let n621: ZN = zsel_n(n614, n620, n577);
    let n624: ZN = zn_add(n586, zn_splat(P8::from_raw(65536i32)));
    let n625: ZN = zsel_n(n618, zn_splat(P8::from_raw(0i32)), n581);
    let n628: ZI = zsel_i(n618, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n584);
    let n630: ZN = zsel_n(n614, n624, n586);
    let n632: ZB = zsel_b(n618, zb_splat(false), n588);
    let n634: ZB = zn_le(n630, n271);
    let n635: ZN = zn_add(n621, zn_splat(u.c402));
    let n636: ZN = zn_add(n635, n268);
    let n637: ZB = zn_tile_flag_at(g.cache, g.cart, n636, n279, u.c401, u.c400, P8::from_raw(0i32));
    let n648: ZB = zsel_b(n637, n637, zb_splat(false));
    let n651: ZB = zsel_b(n648, n648, zb_splat(false));
    let n654: ZB = zb_not(n651);
    let n655: ZB = zsel_b(n632, n634, n632);
    let n658: ZB = zsel_b(n655, n654, n655);
    let n661: ZB = zb_not(n654);
    let n662: ZB = zsel_b(n655, n661, n655);
    let n664: ZN = zn_add(n621, n268);
    let n665: ZN = zsel_n(n658, n664, n621);
    let n668: ZN = zsel_n(n662, zn_splat(P8::from_raw(0i32)), n625);
    let n671: ZI = zsel_i(n662, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n628);
    let n703: ZN = zn_add(n665, zn_splat(u.c402));
    let n704: ZN = zn_add(n703, zn_splat(P8::from_raw(0i32)));
    let n1521: ZN = zn_abs(n668);
    let n1522: ZB = zn_gt(n1521, zn_splat(P8::from_raw(65536i32)));
    let n1523: ZB = zn_gt(n668, zn_splat(P8::from_raw(0i32)));
    let n1524: ZB = zsel_b(n1523, zb_splat(true), n1523);
    let n1526: ZN = zsel_n(n1523, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n1527: ZB = zn_lt(n668, zn_splat(P8::from_raw(0i32)));
    let n1528: ZB = zsel_b(n1524, n1524, n1527);
    let n1530: ZN = zsel_n(n1524, n1526, zn_splat(P8::from_raw(-65536i32)));
    let n1531: ZN = zsel_n(n1528, n1530, zn_splat(P8::from_raw(0i32)));
    let n1533: ZN = zn_mul(n1531, zn_splat(P8::from_raw(65536i32)));
    let n1534: ZB = zn_gt(n668, n1533);
    let n1536: ZN = zn_sub(n668, zn_splat(P8::from_raw(9830i32)));
    let n1537: ZN = zn_max(n1536, n1533);
    let n1538: ZN = zn_add(n668, zn_splat(P8::from_raw(9830i32)));
    let n1539: ZN = zn_min(n1538, n1533);
    let n1540: ZN = zsel_n(n1534, n1537, n1539);
    for c1 in 0..2usize {
    let (f1, f1_fv): (ZI, u16) = zi_fork_flr(n675, c1);
    let valid1: u16 = valid0 & f1_fv;
    if valid1 == 0 { continue; }
    let n681: ZN = zi_flr(f1);
    let n684: ZI = zi_sub(f1, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n685: ZI = zi_sub(n684, zi_of_zn(n681));
    let n686: ZB = zn_gt(n681, zn_splat(P8::from_raw(0i32)));
    let n687: ZB = zn_lt(n681, zn_splat(P8::from_raw(0i32)));
    let n688: ZB = zsel_b(n686, n686, n687);
    let n691: ZN = zsel_n(n686, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)));
    let n693: ZN = zsel_n(n688, n691, zn_splat(P8::from_raw(0i32)));
    let n696: ZN = zn_abs(n681);
    let n701: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n696);
    let n702: ZB = zn_gt(n693, zn_splat(P8::from_raw(0i32)));
    let n715: ZB = zsel_b(n702, zb_splat(true), n702);
    let n718: ZN = zn_add(n90, n693);
    let n728: ZB = zsel_b(n715, zb_splat(false), n715);
    let n731: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n718, u.c401, u.c400, P8::from_raw(0i32));
    let n732: ZB = zsel_b(n731, n731, zb_splat(false));
    let n735: ZB = zsel_b(n732, n732, zb_splat(false));
    let n738: ZB = zsel_b(n728, zb_splat(true), n735);
    let n741: ZB = zb_not(n738);
    let n742: ZB = zsel_b(n701, n741, n701);
    let n745: ZB = zb_not(n741);
    let n746: ZB = zsel_b(n701, n745, n701);
    let n748: ZN = zn_add(r_c317, n693);
    let n749: ZN = zsel_n(n742, n748, r_c317);
    let n752: ZN = zsel_n(n746, zn_splat(P8::from_raw(0i32)), r_c407);
    let n755: ZI = zsel_i(n746, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n685);
    let n757: ZN = zsel_n(n742, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n759: ZB = zsel_b(n746, zb_splat(false), zb_splat(true));
    let n761: ZB = zn_le(n757, n696);
    let n762: ZN = zn_add(n749, zn_splat(u.c403));
    let n774: ZN = zn_add(n762, n693);
    let n784: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n774, u.c401, u.c400, P8::from_raw(0i32));
    let n785: ZB = zsel_b(n784, n784, zb_splat(false));
    let n788: ZB = zsel_b(n785, n785, zb_splat(false));
    let n791: ZB = zsel_b(n728, zb_splat(true), n788);
    let n793: ZB = zb_not(n791);
    let n794: ZB = zsel_b(n759, n761, n759);
    let n797: ZB = zsel_b(n794, n793, n794);
    let n800: ZB = zb_not(n793);
    let n801: ZB = zsel_b(n794, n800, n794);
    let n803: ZN = zn_add(n749, n693);
    let n804: ZN = zsel_n(n797, n803, n749);
    let n807: ZN = zn_add(n757, zn_splat(P8::from_raw(65536i32)));
    let n808: ZN = zsel_n(n801, zn_splat(P8::from_raw(0i32)), n752);
    let n811: ZI = zsel_i(n801, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n755);
    let n813: ZN = zsel_n(n797, n807, n757);
    let n815: ZB = zsel_b(n801, zb_splat(false), n759);
    let n817: ZB = zn_le(n813, n696);
    let n818: ZN = zn_add(n804, zn_splat(u.c403));
    let n830: ZN = zn_add(n818, n693);
    let n840: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n830, u.c401, u.c400, P8::from_raw(0i32));
    let n841: ZB = zsel_b(n840, n840, zb_splat(false));
    let n844: ZB = zsel_b(n841, n841, zb_splat(false));
    let n847: ZB = zsel_b(n728, zb_splat(true), n844);
    let n849: ZB = zb_not(n847);
    let n850: ZB = zsel_b(n815, n817, n815);
    let n853: ZB = zsel_b(n850, n849, n850);
    let n856: ZB = zb_not(n849);
    let n857: ZB = zsel_b(n850, n856, n850);
    let n859: ZN = zn_add(n804, n693);
    let n860: ZN = zsel_n(n853, n859, n804);
    let n863: ZN = zn_add(n813, zn_splat(P8::from_raw(65536i32)));
    let n864: ZN = zsel_n(n857, zn_splat(P8::from_raw(0i32)), n808);
    let n867: ZI = zsel_i(n857, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n811);
    let n869: ZN = zsel_n(n853, n863, n813);
    let n871: ZB = zsel_b(n857, zb_splat(false), n815);
    let n873: ZB = zn_le(n869, n696);
    let n874: ZN = zn_add(n860, zn_splat(u.c403));
    let n886: ZN = zn_add(n874, n693);
    let n896: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n886, u.c401, u.c400, P8::from_raw(0i32));
    let n897: ZB = zsel_b(n896, n896, zb_splat(false));
    let n900: ZB = zsel_b(n897, n897, zb_splat(false));
    let n903: ZB = zsel_b(n728, zb_splat(true), n900);
    let n905: ZB = zb_not(n903);
    let n906: ZB = zsel_b(n871, n873, n871);
    let n909: ZB = zsel_b(n906, n905, n906);
    let n912: ZB = zb_not(n905);
    let n913: ZB = zsel_b(n906, n912, n906);
    let n915: ZN = zn_add(n860, n693);
    let n916: ZN = zsel_n(n909, n915, n860);
    let n919: ZN = zn_add(n869, zn_splat(P8::from_raw(65536i32)));
    let n920: ZN = zsel_n(n913, zn_splat(P8::from_raw(0i32)), n864);
    let n923: ZI = zsel_i(n913, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n867);
    let n925: ZN = zsel_n(n909, n919, n869);
    let n927: ZB = zsel_b(n913, zb_splat(false), n871);
    let n929: ZB = zn_le(n925, n696);
    let n930: ZN = zn_add(n916, zn_splat(u.c403));
    let n942: ZN = zn_add(n930, n693);
    let n952: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n942, u.c401, u.c400, P8::from_raw(0i32));
    let n953: ZB = zsel_b(n952, n952, zb_splat(false));
    let n956: ZB = zsel_b(n953, n953, zb_splat(false));
    let n959: ZB = zsel_b(n728, zb_splat(true), n956);
    let n961: ZB = zb_not(n959);
    let n962: ZB = zsel_b(n927, n929, n927);
    let n965: ZB = zsel_b(n962, n961, n962);
    let n968: ZB = zb_not(n961);
    let n969: ZB = zsel_b(n962, n968, n962);
    let n971: ZN = zn_add(n916, n693);
    let n972: ZN = zsel_n(n965, n971, n916);
    let n975: ZN = zn_add(n925, zn_splat(P8::from_raw(65536i32)));
    let n976: ZN = zsel_n(n969, zn_splat(P8::from_raw(0i32)), n920);
    let n979: ZI = zsel_i(n969, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n923);
    let n981: ZN = zsel_n(n965, n975, n925);
    let n983: ZB = zsel_b(n969, zb_splat(false), n927);
    let n985: ZB = zn_le(n981, n696);
    let n986: ZN = zn_add(n972, zn_splat(u.c403));
    let n998: ZN = zn_add(n986, n693);
    let n1008: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n998, u.c401, u.c400, P8::from_raw(0i32));
    let n1009: ZB = zsel_b(n1008, n1008, zb_splat(false));
    let n1012: ZB = zsel_b(n1009, n1009, zb_splat(false));
    let n1015: ZB = zsel_b(n728, zb_splat(true), n1012);
    let n1017: ZB = zb_not(n1015);
    let n1018: ZB = zsel_b(n983, n985, n983);
    let n1021: ZB = zsel_b(n1018, n1017, n1018);
    let n1024: ZB = zb_not(n1017);
    let n1025: ZB = zsel_b(n1018, n1024, n1018);
    let n1027: ZN = zn_add(n972, n693);
    let n1028: ZN = zsel_n(n1021, n1027, n972);
    let n1031: ZN = zn_add(n981, zn_splat(P8::from_raw(65536i32)));
    let n1032: ZN = zsel_n(n1025, zn_splat(P8::from_raw(0i32)), n976);
    let n1035: ZI = zsel_i(n1025, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n979);
    let n1037: ZN = zsel_n(n1021, n1031, n981);
    let n1039: ZB = zsel_b(n1025, zb_splat(false), n983);
    let n1041: ZB = zn_le(n1037, n696);
    let n1042: ZN = zn_add(n1028, zn_splat(u.c403));
    let n1054: ZN = zn_add(n1042, n693);
    let n1064: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n1054, u.c401, u.c400, P8::from_raw(0i32));
    let n1065: ZB = zsel_b(n1064, n1064, zb_splat(false));
    let n1068: ZB = zsel_b(n1065, n1065, zb_splat(false));
    let n1071: ZB = zsel_b(n728, zb_splat(true), n1068);
    let n1073: ZB = zb_not(n1071);
    let n1074: ZB = zsel_b(n1039, n1041, n1039);
    let n1077: ZB = zsel_b(n1074, n1073, n1074);
    let n1080: ZB = zb_not(n1073);
    let n1081: ZB = zsel_b(n1074, n1080, n1074);
    let n1083: ZN = zn_add(n1028, n693);
    let n1084: ZN = zsel_n(n1077, n1083, n1028);
    let n1087: ZN = zn_add(n1037, zn_splat(P8::from_raw(65536i32)));
    let n1088: ZN = zsel_n(n1081, zn_splat(P8::from_raw(0i32)), n1032);
    let n1091: ZI = zsel_i(n1081, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1035);
    let n1093: ZN = zsel_n(n1077, n1087, n1037);
    let n1095: ZB = zsel_b(n1081, zb_splat(false), n1039);
    let n1097: ZB = zn_le(n1093, n696);
    let n1098: ZN = zn_add(n1084, zn_splat(u.c403));
    let n1110: ZN = zn_add(n1098, n693);
    let n1120: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n1110, u.c401, u.c400, P8::from_raw(0i32));
    let n1121: ZB = zsel_b(n1120, n1120, zb_splat(false));
    let n1124: ZB = zsel_b(n1121, n1121, zb_splat(false));
    let n1127: ZB = zsel_b(n728, zb_splat(true), n1124);
    let n1129: ZB = zb_not(n1127);
    let n1130: ZB = zsel_b(n1095, n1097, n1095);
    let n1133: ZB = zsel_b(n1130, n1129, n1130);
    let n1136: ZB = zb_not(n1129);
    let n1137: ZB = zsel_b(n1130, n1136, n1130);
    let n1139: ZN = zn_add(n1084, n693);
    let n1140: ZN = zsel_n(n1133, n1139, n1084);
    let n1143: ZN = zn_add(n1093, zn_splat(P8::from_raw(65536i32)));
    let n1144: ZN = zsel_n(n1137, zn_splat(P8::from_raw(0i32)), n1088);
    let n1147: ZI = zsel_i(n1137, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1091);
    let n1149: ZN = zsel_n(n1133, n1143, n1093);
    let n1151: ZB = zsel_b(n1137, zb_splat(false), n1095);
    let n1153: ZB = zn_le(n1149, n696);
    let n1154: ZN = zn_add(n1140, zn_splat(u.c403));
    let n1166: ZN = zn_add(n1154, n693);
    let n1176: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n1166, u.c401, u.c400, P8::from_raw(0i32));
    let n1177: ZB = zsel_b(n1176, n1176, zb_splat(false));
    let n1180: ZB = zsel_b(n1177, n1177, zb_splat(false));
    let n1183: ZB = zsel_b(n728, zb_splat(true), n1180);
    let n1185: ZB = zb_not(n1183);
    let n1186: ZB = zsel_b(n1151, n1153, n1151);
    let n1189: ZB = zsel_b(n1186, n1185, n1186);
    let n1192: ZB = zb_not(n1185);
    let n1193: ZB = zsel_b(n1186, n1192, n1186);
    let n1195: ZN = zn_add(n1140, n693);
    let n1196: ZN = zsel_n(n1189, n1195, n1140);
    let n1199: ZN = zsel_n(n1193, zn_splat(P8::from_raw(0i32)), n1144);
    let n1202: ZI = zsel_i(n1193, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1147);
    let n1218: ZN = zn_add(n1196, zn_splat(u.c403));
    let n1473: ZN = zn_add(n1218, zn_splat(P8::from_raw(65536i32)));
    let n1481: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n1473, u.c401, u.c400, P8::from_raw(0i32));
    let n1482: ZB = zsel_b(n1481, n1481, zb_splat(false));
    let n1484: ZB = zsel_b(n1482, n1482, zb_splat(false));
    let n1487: ZB = zn_tile_flag_at(g.cache, g.cart, n704, n1473, u.c401, u.c400, P8::from_raw(262144i32));
    let n1505: ZN = zsel_n(n1484, zn_splat(P8::from_raw(393216i32)), n1503);
    let n1507: ZN = zsel_n(n1484, zn_splat(n1499), zn_splat(u.c300));
    let n1513: ZB = zb_not(n1484);
    let n1516: ZN = zsel_n(n1487, zn_splat(P8::from_raw(3276i32)), zn_splat(P8::from_raw(39321i32)));
    let n1519: ZN = zsel_n(n1513, zn_splat(P8::from_raw(26214i32)), n1516);
    let n1542: ZN = zn_sub(n668, n1519);
    let n1543: ZN = zn_max(n1542, zn_splat(P8::from_raw(0i32)));
    let n1544: ZN = zn_add(n668, n1519);
    let n1545: ZN = zn_min(n1544, zn_splat(P8::from_raw(0i32)));
    let n1546: ZN = zsel_n(n1523, n1543, n1545);
    let n1547: ZN = zsel_n(n1522, n1540, n1546);
    let n1549: ZB = zn_eq(n1547, zn_splat(P8::from_raw(0i32)));
    let n1550: ZB = zb_not(n1549);
    let n1551: ZB = zn_lt(n1547, zn_splat(P8::from_raw(0i32)));
    let n1553: ZB = zsel_b(n1550, n1551, r_c398);
    let n1555: ZN = zn_abs(n1199);
    let n1556: ZB = zn_le(n1555, zn_splat(P8::from_raw(9830i32)));
    let n1559: ZN = zsel_n(n1556, zn_splat(P8::from_raw(6881i32)), zn_splat(P8::from_raw(13762i32)));
    let n1563: ZB = zn_gt(n1199, zn_splat(P8::from_raw(131072i32)));
    let n1564: ZN = zn_sub(n1199, n1559);
    let n1565: ZN = zn_max(n1564, zn_splat(P8::from_raw(131072i32)));
    let n1566: ZN = zn_add(n1199, n1559);
    let n1567: ZN = zn_min(n1566, zn_splat(P8::from_raw(131072i32)));
    let n1568: ZN = zsel_n(n1563, n1565, n1567);
    let n1570: ZN = zsel_n(n1513, n1568, n1199);
    let ok_pre: u16 = ALL;
    let bd_pre: bool = bd0;
    let p = Pre {
        bd_pre,
        ok_pre,
        valid: valid1,
    };
    let osh = KOutShared {
        c38: true,
        c39: P8::from_raw(983040i32),
        c84: n11,
        c87: n1464,
        c246: n110,
        c254: n121,
        c297: n1509,
        c300: n1507,
        c302: n1505,
        c309: false,
        c310: false,
        c316: n665,
        c317: n1196,
        c398: n1553,
        c404: n671,
        c405: n1202,
        c406: n1547,
        c407: n1570,
    };
    // suffix observes button bits []: 1 distinct variant(s)
    suffix::<0>(u, g, &p, &osh, out);
    }
    }
}

#[inline(never)]
fn suffix<const B: u8>(u: &Uni, g: &G, p: &Pre, osh: &KOutShared, out: &mut impl FnMut(u8, &KOutShared, &KOut)) {
    let bd_pre = p.bd_pre;
    let ok_pre = p.ok_pre;
    let kb0: bool = (B >> 0) & 1 != 0;
    let kb1: bool = (B >> 1) & 1 != 0;
    let kb2: bool = (B >> 2) & 1 != 0;
    let kb3: bool = (B >> 3) & 1 != 0;
    let kb4: bool = (B >> 4) & 1 != 0;
    let kb5: bool = (B >> 5) & 1 != 0;
    let ok_out: u16 = ok_pre;
    let bd_out: bool = bd_pre;
    out(B, osh, &KOut {
        valid: p.valid,
        deopt: !ok_out,
        bd: bd_out,
    });
}
