// GENERATED by `transpile --kernel` (plans/kernel-plan.md). Do not edit.
//
// The STEADY-CLASS lane kernel: shape (player), pm1 freeze=0 dash_time=0.
// Shared prefix per 16-row slice, 64 monomorphized button suffixes.
#![allow(unused_variables, unused_mut, unused_imports, clippy::all)]
use celeste_engine::kernel::*;
use celeste_core::pico8_num::{Pico8Num as P8, Pico8NumInterval as IV};
use celeste_core::cart_data::CartData;
use celeste_core::collision_cache::CollisionCache;

pub const SHAPE_HASH: u64 = 0xa9e20c0af79aea86;
pub struct G<'a> { pub cart: &'a CartData, pub cache: &'a CollisionCache }

/// Block-uniform inputs, bound per block (kind-checked).
pub struct Uni {
    pub c20: P8,
    pub c38: bool,
    pub c39: P8,
    pub c41: bool,
    pub c42: bool,
    pub c43: bool,
    pub c44: P8,
    pub c45: P8,
    pub c46: P8,
    pub c47: P8,
    pub c48: P8,
    pub c49: P8,
    pub c84: P8,
    pub c85: P8,
    pub c86: P8,
    pub c87: P8,
    pub c88: P8,
    pub c159: P8,
    pub c161: P8,
    pub c162: P8,
    pub c174: P8,
    pub c177: P8,
    pub c180: P8,
    pub c182: bool,
    pub c184: P8,
    pub c186: bool,
    pub c188: P8,
    pub c190: bool,
    pub c191: P8,
    pub c193: bool,
    pub c194: P8,
    pub c196: bool,
    pub c198: P8,
    pub c204: P8,
    pub c238: bool,
    pub c246: (P8, P8),
    pub c248: bool,
    pub c250: P8,
    pub c251: P8,
    pub c253: P8,
    pub c254: (P8, P8),
    pub c257: bool,
    pub c259: P8,
    pub c260: P8,
    pub c268: bool,
    pub c270: P8,
    pub c272: P8,
    pub c273: P8,
    pub c276: bool,
    pub c278: P8,
    pub c279: P8,
    pub c287: bool,
    pub c289: P8,
    pub c291: P8,
    pub c292: P8,
    pub c295: bool,
    pub c299: P8,
    pub c300: P8,
    pub c309: bool,
    pub c310: bool,
    pub c312: bool,
    pub c364: bool,
    pub c365: bool,
    pub c366: P8,
    pub c367: P8,
    pub c368: P8,
    pub c369: P8,
    pub c370: P8,
    pub c371: P8,
    pub c372: P8,
    pub c373: P8,
    pub c374: bool,
    pub c375: bool,
    pub c376: P8,
    pub c377: P8,
    pub c378: P8,
    pub c379: P8,
    pub c380: P8,
    pub c381: P8,
    pub c382: P8,
    pub c383: P8,
    pub c384: bool,
    pub c385: bool,
    pub c386: P8,
    pub c387: P8,
    pub c388: P8,
    pub c389: P8,
    pub c390: P8,
    pub c391: P8,
    pub c392: P8,
    pub c393: P8,
    pub c399: bool,
    pub c400: P8,
    pub c401: P8,
    pub c402: P8,
    pub c403: P8,
    pub c404: (P8, P8),
    pub c405: (P8, P8),
}

pub const UNI_CELLS: &[(u32, &str)] = &[
    (20, "num"),
    (38, "bool"),
    (39, "num"),
    (41, "bool"),
    (42, "bool"),
    (43, "bool"),
    (44, "num"),
    (45, "num"),
    (46, "num"),
    (47, "num"),
    (48, "num"),
    (49, "num"),
    (84, "num"),
    (85, "num"),
    (86, "num"),
    (87, "num"),
    (88, "num"),
    (159, "num"),
    (161, "num"),
    (162, "num"),
    (174, "num"),
    (177, "num"),
    (180, "num"),
    (182, "bool"),
    (184, "num"),
    (186, "bool"),
    (188, "num"),
    (190, "bool"),
    (191, "num"),
    (193, "bool"),
    (194, "num"),
    (196, "bool"),
    (198, "num"),
    (204, "num"),
    (238, "bool"),
    (246, "ival"),
    (248, "bool"),
    (250, "num"),
    (251, "num"),
    (253, "num"),
    (254, "ival"),
    (257, "bool"),
    (259, "num"),
    (260, "num"),
    (268, "bool"),
    (270, "num"),
    (272, "num"),
    (273, "num"),
    (276, "bool"),
    (278, "num"),
    (279, "num"),
    (287, "bool"),
    (289, "num"),
    (291, "num"),
    (292, "num"),
    (295, "bool"),
    (299, "num"),
    (300, "num"),
    (309, "bool"),
    (310, "bool"),
    (312, "bool"),
    (364, "bool"),
    (365, "bool"),
    (366, "num"),
    (367, "num"),
    (368, "num"),
    (369, "num"),
    (370, "num"),
    (371, "num"),
    (372, "num"),
    (373, "num"),
    (374, "bool"),
    (375, "bool"),
    (376, "num"),
    (377, "num"),
    (378, "num"),
    (379, "num"),
    (380, "num"),
    (381, "num"),
    (382, "num"),
    (383, "num"),
    (384, "bool"),
    (385, "bool"),
    (386, "num"),
    (387, "num"),
    (388, "num"),
    (389, "num"),
    (390, "num"),
    (391, "num"),
    (392, "num"),
    (393, "num"),
    (399, "bool"),
    (400, "num"),
    (401, "num"),
    (402, "num"),
    (403, "num"),
    (404, "ival"),
    (405, "ival"),
];

/// Folds consumed these uniform cells' witness values; bind must
/// guard them (raw bits) or send the block to the interpreter.
pub const PIN_CELLS: &[(u32, i32)] = &[
    (44, 0i32),
    (45, 65536i32),
    (48, 262144i32),
    (49, 327680i32),
];

/// Per-lane inputs: 16 rows per slice.
pub struct RowsIn {
    pub c297: ZN,
    pub c302: ZN,
    pub c316: ZN,
    pub c317: ZN,
    pub c394: ZN,
    pub c395: ZN,
    pub c396: ZN,
    pub c397: ZN,
    pub c398: u16,
    pub c406: ZN,
    pub c407: ZN,
}

pub const VARY_CELLS: &[(u32, &str)] = &[
    (297, "num"),
    (302, "num"),
    (316, "num"),
    (317, "num"),
    (394, "num"),
    (395, "num"),
    (396, "num"),
    (397, "num"),
    (398, "bool"),
    (406, "num"),
    (407, "num"),
];

/// Button-independent outputs: one per fork config.
pub struct KOutShared {
    pub c38: bool,
    pub c39: P8,
    pub c84: P8,
    pub c87: P8,
    pub c246: (P8, P8),
    pub c254: (P8, P8),
    pub c297: ZN,
    pub c300: ZN,
    pub c302: ZN,
    pub c309: bool,
    pub c310: bool,
    pub c316: ZN,
    pub c317: ZN,
    pub c398: ZB,
    pub c404: ZI,
    pub c405: ZI,
    pub c406: ZN,
    pub c407: ZN,
}

/// Button-dependent outputs: one per (config, variant).
pub struct KOut {
    /// Lanes that EXIST in this fork configuration.
    pub valid: u16,
    pub deopt: u16,
    pub bd: bool,
}

pub const OUT_CELLS: &[u32] = &[
    38,
    39,
    84,
    87,
    246,
    254,
    297,
    300,
    302,
    309,
    310,
    316,
    317,
    398,
    404,
    405,
    406,
    407,
];

/// Cells that end every frame as a fresh UnknownBool (the next
/// frame's button inputs); the boundary writes UBool, no data.
pub const OUT_UBOOL_CELLS: &[u32] = &[
    145,
    146,
    147,
    148,
    149,
    150,
];

use celeste_engine::runtime2::{Rt2, Col, AV};

/// Bind the block-uniform inputs. None = off-shape / off-kind /
/// pin mismatch: the block takes the reference path.
pub fn bind(b: &Rt2) -> Option<Uni> {
    if b.shape_hash != SHAPE_HASH { return None; }
    for (cell, pin) in PIN_CELLS {
        match &b.cols[*cell as usize] {
            Col::U(AV::Num(n)) if n.as_raw_u32() as i32 == *pin => {}
            _ => return None,
        }
    }
    Some(Uni {
        c20: match &b.cols[20] { Col::U(AV::Num(n)) => *n, _ => return None },
        c38: match &b.cols[38] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c39: match &b.cols[39] { Col::U(AV::Num(n)) => *n, _ => return None },
        c41: match &b.cols[41] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c42: match &b.cols[42] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c43: match &b.cols[43] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c44: match &b.cols[44] { Col::U(AV::Num(n)) => *n, _ => return None },
        c45: match &b.cols[45] { Col::U(AV::Num(n)) => *n, _ => return None },
        c46: match &b.cols[46] { Col::U(AV::Num(n)) => *n, _ => return None },
        c47: match &b.cols[47] { Col::U(AV::Num(n)) => *n, _ => return None },
        c48: match &b.cols[48] { Col::U(AV::Num(n)) => *n, _ => return None },
        c49: match &b.cols[49] { Col::U(AV::Num(n)) => *n, _ => return None },
        c84: match &b.cols[84] { Col::U(AV::Num(n)) => *n, _ => return None },
        c85: match &b.cols[85] { Col::U(AV::Num(n)) => *n, _ => return None },
        c86: match &b.cols[86] { Col::U(AV::Num(n)) => *n, _ => return None },
        c87: match &b.cols[87] { Col::U(AV::Num(n)) => *n, _ => return None },
        c88: match &b.cols[88] { Col::U(AV::Num(n)) => *n, _ => return None },
        c159: match &b.cols[159] { Col::U(AV::Num(n)) => *n, _ => return None },
        c161: match &b.cols[161] { Col::U(AV::Num(n)) => *n, _ => return None },
        c162: match &b.cols[162] { Col::U(AV::Num(n)) => *n, _ => return None },
        c174: match &b.cols[174] { Col::U(AV::Num(n)) => *n, _ => return None },
        c177: match &b.cols[177] { Col::U(AV::Num(n)) => *n, _ => return None },
        c180: match &b.cols[180] { Col::U(AV::Num(n)) => *n, _ => return None },
        c182: match &b.cols[182] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c184: match &b.cols[184] { Col::U(AV::Num(n)) => *n, _ => return None },
        c186: match &b.cols[186] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c188: match &b.cols[188] { Col::U(AV::Num(n)) => *n, _ => return None },
        c190: match &b.cols[190] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c191: match &b.cols[191] { Col::U(AV::Num(n)) => *n, _ => return None },
        c193: match &b.cols[193] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c194: match &b.cols[194] { Col::U(AV::Num(n)) => *n, _ => return None },
        c196: match &b.cols[196] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c198: match &b.cols[198] { Col::U(AV::Num(n)) => *n, _ => return None },
        c204: match &b.cols[204] { Col::U(AV::Num(n)) => *n, _ => return None },
        c238: match &b.cols[238] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c246: match &b.cols[246] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c248: match &b.cols[248] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c250: match &b.cols[250] { Col::U(AV::Num(n)) => *n, _ => return None },
        c251: match &b.cols[251] { Col::U(AV::Num(n)) => *n, _ => return None },
        c253: match &b.cols[253] { Col::U(AV::Num(n)) => *n, _ => return None },
        c254: match &b.cols[254] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c257: match &b.cols[257] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c259: match &b.cols[259] { Col::U(AV::Num(n)) => *n, _ => return None },
        c260: match &b.cols[260] { Col::U(AV::Num(n)) => *n, _ => return None },
        c268: match &b.cols[268] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c270: match &b.cols[270] { Col::U(AV::Num(n)) => *n, _ => return None },
        c272: match &b.cols[272] { Col::U(AV::Num(n)) => *n, _ => return None },
        c273: match &b.cols[273] { Col::U(AV::Num(n)) => *n, _ => return None },
        c276: match &b.cols[276] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c278: match &b.cols[278] { Col::U(AV::Num(n)) => *n, _ => return None },
        c279: match &b.cols[279] { Col::U(AV::Num(n)) => *n, _ => return None },
        c287: match &b.cols[287] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c289: match &b.cols[289] { Col::U(AV::Num(n)) => *n, _ => return None },
        c291: match &b.cols[291] { Col::U(AV::Num(n)) => *n, _ => return None },
        c292: match &b.cols[292] { Col::U(AV::Num(n)) => *n, _ => return None },
        c295: match &b.cols[295] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c299: match &b.cols[299] { Col::U(AV::Num(n)) => *n, _ => return None },
        c300: match &b.cols[300] { Col::U(AV::Num(n)) => *n, _ => return None },
        c309: match &b.cols[309] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c310: match &b.cols[310] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c312: match &b.cols[312] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c364: match &b.cols[364] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c365: match &b.cols[365] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c366: match &b.cols[366] { Col::U(AV::Num(n)) => *n, _ => return None },
        c367: match &b.cols[367] { Col::U(AV::Num(n)) => *n, _ => return None },
        c368: match &b.cols[368] { Col::U(AV::Num(n)) => *n, _ => return None },
        c369: match &b.cols[369] { Col::U(AV::Num(n)) => *n, _ => return None },
        c370: match &b.cols[370] { Col::U(AV::Num(n)) => *n, _ => return None },
        c371: match &b.cols[371] { Col::U(AV::Num(n)) => *n, _ => return None },
        c372: match &b.cols[372] { Col::U(AV::Num(n)) => *n, _ => return None },
        c373: match &b.cols[373] { Col::U(AV::Num(n)) => *n, _ => return None },
        c374: match &b.cols[374] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c375: match &b.cols[375] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c376: match &b.cols[376] { Col::U(AV::Num(n)) => *n, _ => return None },
        c377: match &b.cols[377] { Col::U(AV::Num(n)) => *n, _ => return None },
        c378: match &b.cols[378] { Col::U(AV::Num(n)) => *n, _ => return None },
        c379: match &b.cols[379] { Col::U(AV::Num(n)) => *n, _ => return None },
        c380: match &b.cols[380] { Col::U(AV::Num(n)) => *n, _ => return None },
        c381: match &b.cols[381] { Col::U(AV::Num(n)) => *n, _ => return None },
        c382: match &b.cols[382] { Col::U(AV::Num(n)) => *n, _ => return None },
        c383: match &b.cols[383] { Col::U(AV::Num(n)) => *n, _ => return None },
        c384: match &b.cols[384] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c385: match &b.cols[385] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c386: match &b.cols[386] { Col::U(AV::Num(n)) => *n, _ => return None },
        c387: match &b.cols[387] { Col::U(AV::Num(n)) => *n, _ => return None },
        c388: match &b.cols[388] { Col::U(AV::Num(n)) => *n, _ => return None },
        c389: match &b.cols[389] { Col::U(AV::Num(n)) => *n, _ => return None },
        c390: match &b.cols[390] { Col::U(AV::Num(n)) => *n, _ => return None },
        c391: match &b.cols[391] { Col::U(AV::Num(n)) => *n, _ => return None },
        c392: match &b.cols[392] { Col::U(AV::Num(n)) => *n, _ => return None },
        c393: match &b.cols[393] { Col::U(AV::Num(n)) => *n, _ => return None },
        c399: match &b.cols[399] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c400: match &b.cols[400] { Col::U(AV::Num(n)) => *n, _ => return None },
        c401: match &b.cols[401] { Col::U(AV::Num(n)) => *n, _ => return None },
        c402: match &b.cols[402] { Col::U(AV::Num(n)) => *n, _ => return None },
        c403: match &b.cols[403] { Col::U(AV::Num(n)) => *n, _ => return None },
        c404: match &b.cols[404] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c405: match &b.cols[405] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
    })
}

/// Gather rows [lo, lo+16) into lane arrays; short slices pad by
/// repeating the last row (padded outputs are ignored by width).
pub fn rows(b: &Rt2, lo: usize) -> Option<RowsIn> {
    let at = |i: usize| -> usize { (lo + i).min(b.width - 1) };
    Some(RowsIn {
        c297: match &b.cols[297] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c302: match &b.cols[302] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c316: match &b.cols[316] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c317: match &b.cols[317] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c394: match &b.cols[394] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c395: match &b.cols[395] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c396: match &b.cols[396] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c397: match &b.cols[397] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c398: match &b.cols[398] {
            Col::V(v) => {
                let mut m = 0u16;
                for i in 0..W { if matches!(v[at(i)], AV::Bool(true)) { m |= 1 << i; } else if !matches!(v[at(i)], AV::Bool(false)) { return None; } }
                m
            }
            Col::U(AV::Bool(t)) => if *t { 0xffff } else { 0 },
            _ => return None,
        },
        c406: match &b.cols[406] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c407: match &b.cols[407] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
    })
}

/// Write one (config, variant) result onto a width-`n` sliced block
/// (the block already carries the input row values).
pub fn apply(sh: &KOutShared, kv: &KOut, b: &mut Rt2, n: usize) {
    b.cols[38] = Col::U(AV::Bool(sh.c38));
    b.cols[39] = Col::U(AV::Num(sh.c39));
    b.cols[84] = Col::U(AV::Num(sh.c84));
    b.cols[87] = Col::U(AV::Num(sh.c87));
    b.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
    b.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
    b.cols[297] = Col::N(sh.c297[..n].to_vec());
    b.cols[300] = Col::N(sh.c300[..n].to_vec());
    b.cols[302] = Col::N(sh.c302[..n].to_vec());
    b.cols[309] = Col::U(AV::Bool(sh.c309));
    b.cols[310] = Col::U(AV::Bool(sh.c310));
    b.cols[316] = Col::N(sh.c316[..n].to_vec());
    b.cols[317] = Col::N(sh.c317[..n].to_vec());
    b.cols[398] = Col::V((0..n).map(|i| AV::Bool(sh.c398.val & (1 << i) != 0)).collect());
    b.cols[404] = Col::I((0..n).map(|i| (sh.c404.lo[i], sh.c404.hi[i])).collect());
    b.cols[405] = Col::I((0..n).map(|i| (sh.c405.lo[i], sh.c405.hi[i])).collect());
    b.cols[406] = Col::N(sh.c406[..n].to_vec());
    b.cols[407] = Col::N(sh.c407[..n].to_vec());
    for cell in OUT_UBOOL_CELLS {
        b.cols[*cell as usize] = Col::U(AV::UBool);
    }
}

/// One wide output block per chunk: structure + uniforms cloned
/// once, varying/output columns start empty and grow by appends.
pub fn acc_init(chunk: &Rt2) -> Rt2 {
    let mut acc = Rt2::empty(0, chunk.globals.len(), &[], chunk.cart.clone(), chunk.cache.clone());
    acc.strings = chunk.strings.clone();
    acc.globals = chunk.globals.clone();
    acc.structure = chunk.structure.clone();
    acc.cols = chunk.cols.clone();
    acc.shape_hash = chunk.shape_hash;
    acc.cols[297] = Col::N(Vec::new());
    acc.cols[300] = Col::N(Vec::new());
    acc.cols[302] = Col::N(Vec::new());
    acc.cols[316] = Col::N(Vec::new());
    acc.cols[317] = Col::N(Vec::new());
    acc.cols[398] = Col::V(Vec::new());
    acc.cols[404] = Col::I(Vec::new());
    acc.cols[405] = Col::I(Vec::new());
    acc.cols[406] = Col::N(Vec::new());
    acc.cols[407] = Col::N(Vec::new());
    acc.cols[394] = Col::N(Vec::new());
    acc.cols[395] = Col::N(Vec::new());
    acc.cols[396] = Col::N(Vec::new());
    acc.cols[397] = Col::N(Vec::new());
    for cell in OUT_UBOOL_CELLS {
        acc.cols[*cell as usize] = Col::U(AV::UBool);
    }
    acc
}

/// Append one (config, variant)'s live lanes onto the accumulator.
/// `lo` is the slice base in `chunk` (identity columns read there).
#[allow(unused_variables)]
pub fn append_out(acc: &mut Rt2, chunk: &Rt2, lo: usize, n: usize, live: u16, sh: &KOutShared, kv: &KOut, bd: &mut bool) {
    // fresh: no fork config has written yet, so a uniform slot
    // still holds the chunk's INPUT value (legitimately different).
    let fresh = acc.width == 0;
    for i in 0..n {
        if live & (1 << i) == 0 { continue; }
        if !fresh { if let Col::U(AV::Bool(prev)) = &acc.cols[38] { if *prev != sh.c38 { *bd = true; } } }
        acc.cols[38] = Col::U(AV::Bool(sh.c38));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[39] { if *prev != sh.c39 { *bd = true; } } }
        acc.cols[39] = Col::U(AV::Num(sh.c39));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[84] { if *prev != sh.c84 { *bd = true; } } }
        acc.cols[84] = Col::U(AV::Num(sh.c84));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[87] { if *prev != sh.c87 { *bd = true; } } }
        acc.cols[87] = Col::U(AV::Num(sh.c87));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[246] { if (*a, *b) != sh.c246 { *bd = true; } } }
        acc.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[254] { if (*a, *b) != sh.c254 { *bd = true; } } }
        acc.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
        if let Col::N(v) = &mut acc.cols[297] { v.push(sh.c297[i]); }
        if let Col::N(v) = &mut acc.cols[300] { v.push(sh.c300[i]); }
        if let Col::N(v) = &mut acc.cols[302] { v.push(sh.c302[i]); }
        if !fresh { if let Col::U(AV::Bool(prev)) = &acc.cols[309] { if *prev != sh.c309 { *bd = true; } } }
        acc.cols[309] = Col::U(AV::Bool(sh.c309));
        if !fresh { if let Col::U(AV::Bool(prev)) = &acc.cols[310] { if *prev != sh.c310 { *bd = true; } } }
        acc.cols[310] = Col::U(AV::Bool(sh.c310));
        if let Col::N(v) = &mut acc.cols[316] { v.push(sh.c316[i]); }
        if let Col::N(v) = &mut acc.cols[317] { v.push(sh.c317[i]); }
        if let Col::V(v) = &mut acc.cols[398] { v.push(AV::Bool(sh.c398.val & (1 << i) != 0)); }
        if let Col::I(v) = &mut acc.cols[404] { v.push((sh.c404.lo[i], sh.c404.hi[i])); }
        if let Col::I(v) = &mut acc.cols[405] { v.push((sh.c405.lo[i], sh.c405.hi[i])); }
        if let Col::N(v) = &mut acc.cols[406] { v.push(sh.c406[i]); }
        if let Col::N(v) = &mut acc.cols[407] { v.push(sh.c407[i]); }
        let val = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[394] { v.push(val); }
        let val = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[395] { v.push(val); }
        let val = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[396] { v.push(val); }
        let val = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[397] { v.push(val); }
        acc.width += 1;
    }
}

/// Cells the pre-dedup key covers, in key-bit order.
pub const KEY_CELLS: &[u32] = &[
    38,
    39,
    84,
    87,
    246,
    254,
    297,
    300,
    302,
    309,
    310,
    316,
    317,
    398,
    404,
    405,
    406,
    407,
    394,
    395,
    396,
    397,
];

#[allow(unused_variables)]
pub fn row_keys(chunk: &Rt2, lo: usize, n: usize, sh: &KOutShared, kv: &KOut, plan: &KeyPlan, keys: &mut [(u64, u64); W]) {
    let mut h1 = [0u64; W];
    let mut h2 = [0u64; W];
    // cell 38 (bool)
    if plan.rem & (1 << 0) == 0 {
        assert!(plan.det & (1 << 0) == 0, "det clamp on non-numeric cell 38");
        for i in 0..W {
            let v = AV::Bool(sh.c38);
            h1[i] = h1[i].wrapping_add(cell_mix(38u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(38u64, v, 0x27d4_eb2f));
        }
    }
    // cell 39 (P8)
    if plan.rem & (1 << 1) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (39u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (39u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c39;
            let v = if plan.det & (1 << 1) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 84 (P8)
    if plan.rem & (1 << 2) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c84;
            let v = if plan.det & (1 << 2) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 87 (P8)
    if plan.rem & (1 << 3) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (87u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (87u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c87;
            let v = if plan.det & (1 << 3) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 246 ((P8, P8))
    if plan.rem & (1 << 4) == 0 {
        assert!(plan.det & (1 << 4) == 0, "det clamp on non-numeric cell 246");
        for i in 0..W {
            let v = AV::Ival(sh.c246.0, sh.c246.1);
            h1[i] = h1[i].wrapping_add(cell_mix(246u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(246u64, v, 0x27d4_eb2f));
        }
    }
    // cell 254 ((P8, P8))
    if plan.rem & (1 << 5) == 0 {
        assert!(plan.det & (1 << 5) == 0, "det clamp on non-numeric cell 254");
        for i in 0..W {
            let v = AV::Ival(sh.c254.0, sh.c254.1);
            h1[i] = h1[i].wrapping_add(cell_mix(254u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(254u64, v, 0x27d4_eb2f));
        }
    }
    // cell 297 (ZN)
    if plan.rem & (1 << 6) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c297[i];
            let v = if plan.det & (1 << 6) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 300 (ZN)
    if plan.rem & (1 << 7) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c300[i];
            let v = if plan.det & (1 << 7) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 302 (ZN)
    if plan.rem & (1 << 8) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c302[i];
            let v = if plan.det & (1 << 8) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 309 (bool)
    if plan.rem & (1 << 9) == 0 {
        assert!(plan.det & (1 << 9) == 0, "det clamp on non-numeric cell 309");
        for i in 0..W {
            let v = AV::Bool(sh.c309);
            h1[i] = h1[i].wrapping_add(cell_mix(309u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(309u64, v, 0x27d4_eb2f));
        }
    }
    // cell 310 (bool)
    if plan.rem & (1 << 10) == 0 {
        assert!(plan.det & (1 << 10) == 0, "det clamp on non-numeric cell 310");
        for i in 0..W {
            let v = AV::Bool(sh.c310);
            h1[i] = h1[i].wrapping_add(cell_mix(310u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(310u64, v, 0x27d4_eb2f));
        }
    }
    // cell 316 (ZN)
    if plan.rem & (1 << 11) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c316[i];
            let v = if plan.det & (1 << 11) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 317 (ZN)
    if plan.rem & (1 << 12) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c317[i];
            let v = if plan.det & (1 << 12) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 398 (ZB)
    if plan.rem & (1 << 13) == 0 {
        assert!(plan.det & (1 << 13) == 0, "det clamp on non-numeric cell 398");
        for i in 0..W {
            let v = AV::Bool(sh.c398.val & (1 << i) != 0);
            h1[i] = h1[i].wrapping_add(cell_mix(398u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(398u64, v, 0x27d4_eb2f));
        }
    }
    // cell 404 (ZI)
    if plan.rem & (1 << 14) == 0 {
        assert!(plan.det & (1 << 14) == 0, "det clamp on non-numeric cell 404");
        for i in 0..W {
            let v = AV::Ival(sh.c404.lo[i], sh.c404.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(404u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(404u64, v, 0x27d4_eb2f));
        }
    }
    // cell 405 (ZI)
    if plan.rem & (1 << 15) == 0 {
        assert!(plan.det & (1 << 15) == 0, "det clamp on non-numeric cell 405");
        for i in 0..W {
            let v = AV::Ival(sh.c405.lo[i], sh.c405.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(405u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(405u64, v, 0x27d4_eb2f));
        }
    }
    // cell 406 (ZN)
    if plan.rem & (1 << 16) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c406[i];
            let v = if plan.det & (1 << 16) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 407 (ZN)
    if plan.rem & (1 << 17) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c407[i];
            let v = if plan.det & (1 << 17) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 394 (IN_N)
    if plan.rem & (1 << 18) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 18) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 395 (IN_N)
    if plan.rem & (1 << 19) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 19) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 396 (IN_N)
    if plan.rem & (1 << 20) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 20) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 397 (IN_N)
    if plan.rem & (1 << 21) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 21) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    for i in 0..W {
        keys[i] = (mix64(h1[i]), mix64(h2[i]));
    }
}

#[inline(never)]
pub fn frame(u: &Uni, rin: &RowsIn, g: &G, out: &mut impl FnMut(u8, &KOutShared, &KOut)) {
    let r_c297: ZN = rin.c297;
    let r_c302: ZN = rin.c302;
    let r_c316: ZN = rin.c316;
    let r_c317: ZN = rin.c317;
    let r_c394: ZN = rin.c394;
    let r_c395: ZN = rin.c395;
    let r_c396: ZN = rin.c396;
    let r_c397: ZN = rin.c397;
    let r_c398: ZB = ZB { val: rin.c398, known: ALL };
    let r_c406: ZN = rin.c406;
    let r_c407: ZN = rin.c407;
    let n4: P8 = P8::from_raw(65536i32) + u.c84;
    let n6: P8 = n4 % P8::from_raw(1966080i32);
    let n77: ZN = zn_add(zn_splat(u.c402), r_c316);
    let n85: ZN = zn_add(zn_splat(u.c403), r_c317);
    let n105: (P8, P8) = si_add((P8::from_raw(65536i32), P8::from_raw(65536i32)), u.c246);
    let n114: (P8, P8) = { let r = IV::new((P8::from_raw(-65536i32), P8::from_raw(65536i32)).0, (P8::from_raw(-65536i32), P8::from_raw(65536i32)).1).scale_positive(P8::from_raw(163840i32)); (r.low, r.high) };
    let n116: (P8, P8) = si_add(n114, (u.c251, u.c251));
    let n241: ZI = zi_add(zi_of_zn(r_c406), zi_splat(u.c404.0, u.c404.1));
    let n243: ZI = zi_add(n241, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n274: ZN = zn_add(zn_splat(P8::from_raw(0i32)), n85);
    let n638: ZI = zi_add(zi_of_zn(r_c407), zi_splat(u.c405.0, u.c405.1));
    let n639: ZI = zi_add(zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)), n638);
    let n1395: P8 = P8::from_raw(65536i32) + u.c87;
    let n1426: bool = u.c300 < u.c88;
    let n1427: P8 = if n1426 { u.c88 } else { u.c300 };
    let n1429: ZB = zn_gt(r_c302, zn_splat(P8::from_raw(0i32)));
    let n1430: ZN = zn_sub(r_c302, zn_splat(P8::from_raw(65536i32)));
    let n1431: ZN = zsel_n(n1429, n1430, r_c302);
    let n1436: ZN = zn_sub(r_c297, zn_splat(P8::from_raw(65536i32)));
    for c0 in 0..2usize {
    let (f0, f0_fv): (ZI, u16) = zi_fork_flr(n243, c0);
    let valid0: u16 = ALL & f0_fv;
    if valid0 == 0 { continue; }
    let n248: ZN = zi_flr(f0);
    let n251: ZI = zi_sub(f0, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n252: ZI = zi_sub(n251, zi_of_zn(n248));
    let n255: ZB = zn_gt(n248, zn_splat(P8::from_raw(0i32)));
    let n256: ZB = zn_lt(n248, zn_splat(P8::from_raw(0i32)));
    let n257: ZB = zsel_b(n255, n255, n256);
    let n261: ZN = zsel_n(n255, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)));
    let n263: ZN = zsel_n(n257, n261, zn_splat(P8::from_raw(0i32)));
    let n266: ZN = zn_abs(n248);
    let n272: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n266);
    let n273: ZN = zn_add(n77, n263);
    let n275: ZB = zn_tile_flag_at(g.cache, g.cart, n273, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n297: ZB = zb_not(n275);
    let n298: ZB = zsel_b(n272, n297, n272);
    let n301: ZB = zsel_b(n272, n275, n272);
    let n303: ZN = zn_add(r_c316, n263);
    let n304: ZN = zsel_n(n298, n303, r_c316);
    let n307: ZN = zsel_n(n301, zn_splat(P8::from_raw(0i32)), r_c406);
    let n310: ZI = zsel_i(n301, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n252);
    let n312: ZN = zsel_n(n298, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n314: ZB = zb_not(n301);
    let n316: ZB = zn_le(n312, n266);
    let n317: ZN = zn_add(zn_splat(u.c402), n304);
    let n318: ZN = zn_add(n263, n317);
    let n319: ZB = zn_tile_flag_at(g.cache, g.cart, n318, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n333: ZB = zb_not(n319);
    let n334: ZB = zsel_b(n314, n316, n314);
    let n336: ZB = zsel_b(n334, n333, n334);
    let n339: ZB = zsel_b(n334, n319, n334);
    let n341: ZN = zn_add(n263, n304);
    let n342: ZN = zsel_n(n336, n341, n304);
    let n345: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n312);
    let n346: ZN = zsel_n(n339, zn_splat(P8::from_raw(0i32)), n307);
    let n349: ZI = zsel_i(n339, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n310);
    let n351: ZN = zsel_n(n336, n345, n312);
    let n353: ZB = zb_not(n339);
    let n354: ZB = zb_and(n314, n353);
    let n356: ZB = zn_le(n351, n266);
    let n357: ZN = zn_add(zn_splat(u.c402), n342);
    let n358: ZN = zn_add(n263, n357);
    let n359: ZB = zn_tile_flag_at(g.cache, g.cart, n358, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n373: ZB = zb_not(n359);
    let n374: ZB = zsel_b(n354, n356, n354);
    let n377: ZB = zsel_b(n374, n373, n374);
    let n380: ZB = zsel_b(n374, n359, n374);
    let n382: ZN = zn_add(n263, n342);
    let n383: ZN = zsel_n(n377, n382, n342);
    let n386: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n351);
    let n387: ZN = zsel_n(n380, zn_splat(P8::from_raw(0i32)), n346);
    let n390: ZI = zsel_i(n380, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n349);
    let n392: ZN = zsel_n(n377, n386, n351);
    let n394: ZB = zb_not(n380);
    let n395: ZB = zb_and(n354, n394);
    let n397: ZB = zn_le(n392, n266);
    let n398: ZN = zn_add(zn_splat(u.c402), n383);
    let n399: ZN = zn_add(n263, n398);
    let n400: ZB = zn_tile_flag_at(g.cache, g.cart, n399, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n414: ZB = zb_not(n400);
    let n415: ZB = zsel_b(n395, n397, n395);
    let n418: ZB = zsel_b(n415, n414, n415);
    let n421: ZB = zsel_b(n415, n400, n415);
    let n423: ZN = zn_add(n263, n383);
    let n424: ZN = zsel_n(n418, n423, n383);
    let n427: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n392);
    let n428: ZN = zsel_n(n421, zn_splat(P8::from_raw(0i32)), n387);
    let n431: ZI = zsel_i(n421, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n390);
    let n433: ZN = zsel_n(n418, n427, n392);
    let n435: ZB = zb_not(n421);
    let n436: ZB = zb_and(n395, n435);
    let n438: ZB = zn_le(n433, n266);
    let n439: ZN = zn_add(zn_splat(u.c402), n424);
    let n440: ZN = zn_add(n263, n439);
    let n441: ZB = zn_tile_flag_at(g.cache, g.cart, n440, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n455: ZB = zb_not(n441);
    let n456: ZB = zsel_b(n436, n438, n436);
    let n459: ZB = zsel_b(n456, n455, n456);
    let n462: ZB = zsel_b(n456, n441, n456);
    let n464: ZN = zn_add(n263, n424);
    let n465: ZN = zsel_n(n459, n464, n424);
    let n468: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n433);
    let n469: ZN = zsel_n(n462, zn_splat(P8::from_raw(0i32)), n428);
    let n472: ZI = zsel_i(n462, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n431);
    let n474: ZN = zsel_n(n459, n468, n433);
    let n476: ZB = zb_not(n462);
    let n477: ZB = zb_and(n436, n476);
    let n479: ZB = zn_le(n474, n266);
    let n480: ZN = zn_add(zn_splat(u.c402), n465);
    let n481: ZN = zn_add(n263, n480);
    let n482: ZB = zn_tile_flag_at(g.cache, g.cart, n481, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n496: ZB = zb_not(n482);
    let n497: ZB = zsel_b(n477, n479, n477);
    let n500: ZB = zsel_b(n497, n496, n497);
    let n503: ZB = zsel_b(n497, n482, n497);
    let n505: ZN = zn_add(n263, n465);
    let n506: ZN = zsel_n(n500, n505, n465);
    let n509: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n474);
    let n510: ZN = zsel_n(n503, zn_splat(P8::from_raw(0i32)), n469);
    let n513: ZI = zsel_i(n503, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n472);
    let n515: ZN = zsel_n(n500, n509, n474);
    let n517: ZB = zb_not(n503);
    let n518: ZB = zb_and(n477, n517);
    let n520: ZB = zn_le(n515, n266);
    let n521: ZN = zn_add(zn_splat(u.c402), n506);
    let n522: ZN = zn_add(n263, n521);
    let n523: ZB = zn_tile_flag_at(g.cache, g.cart, n522, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n537: ZB = zb_not(n523);
    let n538: ZB = zsel_b(n518, n520, n518);
    let n541: ZB = zsel_b(n538, n537, n538);
    let n544: ZB = zsel_b(n538, n523, n538);
    let n546: ZN = zn_add(n263, n506);
    let n547: ZN = zsel_n(n541, n546, n506);
    let n550: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n515);
    let n551: ZN = zsel_n(n544, zn_splat(P8::from_raw(0i32)), n510);
    let n554: ZI = zsel_i(n544, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n513);
    let n556: ZN = zsel_n(n541, n550, n515);
    let n558: ZB = zb_not(n544);
    let n559: ZB = zb_and(n518, n558);
    let n561: ZB = zn_le(n556, n266);
    let n562: ZN = zn_add(zn_splat(u.c402), n547);
    let n563: ZN = zn_add(n263, n562);
    let n564: ZB = zn_tile_flag_at(g.cache, g.cart, n563, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n578: ZB = zb_not(n564);
    let n579: ZB = zsel_b(n559, n561, n559);
    let n582: ZB = zsel_b(n579, n578, n579);
    let n585: ZB = zsel_b(n579, n564, n579);
    let n587: ZN = zn_add(n263, n547);
    let n588: ZN = zsel_n(n582, n587, n547);
    let n591: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n556);
    let n592: ZN = zsel_n(n585, zn_splat(P8::from_raw(0i32)), n551);
    let n595: ZI = zsel_i(n585, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n554);
    let n597: ZN = zsel_n(n582, n591, n556);
    let n599: ZB = zb_not(n585);
    let n600: ZB = zb_and(n559, n599);
    let n602: ZB = zn_le(n597, n266);
    let n603: ZN = zn_add(zn_splat(u.c402), n588);
    let n604: ZN = zn_add(n263, n603);
    let n605: ZB = zn_tile_flag_at(g.cache, g.cart, n604, n274, u.c401, u.c400, P8::from_raw(0i32));
    let n619: ZB = zb_not(n605);
    let n620: ZB = zsel_b(n600, n602, n600);
    let n623: ZB = zsel_b(n620, n619, n620);
    let n626: ZB = zsel_b(n620, n605, n620);
    let n628: ZN = zn_add(n263, n588);
    let n629: ZN = zsel_n(n623, n628, n588);
    let n632: ZN = zsel_n(n626, zn_splat(P8::from_raw(0i32)), n592);
    let n635: ZI = zsel_i(n626, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n595);
    let n667: ZN = zn_add(zn_splat(u.c402), n629);
    let n668: ZN = zn_add(zn_splat(P8::from_raw(0i32)), n667);
    let n1447: ZN = zn_abs(n632);
    let n1448: ZB = zn_gt(n1447, zn_splat(P8::from_raw(65536i32)));
    let n1449: ZB = zn_gt(n632, zn_splat(P8::from_raw(0i32)));
    let n1451: ZN = zsel_n(n1449, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n1452: ZB = zn_lt(n632, zn_splat(P8::from_raw(0i32)));
    let n1453: ZB = zsel_b(n1449, n1449, n1452);
    let n1454: ZN = zsel_n(n1449, n1451, zn_splat(P8::from_raw(-65536i32)));
    let n1455: ZN = zsel_n(n1453, n1454, zn_splat(P8::from_raw(0i32)));
    let n1457: ZN = zn_mul(n1455, zn_splat(P8::from_raw(65536i32)));
    let n1458: ZB = zn_gt(n632, n1457);
    let n1460: ZN = zn_sub(n632, zn_splat(P8::from_raw(9830i32)));
    let n1461: ZN = zn_max(n1457, n1460);
    let n1462: ZN = zn_add(n632, zn_splat(P8::from_raw(9830i32)));
    let n1463: ZN = zn_min(n1457, n1462);
    let n1464: ZN = zsel_n(n1458, n1461, n1463);
    for c1 in 0..2usize {
    let (f1, f1_fv): (ZI, u16) = zi_fork_flr(n639, c1);
    let valid1: u16 = valid0 & f1_fv;
    if valid1 == 0 { continue; }
    let n645: ZN = zi_flr(f1);
    let n648: ZI = zi_sub(f1, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n649: ZI = zi_sub(n648, zi_of_zn(n645));
    let n650: ZB = zn_gt(n645, zn_splat(P8::from_raw(0i32)));
    let n651: ZB = zn_lt(n645, zn_splat(P8::from_raw(0i32)));
    let n652: ZB = zsel_b(n650, n650, n651);
    let n655: ZN = zsel_n(n650, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)));
    let n657: ZN = zsel_n(n652, n655, zn_splat(P8::from_raw(0i32)));
    let n660: ZN = zn_abs(n645);
    let n665: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n660);
    let n666: ZB = zn_gt(n657, zn_splat(P8::from_raw(0i32)));
    let n681: ZN = zn_add(n85, n657);
    let n691: ZB = zn_le(n657, zn_splat(P8::from_raw(0i32)));
    let n692: ZB = zb_and(n666, n691);
    let n694: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n681, u.c401, u.c400, P8::from_raw(0i32));
    let n698: ZB = zb_or(n692, n694);
    let n701: ZB = zb_not(n698);
    let n702: ZB = zsel_b(n665, n701, n665);
    let n705: ZB = zsel_b(n665, n698, n665);
    let n707: ZN = zn_add(r_c317, n657);
    let n708: ZN = zsel_n(n702, n707, r_c317);
    let n711: ZN = zsel_n(n705, zn_splat(P8::from_raw(0i32)), r_c407);
    let n714: ZI = zsel_i(n705, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n649);
    let n716: ZN = zsel_n(n702, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)));
    let n718: ZB = zb_not(n705);
    let n720: ZB = zn_le(n716, n660);
    let n721: ZN = zn_add(zn_splat(u.c403), n708);
    let n733: ZN = zn_add(n657, n721);
    let n743: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n733, u.c401, u.c400, P8::from_raw(0i32));
    let n747: ZB = zb_or(n692, n743);
    let n749: ZB = zb_not(n747);
    let n750: ZB = zsel_b(n718, n720, n718);
    let n752: ZB = zsel_b(n750, n749, n750);
    let n755: ZB = zsel_b(n750, n747, n750);
    let n757: ZN = zn_add(n657, n708);
    let n758: ZN = zsel_n(n752, n757, n708);
    let n761: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n716);
    let n762: ZN = zsel_n(n755, zn_splat(P8::from_raw(0i32)), n711);
    let n765: ZI = zsel_i(n755, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n714);
    let n767: ZN = zsel_n(n752, n761, n716);
    let n769: ZB = zb_not(n755);
    let n770: ZB = zb_and(n718, n769);
    let n772: ZB = zn_le(n767, n660);
    let n773: ZN = zn_add(zn_splat(u.c403), n758);
    let n785: ZN = zn_add(n657, n773);
    let n795: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n785, u.c401, u.c400, P8::from_raw(0i32));
    let n799: ZB = zb_or(n692, n795);
    let n801: ZB = zb_not(n799);
    let n802: ZB = zsel_b(n770, n772, n770);
    let n805: ZB = zsel_b(n802, n801, n802);
    let n808: ZB = zsel_b(n802, n799, n802);
    let n810: ZN = zn_add(n657, n758);
    let n811: ZN = zsel_n(n805, n810, n758);
    let n814: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n767);
    let n815: ZN = zsel_n(n808, zn_splat(P8::from_raw(0i32)), n762);
    let n818: ZI = zsel_i(n808, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n765);
    let n820: ZN = zsel_n(n805, n814, n767);
    let n822: ZB = zb_not(n808);
    let n823: ZB = zb_and(n770, n822);
    let n825: ZB = zn_le(n820, n660);
    let n826: ZN = zn_add(zn_splat(u.c403), n811);
    let n838: ZN = zn_add(n657, n826);
    let n848: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n838, u.c401, u.c400, P8::from_raw(0i32));
    let n852: ZB = zb_or(n692, n848);
    let n854: ZB = zb_not(n852);
    let n855: ZB = zsel_b(n823, n825, n823);
    let n858: ZB = zsel_b(n855, n854, n855);
    let n861: ZB = zsel_b(n855, n852, n855);
    let n863: ZN = zn_add(n657, n811);
    let n864: ZN = zsel_n(n858, n863, n811);
    let n867: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n820);
    let n868: ZN = zsel_n(n861, zn_splat(P8::from_raw(0i32)), n815);
    let n871: ZI = zsel_i(n861, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n818);
    let n873: ZN = zsel_n(n858, n867, n820);
    let n875: ZB = zb_not(n861);
    let n876: ZB = zb_and(n823, n875);
    let n878: ZB = zn_le(n873, n660);
    let n879: ZN = zn_add(zn_splat(u.c403), n864);
    let n891: ZN = zn_add(n657, n879);
    let n901: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n891, u.c401, u.c400, P8::from_raw(0i32));
    let n905: ZB = zb_or(n692, n901);
    let n907: ZB = zb_not(n905);
    let n908: ZB = zsel_b(n876, n878, n876);
    let n911: ZB = zsel_b(n908, n907, n908);
    let n914: ZB = zsel_b(n908, n905, n908);
    let n916: ZN = zn_add(n657, n864);
    let n917: ZN = zsel_n(n911, n916, n864);
    let n920: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n873);
    let n921: ZN = zsel_n(n914, zn_splat(P8::from_raw(0i32)), n868);
    let n924: ZI = zsel_i(n914, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n871);
    let n926: ZN = zsel_n(n911, n920, n873);
    let n928: ZB = zb_not(n914);
    let n929: ZB = zb_and(n876, n928);
    let n931: ZB = zn_le(n926, n660);
    let n932: ZN = zn_add(zn_splat(u.c403), n917);
    let n944: ZN = zn_add(n657, n932);
    let n954: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n944, u.c401, u.c400, P8::from_raw(0i32));
    let n958: ZB = zb_or(n692, n954);
    let n960: ZB = zb_not(n958);
    let n961: ZB = zsel_b(n929, n931, n929);
    let n964: ZB = zsel_b(n961, n960, n961);
    let n967: ZB = zsel_b(n961, n958, n961);
    let n969: ZN = zn_add(n657, n917);
    let n970: ZN = zsel_n(n964, n969, n917);
    let n973: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n926);
    let n974: ZN = zsel_n(n967, zn_splat(P8::from_raw(0i32)), n921);
    let n977: ZI = zsel_i(n967, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n924);
    let n979: ZN = zsel_n(n964, n973, n926);
    let n981: ZB = zb_not(n967);
    let n982: ZB = zb_and(n929, n981);
    let n984: ZB = zn_le(n979, n660);
    let n985: ZN = zn_add(zn_splat(u.c403), n970);
    let n997: ZN = zn_add(n657, n985);
    let n1007: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n997, u.c401, u.c400, P8::from_raw(0i32));
    let n1011: ZB = zb_or(n692, n1007);
    let n1013: ZB = zb_not(n1011);
    let n1014: ZB = zsel_b(n982, n984, n982);
    let n1017: ZB = zsel_b(n1014, n1013, n1014);
    let n1020: ZB = zsel_b(n1014, n1011, n1014);
    let n1022: ZN = zn_add(n657, n970);
    let n1023: ZN = zsel_n(n1017, n1022, n970);
    let n1026: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n979);
    let n1027: ZN = zsel_n(n1020, zn_splat(P8::from_raw(0i32)), n974);
    let n1030: ZI = zsel_i(n1020, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n977);
    let n1032: ZN = zsel_n(n1017, n1026, n979);
    let n1034: ZB = zb_not(n1020);
    let n1035: ZB = zb_and(n982, n1034);
    let n1037: ZB = zn_le(n1032, n660);
    let n1038: ZN = zn_add(zn_splat(u.c403), n1023);
    let n1050: ZN = zn_add(n657, n1038);
    let n1060: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n1050, u.c401, u.c400, P8::from_raw(0i32));
    let n1064: ZB = zb_or(n692, n1060);
    let n1066: ZB = zb_not(n1064);
    let n1067: ZB = zsel_b(n1035, n1037, n1035);
    let n1070: ZB = zsel_b(n1067, n1066, n1067);
    let n1073: ZB = zsel_b(n1067, n1064, n1067);
    let n1075: ZN = zn_add(n657, n1023);
    let n1076: ZN = zsel_n(n1070, n1075, n1023);
    let n1079: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n1032);
    let n1080: ZN = zsel_n(n1073, zn_splat(P8::from_raw(0i32)), n1027);
    let n1083: ZI = zsel_i(n1073, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1030);
    let n1085: ZN = zsel_n(n1070, n1079, n1032);
    let n1087: ZB = zb_not(n1073);
    let n1088: ZB = zb_and(n1035, n1087);
    let n1090: ZB = zn_le(n1085, n660);
    let n1091: ZN = zn_add(zn_splat(u.c403), n1076);
    let n1103: ZN = zn_add(n657, n1091);
    let n1113: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n1103, u.c401, u.c400, P8::from_raw(0i32));
    let n1117: ZB = zb_or(n692, n1113);
    let n1119: ZB = zb_not(n1117);
    let n1120: ZB = zsel_b(n1088, n1090, n1088);
    let n1123: ZB = zsel_b(n1120, n1119, n1120);
    let n1126: ZB = zsel_b(n1120, n1117, n1120);
    let n1128: ZN = zn_add(n657, n1076);
    let n1129: ZN = zsel_n(n1123, n1128, n1076);
    let n1132: ZN = zsel_n(n1126, zn_splat(P8::from_raw(0i32)), n1080);
    let n1135: ZI = zsel_i(n1126, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1083);
    let n1151: ZN = zn_add(zn_splat(u.c403), n1129);
    let n1404: ZN = zn_add(zn_splat(P8::from_raw(65536i32)), n1151);
    let n1412: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n1404, u.c401, u.c400, P8::from_raw(0i32));
    let n1415: ZB = zn_tile_flag_at(g.cache, g.cart, n668, n1404, u.c401, u.c400, P8::from_raw(262144i32));
    let n1433: ZN = zsel_n(n1412, zn_splat(P8::from_raw(393216i32)), n1431);
    let n1434: ZN = zsel_n(n1412, zn_splat(n1427), zn_splat(u.c300));
    let n1440: ZB = zb_not(n1412);
    let n1443: ZN = zsel_n(n1415, zn_splat(P8::from_raw(3276i32)), zn_splat(P8::from_raw(39321i32)));
    let n1446: ZN = zsel_n(n1440, zn_splat(P8::from_raw(26214i32)), n1443);
    let n1466: ZN = zn_sub(n632, n1446);
    let n1467: ZN = zn_max(zn_splat(P8::from_raw(0i32)), n1466);
    let n1468: ZN = zn_add(n632, n1446);
    let n1469: ZN = zn_min(zn_splat(P8::from_raw(0i32)), n1468);
    let n1470: ZN = zsel_n(n1449, n1467, n1469);
    let n1471: ZN = zsel_n(n1448, n1464, n1470);
    let n1473: ZB = zn_eq(zn_splat(P8::from_raw(0i32)), n1471);
    let n1474: ZB = zb_not(n1473);
    let n1475: ZB = zn_lt(n1471, zn_splat(P8::from_raw(0i32)));
    let n1477: ZB = zsel_b(n1474, n1475, r_c398);
    let n1479: ZN = zn_abs(n1132);
    let n1480: ZB = zn_le(n1479, zn_splat(P8::from_raw(9830i32)));
    let n1483: ZN = zsel_n(n1480, zn_splat(P8::from_raw(6881i32)), zn_splat(P8::from_raw(13762i32)));
    let n1487: ZB = zn_gt(n1132, zn_splat(P8::from_raw(131072i32)));
    let n1488: ZN = zn_sub(n1132, n1483);
    let n1489: ZN = zn_max(zn_splat(P8::from_raw(131072i32)), n1488);
    let n1490: ZN = zn_add(n1132, n1483);
    let n1491: ZN = zn_min(zn_splat(P8::from_raw(131072i32)), n1490);
    let n1492: ZN = zsel_n(n1487, n1489, n1491);
    let n1494: ZN = zsel_n(n1440, n1492, n1132);
    let ok_v0: u16 = ALL;
    let bd_v0: bool = true;
    let osh = KOutShared {
        c38: true,
        c39: P8::from_raw(983040i32),
        c84: n6,
        c87: n1395,
        c246: n105,
        c254: n116,
        c297: n1436,
        c300: n1434,
        c302: n1433,
        c309: false,
        c310: false,
        c316: n629,
        c317: n1129,
        c398: n1477,
        c404: n635,
        c405: n1135,
        c406: n1471,
        c407: n1494,
    };
    // 1 of 64 free assignments are distinct successors
    out(0, &osh, &KOut {
        valid: valid1,
        deopt: !ok_v0,
        bd: bd_v0,
    });
    }
    }
}
