// GENERATED by `transpile --kernel` (plans/kernel-plan.md). Do not edit.
//
// The STEADY-CLASS lane kernel: shape (player), pm1 freeze=0 dash_time=0.
// Shared prefix per 16-row slice, 64 monomorphized button suffixes.
#![allow(unused_variables, unused_mut, unused_imports, clippy::all)]
use celeste_engine::kernel::*;
use celeste_core::pico8_num::{Pico8Num as P8, Pico8NumInterval as IV};
use celeste_core::cart_data::CartData;
use celeste_core::collision_cache::CollisionCache;

pub const SHAPE_HASH: u64 = 0xa9e20c0af79aea86;
pub struct G<'a> { pub cart: &'a CartData, pub cache: &'a CollisionCache }

/// Block-uniform inputs, bound per block (kind-checked).
pub struct Uni {
    pub c20: P8,
    pub c38: bool,
    pub c39: P8,
    pub c41: bool,
    pub c42: bool,
    pub c43: bool,
    pub c44: P8,
    pub c45: P8,
    pub c46: P8,
    pub c47: P8,
    pub c48: P8,
    pub c49: P8,
    pub c84: P8,
    pub c85: P8,
    pub c86: P8,
    pub c87: P8,
    pub c88: P8,
    pub c159: P8,
    pub c161: P8,
    pub c162: P8,
    pub c174: P8,
    pub c177: P8,
    pub c180: P8,
    pub c182: bool,
    pub c184: P8,
    pub c186: bool,
    pub c188: P8,
    pub c190: bool,
    pub c191: P8,
    pub c193: bool,
    pub c194: P8,
    pub c196: bool,
    pub c198: P8,
    pub c204: P8,
    pub c238: bool,
    pub c246: (P8, P8),
    pub c248: bool,
    pub c250: P8,
    pub c251: P8,
    pub c253: P8,
    pub c254: (P8, P8),
    pub c257: bool,
    pub c259: P8,
    pub c260: P8,
    pub c268: bool,
    pub c270: P8,
    pub c272: P8,
    pub c273: P8,
    pub c276: bool,
    pub c278: P8,
    pub c279: P8,
    pub c287: bool,
    pub c289: P8,
    pub c291: P8,
    pub c292: P8,
    pub c295: bool,
    pub c299: P8,
    pub c300: P8,
    pub c309: bool,
    pub c310: bool,
    pub c312: bool,
    pub c364: bool,
    pub c365: bool,
    pub c366: P8,
    pub c367: P8,
    pub c368: P8,
    pub c369: P8,
    pub c370: P8,
    pub c371: P8,
    pub c372: P8,
    pub c373: P8,
    pub c374: bool,
    pub c375: bool,
    pub c376: P8,
    pub c377: P8,
    pub c378: P8,
    pub c379: P8,
    pub c380: P8,
    pub c381: P8,
    pub c382: P8,
    pub c383: P8,
    pub c384: bool,
    pub c385: bool,
    pub c386: P8,
    pub c387: P8,
    pub c388: P8,
    pub c389: P8,
    pub c390: P8,
    pub c391: P8,
    pub c392: P8,
    pub c393: P8,
    pub c399: bool,
    pub c400: P8,
    pub c401: P8,
    pub c402: P8,
    pub c403: P8,
    pub c404: (P8, P8),
    pub c405: (P8, P8),
}

pub const UNI_CELLS: &[(u32, &str)] = &[
    (20, "num"),
    (38, "bool"),
    (39, "num"),
    (41, "bool"),
    (42, "bool"),
    (43, "bool"),
    (44, "num"),
    (45, "num"),
    (46, "num"),
    (47, "num"),
    (48, "num"),
    (49, "num"),
    (84, "num"),
    (85, "num"),
    (86, "num"),
    (87, "num"),
    (88, "num"),
    (159, "num"),
    (161, "num"),
    (162, "num"),
    (174, "num"),
    (177, "num"),
    (180, "num"),
    (182, "bool"),
    (184, "num"),
    (186, "bool"),
    (188, "num"),
    (190, "bool"),
    (191, "num"),
    (193, "bool"),
    (194, "num"),
    (196, "bool"),
    (198, "num"),
    (204, "num"),
    (238, "bool"),
    (246, "ival"),
    (248, "bool"),
    (250, "num"),
    (251, "num"),
    (253, "num"),
    (254, "ival"),
    (257, "bool"),
    (259, "num"),
    (260, "num"),
    (268, "bool"),
    (270, "num"),
    (272, "num"),
    (273, "num"),
    (276, "bool"),
    (278, "num"),
    (279, "num"),
    (287, "bool"),
    (289, "num"),
    (291, "num"),
    (292, "num"),
    (295, "bool"),
    (299, "num"),
    (300, "num"),
    (309, "bool"),
    (310, "bool"),
    (312, "bool"),
    (364, "bool"),
    (365, "bool"),
    (366, "num"),
    (367, "num"),
    (368, "num"),
    (369, "num"),
    (370, "num"),
    (371, "num"),
    (372, "num"),
    (373, "num"),
    (374, "bool"),
    (375, "bool"),
    (376, "num"),
    (377, "num"),
    (378, "num"),
    (379, "num"),
    (380, "num"),
    (381, "num"),
    (382, "num"),
    (383, "num"),
    (384, "bool"),
    (385, "bool"),
    (386, "num"),
    (387, "num"),
    (388, "num"),
    (389, "num"),
    (390, "num"),
    (391, "num"),
    (392, "num"),
    (393, "num"),
    (399, "bool"),
    (400, "num"),
    (401, "num"),
    (402, "num"),
    (403, "num"),
    (404, "ival"),
    (405, "ival"),
];

/// Folds consumed these uniform cells' witness values; bind must
/// guard them (raw bits) or send the block to the interpreter.
pub const PIN_CELLS: &[(u32, i32)] = &[
    (44, 0i32),
    (45, 65536i32),
    (48, 262144i32),
    (49, 327680i32),
];

/// Per-lane inputs: 16 rows per slice.
pub struct RowsIn {
    pub c297: ZN,
    pub c302: ZN,
    pub c316: ZN,
    pub c317: ZN,
    pub c394: ZN,
    pub c395: ZN,
    pub c396: ZN,
    pub c397: ZN,
    pub c398: u16,
    pub c406: ZN,
    pub c407: ZN,
}

pub const VARY_CELLS: &[(u32, &str)] = &[
    (297, "num"),
    (302, "num"),
    (316, "num"),
    (317, "num"),
    (394, "num"),
    (395, "num"),
    (396, "num"),
    (397, "num"),
    (398, "bool"),
    (406, "num"),
    (407, "num"),
];

/// Button-independent outputs: one per fork config.
pub struct KOutShared {
    pub c84: P8,
    pub c85: P8,
    pub c246: (P8, P8),
    pub c254: (P8, P8),
    pub c297: ZN,
    pub c299: P8,
    pub c300: ZN,
    pub c302: ZN,
    pub c316: ZN,
    pub c317: ZN,
    pub c404: ZI,
    pub c405: ZI,
    pub c406: ZN,
    pub c407: ZN,
}

/// Button-dependent outputs: one per (config, variant).
pub struct KOut {
    /// Lanes that EXIST in this fork configuration.
    pub valid: u16,
    pub deopt: u16,
    pub bd: bool,
    pub c309: bool,
    pub c310: bool,
}

pub const OUT_CELLS: &[u32] = &[
    84,
    85,
    246,
    254,
    297,
    299,
    300,
    302,
    309,
    310,
    316,
    317,
    404,
    405,
    406,
    407,
];

/// Cells that end every frame as a fresh UnknownBool (the next
/// frame's button inputs); the boundary writes UBool, no data.
pub const OUT_UBOOL_CELLS: &[u32] = &[
    145,
    146,
    147,
    148,
    149,
    150,
];

use celeste_engine::runtime2::{Rt2, Col, AV};

/// Bind the block-uniform inputs. None = off-shape / off-kind /
/// pin mismatch: the block takes the reference path.
pub fn bind(b: &Rt2) -> Option<Uni> {
    if b.shape_hash != SHAPE_HASH { return None; }
    for (cell, pin) in PIN_CELLS {
        match &b.cols[*cell as usize] {
            Col::U(AV::Num(n)) if n.as_raw_u32() as i32 == *pin => {}
            _ => return None,
        }
    }
    Some(Uni {
        c20: match &b.cols[20] { Col::U(AV::Num(n)) => *n, _ => return None },
        c38: match &b.cols[38] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c39: match &b.cols[39] { Col::U(AV::Num(n)) => *n, _ => return None },
        c41: match &b.cols[41] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c42: match &b.cols[42] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c43: match &b.cols[43] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c44: match &b.cols[44] { Col::U(AV::Num(n)) => *n, _ => return None },
        c45: match &b.cols[45] { Col::U(AV::Num(n)) => *n, _ => return None },
        c46: match &b.cols[46] { Col::U(AV::Num(n)) => *n, _ => return None },
        c47: match &b.cols[47] { Col::U(AV::Num(n)) => *n, _ => return None },
        c48: match &b.cols[48] { Col::U(AV::Num(n)) => *n, _ => return None },
        c49: match &b.cols[49] { Col::U(AV::Num(n)) => *n, _ => return None },
        c84: match &b.cols[84] { Col::U(AV::Num(n)) => *n, _ => return None },
        c85: match &b.cols[85] { Col::U(AV::Num(n)) => *n, _ => return None },
        c86: match &b.cols[86] { Col::U(AV::Num(n)) => *n, _ => return None },
        c87: match &b.cols[87] { Col::U(AV::Num(n)) => *n, _ => return None },
        c88: match &b.cols[88] { Col::U(AV::Num(n)) => *n, _ => return None },
        c159: match &b.cols[159] { Col::U(AV::Num(n)) => *n, _ => return None },
        c161: match &b.cols[161] { Col::U(AV::Num(n)) => *n, _ => return None },
        c162: match &b.cols[162] { Col::U(AV::Num(n)) => *n, _ => return None },
        c174: match &b.cols[174] { Col::U(AV::Num(n)) => *n, _ => return None },
        c177: match &b.cols[177] { Col::U(AV::Num(n)) => *n, _ => return None },
        c180: match &b.cols[180] { Col::U(AV::Num(n)) => *n, _ => return None },
        c182: match &b.cols[182] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c184: match &b.cols[184] { Col::U(AV::Num(n)) => *n, _ => return None },
        c186: match &b.cols[186] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c188: match &b.cols[188] { Col::U(AV::Num(n)) => *n, _ => return None },
        c190: match &b.cols[190] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c191: match &b.cols[191] { Col::U(AV::Num(n)) => *n, _ => return None },
        c193: match &b.cols[193] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c194: match &b.cols[194] { Col::U(AV::Num(n)) => *n, _ => return None },
        c196: match &b.cols[196] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c198: match &b.cols[198] { Col::U(AV::Num(n)) => *n, _ => return None },
        c204: match &b.cols[204] { Col::U(AV::Num(n)) => *n, _ => return None },
        c238: match &b.cols[238] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c246: match &b.cols[246] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c248: match &b.cols[248] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c250: match &b.cols[250] { Col::U(AV::Num(n)) => *n, _ => return None },
        c251: match &b.cols[251] { Col::U(AV::Num(n)) => *n, _ => return None },
        c253: match &b.cols[253] { Col::U(AV::Num(n)) => *n, _ => return None },
        c254: match &b.cols[254] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c257: match &b.cols[257] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c259: match &b.cols[259] { Col::U(AV::Num(n)) => *n, _ => return None },
        c260: match &b.cols[260] { Col::U(AV::Num(n)) => *n, _ => return None },
        c268: match &b.cols[268] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c270: match &b.cols[270] { Col::U(AV::Num(n)) => *n, _ => return None },
        c272: match &b.cols[272] { Col::U(AV::Num(n)) => *n, _ => return None },
        c273: match &b.cols[273] { Col::U(AV::Num(n)) => *n, _ => return None },
        c276: match &b.cols[276] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c278: match &b.cols[278] { Col::U(AV::Num(n)) => *n, _ => return None },
        c279: match &b.cols[279] { Col::U(AV::Num(n)) => *n, _ => return None },
        c287: match &b.cols[287] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c289: match &b.cols[289] { Col::U(AV::Num(n)) => *n, _ => return None },
        c291: match &b.cols[291] { Col::U(AV::Num(n)) => *n, _ => return None },
        c292: match &b.cols[292] { Col::U(AV::Num(n)) => *n, _ => return None },
        c295: match &b.cols[295] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c299: match &b.cols[299] { Col::U(AV::Num(n)) => *n, _ => return None },
        c300: match &b.cols[300] { Col::U(AV::Num(n)) => *n, _ => return None },
        c309: match &b.cols[309] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c310: match &b.cols[310] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c312: match &b.cols[312] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c364: match &b.cols[364] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c365: match &b.cols[365] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c366: match &b.cols[366] { Col::U(AV::Num(n)) => *n, _ => return None },
        c367: match &b.cols[367] { Col::U(AV::Num(n)) => *n, _ => return None },
        c368: match &b.cols[368] { Col::U(AV::Num(n)) => *n, _ => return None },
        c369: match &b.cols[369] { Col::U(AV::Num(n)) => *n, _ => return None },
        c370: match &b.cols[370] { Col::U(AV::Num(n)) => *n, _ => return None },
        c371: match &b.cols[371] { Col::U(AV::Num(n)) => *n, _ => return None },
        c372: match &b.cols[372] { Col::U(AV::Num(n)) => *n, _ => return None },
        c373: match &b.cols[373] { Col::U(AV::Num(n)) => *n, _ => return None },
        c374: match &b.cols[374] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c375: match &b.cols[375] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c376: match &b.cols[376] { Col::U(AV::Num(n)) => *n, _ => return None },
        c377: match &b.cols[377] { Col::U(AV::Num(n)) => *n, _ => return None },
        c378: match &b.cols[378] { Col::U(AV::Num(n)) => *n, _ => return None },
        c379: match &b.cols[379] { Col::U(AV::Num(n)) => *n, _ => return None },
        c380: match &b.cols[380] { Col::U(AV::Num(n)) => *n, _ => return None },
        c381: match &b.cols[381] { Col::U(AV::Num(n)) => *n, _ => return None },
        c382: match &b.cols[382] { Col::U(AV::Num(n)) => *n, _ => return None },
        c383: match &b.cols[383] { Col::U(AV::Num(n)) => *n, _ => return None },
        c384: match &b.cols[384] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c385: match &b.cols[385] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c386: match &b.cols[386] { Col::U(AV::Num(n)) => *n, _ => return None },
        c387: match &b.cols[387] { Col::U(AV::Num(n)) => *n, _ => return None },
        c388: match &b.cols[388] { Col::U(AV::Num(n)) => *n, _ => return None },
        c389: match &b.cols[389] { Col::U(AV::Num(n)) => *n, _ => return None },
        c390: match &b.cols[390] { Col::U(AV::Num(n)) => *n, _ => return None },
        c391: match &b.cols[391] { Col::U(AV::Num(n)) => *n, _ => return None },
        c392: match &b.cols[392] { Col::U(AV::Num(n)) => *n, _ => return None },
        c393: match &b.cols[393] { Col::U(AV::Num(n)) => *n, _ => return None },
        c399: match &b.cols[399] { Col::U(AV::Bool(v)) => *v, _ => return None },
        c400: match &b.cols[400] { Col::U(AV::Num(n)) => *n, _ => return None },
        c401: match &b.cols[401] { Col::U(AV::Num(n)) => *n, _ => return None },
        c402: match &b.cols[402] { Col::U(AV::Num(n)) => *n, _ => return None },
        c403: match &b.cols[403] { Col::U(AV::Num(n)) => *n, _ => return None },
        c404: match &b.cols[404] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
        c405: match &b.cols[405] { Col::U(AV::Ival(a, b)) => (*a, *b), _ => return None },
    })
}

/// Gather rows [lo, lo+16) into lane arrays; short slices pad by
/// repeating the last row (padded outputs are ignored by width).
pub fn rows(b: &Rt2, lo: usize) -> Option<RowsIn> {
    let at = |i: usize| -> usize { (lo + i).min(b.width - 1) };
    Some(RowsIn {
        c297: match &b.cols[297] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c302: match &b.cols[302] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c316: match &b.cols[316] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c317: match &b.cols[317] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c394: match &b.cols[394] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c395: match &b.cols[395] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c396: match &b.cols[396] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c397: match &b.cols[397] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c398: match &b.cols[398] {
            Col::V(v) => {
                let mut m = 0u16;
                for i in 0..W { if matches!(v[at(i)], AV::Bool(true)) { m |= 1 << i; } else if !matches!(v[at(i)], AV::Bool(false)) { return None; } }
                m
            }
            Col::U(AV::Bool(t)) => if *t { 0xffff } else { 0 },
            _ => return None,
        },
        c406: match &b.cols[406] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
        c407: match &b.cols[407] {
            Col::N(v) => core::array::from_fn(|i| v[at(i)]),
            Col::U(AV::Num(n)) => [*n; W],
            _ => return None,
        },
    })
}

/// Write one (config, variant) result onto a width-`n` sliced block
/// (the block already carries the input row values).
pub fn apply(sh: &KOutShared, kv: &KOut, b: &mut Rt2, n: usize) {
    b.cols[84] = Col::U(AV::Num(sh.c84));
    b.cols[85] = Col::U(AV::Num(sh.c85));
    b.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
    b.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
    b.cols[297] = Col::N(sh.c297[..n].to_vec());
    b.cols[299] = Col::U(AV::Num(sh.c299));
    b.cols[300] = Col::N(sh.c300[..n].to_vec());
    b.cols[302] = Col::N(sh.c302[..n].to_vec());
    b.cols[309] = Col::U(AV::Bool(kv.c309));
    b.cols[310] = Col::U(AV::Bool(kv.c310));
    b.cols[316] = Col::N(sh.c316[..n].to_vec());
    b.cols[317] = Col::N(sh.c317[..n].to_vec());
    b.cols[404] = Col::I((0..n).map(|i| (sh.c404.lo[i], sh.c404.hi[i])).collect());
    b.cols[405] = Col::I((0..n).map(|i| (sh.c405.lo[i], sh.c405.hi[i])).collect());
    b.cols[406] = Col::N(sh.c406[..n].to_vec());
    b.cols[407] = Col::N(sh.c407[..n].to_vec());
    for cell in OUT_UBOOL_CELLS {
        b.cols[*cell as usize] = Col::U(AV::UBool);
    }
}

/// One wide output block per chunk: structure + uniforms cloned
/// once, varying/output columns start empty and grow by appends.
pub fn acc_init(chunk: &Rt2) -> Rt2 {
    let mut acc = Rt2::empty(0, chunk.globals.len(), &[], chunk.cart.clone(), chunk.cache.clone());
    acc.strings = chunk.strings.clone();
    acc.globals = chunk.globals.clone();
    acc.structure = chunk.structure.clone();
    acc.cols = chunk.cols.clone();
    acc.shape_hash = chunk.shape_hash;
    acc.cols[297] = Col::N(Vec::new());
    acc.cols[300] = Col::N(Vec::new());
    acc.cols[302] = Col::N(Vec::new());
    acc.cols[309] = Col::V(Vec::new());
    acc.cols[310] = Col::V(Vec::new());
    acc.cols[316] = Col::N(Vec::new());
    acc.cols[317] = Col::N(Vec::new());
    acc.cols[404] = Col::I(Vec::new());
    acc.cols[405] = Col::I(Vec::new());
    acc.cols[406] = Col::N(Vec::new());
    acc.cols[407] = Col::N(Vec::new());
    acc.cols[394] = Col::N(Vec::new());
    acc.cols[395] = Col::N(Vec::new());
    acc.cols[396] = Col::N(Vec::new());
    acc.cols[397] = Col::N(Vec::new());
    acc.cols[398] = Col::V(Vec::new());
    for cell in OUT_UBOOL_CELLS {
        acc.cols[*cell as usize] = Col::U(AV::UBool);
    }
    acc
}

/// Append one (config, variant)'s live lanes onto the accumulator.
/// `lo` is the slice base in `chunk` (identity columns read there).
#[allow(unused_variables)]
pub fn append_out(acc: &mut Rt2, chunk: &Rt2, lo: usize, n: usize, live: u16, sh: &KOutShared, kv: &KOut, bd: &mut bool) {
    // fresh: no fork config has written yet, so a uniform slot
    // still holds the chunk's INPUT value (legitimately different).
    let fresh = acc.width == 0;
    for i in 0..n {
        if live & (1 << i) == 0 { continue; }
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[84] { if *prev != sh.c84 { *bd = true; } } }
        acc.cols[84] = Col::U(AV::Num(sh.c84));
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[85] { if *prev != sh.c85 { *bd = true; } } }
        acc.cols[85] = Col::U(AV::Num(sh.c85));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[246] { if (*a, *b) != sh.c246 { *bd = true; } } }
        acc.cols[246] = Col::U(AV::Ival(sh.c246.0, sh.c246.1));
        if !fresh { if let Col::U(AV::Ival(a, b)) = &acc.cols[254] { if (*a, *b) != sh.c254 { *bd = true; } } }
        acc.cols[254] = Col::U(AV::Ival(sh.c254.0, sh.c254.1));
        if let Col::N(v) = &mut acc.cols[297] { v.push(sh.c297[i]); }
        if !fresh { if let Col::U(AV::Num(prev)) = &acc.cols[299] { if *prev != sh.c299 { *bd = true; } } }
        acc.cols[299] = Col::U(AV::Num(sh.c299));
        if let Col::N(v) = &mut acc.cols[300] { v.push(sh.c300[i]); }
        if let Col::N(v) = &mut acc.cols[302] { v.push(sh.c302[i]); }
        if let Col::V(v) = &mut acc.cols[309] { v.push(AV::Bool(kv.c309)); }
        if let Col::V(v) = &mut acc.cols[310] { v.push(AV::Bool(kv.c310)); }
        if let Col::N(v) = &mut acc.cols[316] { v.push(sh.c316[i]); }
        if let Col::N(v) = &mut acc.cols[317] { v.push(sh.c317[i]); }
        if let Col::I(v) = &mut acc.cols[404] { v.push((sh.c404.lo[i], sh.c404.hi[i])); }
        if let Col::I(v) = &mut acc.cols[405] { v.push((sh.c405.lo[i], sh.c405.hi[i])); }
        if let Col::N(v) = &mut acc.cols[406] { v.push(sh.c406[i]); }
        if let Col::N(v) = &mut acc.cols[407] { v.push(sh.c407[i]); }
        let val = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[394] { v.push(val); }
        let val = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[395] { v.push(val); }
        let val = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[396] { v.push(val); }
        let val = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
        if let Col::N(v) = &mut acc.cols[397] { v.push(val); }
        let val = match &chunk.cols[398] { Col::V(s) => s[(lo + i).min(chunk.width - 1)], Col::U(a) => *a, _ => unreachable!() };
        if let Col::V(v) = &mut acc.cols[398] { v.push(val); }
        acc.width += 1;
    }
}

/// Cells the pre-dedup key covers, in key-bit order.
pub const KEY_CELLS: &[u32] = &[
    84,
    85,
    246,
    254,
    297,
    299,
    300,
    302,
    309,
    310,
    316,
    317,
    404,
    405,
    406,
    407,
    394,
    395,
    396,
    397,
    398,
];

#[allow(unused_variables)]
pub fn row_keys(chunk: &Rt2, lo: usize, n: usize, sh: &KOutShared, kv: &KOut, plan: &KeyPlan, keys: &mut [(u64, u64); W]) {
    let mut h1 = [0u64; W];
    let mut h2 = [0u64; W];
    // cell 84 (P8)
    if plan.rem & (1 << 0) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (84u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c84;
            let v = if plan.det & (1 << 0) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 85 (P8)
    if plan.rem & (1 << 1) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (85u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (85u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c85;
            let v = if plan.det & (1 << 1) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 246 ((P8, P8))
    if plan.rem & (1 << 2) == 0 {
        assert!(plan.det & (1 << 2) == 0, "det clamp on non-numeric cell 246");
        for i in 0..W {
            let v = AV::Ival(sh.c246.0, sh.c246.1);
            h1[i] = h1[i].wrapping_add(cell_mix(246u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(246u64, v, 0x27d4_eb2f));
        }
    }
    // cell 254 ((P8, P8))
    if plan.rem & (1 << 3) == 0 {
        assert!(plan.det & (1 << 3) == 0, "det clamp on non-numeric cell 254");
        for i in 0..W {
            let v = AV::Ival(sh.c254.0, sh.c254.1);
            h1[i] = h1[i].wrapping_add(cell_mix(254u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(254u64, v, 0x27d4_eb2f));
        }
    }
    // cell 297 (ZN)
    if plan.rem & (1 << 4) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (297u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c297[i];
            let v = if plan.det & (1 << 4) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 299 (P8)
    if plan.rem & (1 << 5) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (299u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (299u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c299;
            let v = if plan.det & (1 << 5) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 300 (ZN)
    if plan.rem & (1 << 6) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (300u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c300[i];
            let v = if plan.det & (1 << 6) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 302 (ZN)
    if plan.rem & (1 << 7) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (302u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c302[i];
            let v = if plan.det & (1 << 7) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 309 (bool)
    if plan.rem & (1 << 8) == 0 {
        assert!(plan.det & (1 << 8) == 0, "det clamp on non-numeric cell 309");
        for i in 0..W {
            let v = AV::Bool(kv.c309);
            h1[i] = h1[i].wrapping_add(cell_mix(309u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(309u64, v, 0x27d4_eb2f));
        }
    }
    // cell 310 (bool)
    if plan.rem & (1 << 9) == 0 {
        assert!(plan.det & (1 << 9) == 0, "det clamp on non-numeric cell 310");
        for i in 0..W {
            let v = AV::Bool(kv.c310);
            h1[i] = h1[i].wrapping_add(cell_mix(310u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(310u64, v, 0x27d4_eb2f));
        }
    }
    // cell 316 (ZN)
    if plan.rem & (1 << 10) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (316u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c316[i];
            let v = if plan.det & (1 << 10) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 317 (ZN)
    if plan.rem & (1 << 11) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (317u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c317[i];
            let v = if plan.det & (1 << 11) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 404 (ZI)
    if plan.rem & (1 << 12) == 0 {
        assert!(plan.det & (1 << 12) == 0, "det clamp on non-numeric cell 404");
        for i in 0..W {
            let v = AV::Ival(sh.c404.lo[i], sh.c404.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(404u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(404u64, v, 0x27d4_eb2f));
        }
    }
    // cell 405 (ZI)
    if plan.rem & (1 << 13) == 0 {
        assert!(plan.det & (1 << 13) == 0, "det clamp on non-numeric cell 405");
        for i in 0..W {
            let v = AV::Ival(sh.c405.lo[i], sh.c405.hi[i]);
            h1[i] = h1[i].wrapping_add(cell_mix(405u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(405u64, v, 0x27d4_eb2f));
        }
    }
    // cell 406 (ZN)
    if plan.rem & (1 << 14) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (406u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c406[i];
            let v = if plan.det & (1 << 14) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 407 (ZN)
    if plan.rem & (1 << 15) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (407u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = sh.c407[i];
            let v = if plan.det & (1 << 15) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 394 (IN_N)
    if plan.rem & (1 << 16) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (394u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[394] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 16) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 395 (IN_N)
    if plan.rem & (1 << 17) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (395u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[395] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 17) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 396 (IN_N)
    if plan.rem & (1 << 18) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (396u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[396] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 18) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 397 (IN_N)
    if plan.rem & (1 << 19) == 0 {
        let c1 = 0x5bf0_3635u64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        let c2 = 0x27d4_eb2fu64 ^ (397u64).wrapping_mul(0x9e37_79b9_7f4a_7c15);
        for i in 0..W {
            let v = match &chunk.cols[397] { Col::N(s) => s[(lo + i).min(chunk.width - 1)], Col::U(AV::Num(u)) => *u, _ => unreachable!() };
            let v = if plan.det & (1 << 19) != 0 && v < P8::from_raw(0i32) { P8::from_raw(0i32) } else { v };
            let code = 1u64 << 56 | v.to_bits() as u64;
            h1[i] = h1[i].wrapping_add(mix64(c1 ^ code));
            h2[i] = h2[i].wrapping_add(mix64(c2 ^ code));
        }
    }
    // cell 398 (IN_B)
    if plan.rem & (1 << 20) == 0 {
        assert!(plan.det & (1 << 20) == 0, "det clamp on non-numeric cell 398");
        for i in 0..W {
            let v = match &chunk.cols[398] { Col::V(s) => s[(lo + i).min(chunk.width - 1)], Col::U(a) => *a, _ => unreachable!() };
            h1[i] = h1[i].wrapping_add(cell_mix(398u64, v, 0x5bf0_3635));
            h2[i] = h2[i].wrapping_add(cell_mix(398u64, v, 0x27d4_eb2f));
        }
    }
    for i in 0..W {
        keys[i] = (mix64(h1[i]), mix64(h2[i]));
    }
}

pub struct Pre {
    valid: u16,
    dp: u16,
    bd: bool,
}

#[inline(never)]
pub fn frame(u: &Uni, rin: &RowsIn, g: &G, out: &mut impl FnMut(u8, &KOutShared, &KOut)) {
    let mut dp: u16 = 0;
    let mut bd_flag: bool = false;
    let bd: &mut bool = &mut bd_flag;
    let r_c297: ZN = rin.c297;
    let r_c302: ZN = rin.c302;
    let r_c316: ZN = rin.c316;
    let r_c317: ZN = rin.c317;
    let r_c394: ZN = rin.c394;
    let r_c395: ZN = rin.c395;
    let r_c396: ZN = rin.c396;
    let r_c397: ZN = rin.c397;
    let r_c398: ZB = ZB { val: rin.c398, known: ALL };
    let r_c406: ZN = rin.c406;
    let r_c407: ZN = rin.c407;
    let n9: P8 = u.c84 + P8::from_raw(65536i32);
    let n11: P8 = n9 % P8::from_raw(1966080i32);
    let n13: bool = n11 == P8::from_raw(0i32);
    let n16: P8 = u.c161 % P8::from_raw(524288i32);
    let n18: P8 = u.c162 * P8::from_raw(524288i32);
    let n19: P8 = n16 + n18;
    let n20: bool = n19 < P8::from_raw(1966080i32);
    let n21: bool = if n13 { n20 } else { n13 };
    let n23: P8 = u.c85 + P8::from_raw(65536i32);
    let n25: P8 = n23 % P8::from_raw(3932160i32);
    let n26: P8 = if n21 { n25 } else { u.c85 };
    let n27: bool = n26 == P8::from_raw(0i32);
    let n28: bool = !n27;
    let n29: bool = if n21 { n28 } else { true };
    let n31: bool = u.c20 > P8::from_raw(0i32);
    let n32: bool = !n31;
    let n35: bool = u.c39 > P8::from_raw(0i32);
    let n37: bool = if u.c38 { n35 } else { u.c38 };
    let n38: bool = !n37;
    let n41: bool = u.c372 == P8::from_raw(0i32);
    let n42: bool = !n41;
    let n44: bool = u.c373 == P8::from_raw(0i32);
    let n45: bool = !n44;
    let n46: bool = if n42 { n42 } else { n45 };
    let n47: bool = !n46;
    let n51: P8 = u.c253 + u.c368;
    let n53: P8 = n51 + u.c367;
    let n54: P8 = n51 + P8::from_raw(0i32);
    let n58: (P8, P8) = si_add(u.c254, (u.c369, u.c369));
    let n60: (P8, P8) = si_add(n58, (u.c366, u.c366));
    let n61: (P8, P8) = si_add(n58, (P8::from_raw(0i32), P8::from_raw(0i32)));
    let n63: P8 = n53 + P8::from_raw(0i32);
    let n65: (P8, P8) = si_add(n60, (P8::from_raw(0i32), P8::from_raw(0i32)));
    let n69: P8 = u.c272 + u.c378;
    let n71: P8 = n69 + u.c377;
    let n75: P8 = u.c273 + u.c379;
    let n77: P8 = n75 + u.c376;
    let n83: P8 = u.c291 + u.c388;
    let n85: P8 = n83 + u.c387;
    let n89: P8 = u.c292 + u.c389;
    let n91: P8 = n89 + u.c386;
    let n97: ZN = zn_add(r_c316, zn_splat(u.c402));
    let n99: ZN = zn_add(n97, zn_splat(u.c401));
    let n100: ZB = zn_gt(n99, zn_splat(n54));
    let n102: ZB = if u.c295 { n100 } else { zb_splat(u.c295) };
    let n105: ZN = zn_add(r_c317, zn_splat(u.c403));
    let n107: ZN = zn_add(n105, zn_splat(u.c400));
    let n108: ZB = zi_cmp(Cmp::Gt, zi_of_zn(n107), zi_splat(n61.0, n61.1));
    let n109: ZB = zsel_b(n102, n108, n102, &mut dp);
    let n112: ZB = zn_lt(n97, zn_splat(n63));
    let n113: ZB = zsel_b(n109, n112, n109, &mut dp);
    let n116: ZB = zi_cmp(Cmp::Lt, zi_of_zn(n105), zi_splat(n65.0, n65.1));
    let n117: ZB = zsel_b(n113, n116, n113, &mut dp);
    let n120: ZB = zb_not(n117);
    let n125: (P8, P8) = si_add(u.c246, (P8::from_raw(65536i32), P8::from_raw(65536i32)));
    let n127: bool = P8::from_raw(2621440i32) > P8::from_raw(0i32);
    let n132: bool = P8::from_raw(163840i32) > P8::from_raw(0i32);
    let n134: (P8, P8) = { let r = IV::new((P8::from_raw(-65536i32), P8::from_raw(65536i32)).0, (P8::from_raw(-65536i32), P8::from_raw(65536i32)).1).scale_positive(P8::from_raw(163840i32)); (r.low, r.high) };
    let n136: (P8, P8) = si_add((u.c251, u.c251), n134);
    let n138: bool = u.c382 == P8::from_raw(0i32);
    let n139: bool = !n138;
    let n141: bool = u.c383 == P8::from_raw(0i32);
    let n142: bool = !n141;
    let n143: bool = if n139 { n139 } else { n142 };
    let n144: bool = !n143;
    let n147: bool = u.c259 > P8::from_raw(0i32);
    let n148: bool = !n147;
    let n152: bool = u.c270 == P8::from_raw(1179648i32);
    let n154: P8 = n69 + P8::from_raw(0i32);
    let n158: P8 = n75 + P8::from_raw(0i32);
    let n160: P8 = n71 + P8::from_raw(0i32);
    let n162: P8 = n77 + P8::from_raw(0i32);
    let n172: ZB = zn_gt(n99, zn_splat(n154));
    let n173: ZB = if u.c295 { n172 } else { zb_splat(u.c295) };
    let n174: ZB = zn_gt(n107, zn_splat(n158));
    let n175: ZB = zsel_b(n173, n174, n173, &mut dp);
    let n178: ZB = zn_lt(n97, zn_splat(n160));
    let n179: ZB = zsel_b(n175, n178, n175, &mut dp);
    let n182: ZB = zn_lt(n105, zn_splat(n162));
    let n183: ZB = zsel_b(n179, n182, n179, &mut dp);
    let n186: ZB = zb_not(n183);
    let n191: bool = u.c260 > P8::from_raw(0i32);
    let n192: bool = !n191;
    let n195: bool = u.c392 == P8::from_raw(0i32);
    let n196: bool = !n195;
    let n198: bool = u.c393 == P8::from_raw(0i32);
    let n199: bool = !n198;
    let n200: bool = if n196 { n196 } else { n199 };
    let n201: bool = !n200;
    let n204: bool = u.c278 > P8::from_raw(0i32);
    let n205: bool = !n204;
    let n208: bool = u.c289 == P8::from_raw(1179648i32);
    let n210: P8 = n83 + P8::from_raw(0i32);
    let n212: P8 = n89 + P8::from_raw(0i32);
    let n214: P8 = n85 + P8::from_raw(0i32);
    let n216: P8 = n91 + P8::from_raw(0i32);
    let n226: ZB = zn_gt(n99, zn_splat(n210));
    let n227: ZB = if u.c295 { n226 } else { zb_splat(u.c295) };
    let n228: ZB = zn_gt(n107, zn_splat(n212));
    let n229: ZB = zsel_b(n227, n228, n227, &mut dp);
    let n232: ZB = zn_lt(n97, zn_splat(n214));
    let n233: ZB = zsel_b(n229, n232, n229, &mut dp);
    let n236: ZB = zn_lt(n105, zn_splat(n216));
    let n237: ZB = zsel_b(n233, n236, n233, &mut dp);
    let n240: ZB = zb_not(n237);
    let n245: bool = u.c279 > P8::from_raw(0i32);
    let n246: bool = !n245;
    let n249: ZB = zn_eq(r_c406, zn_splat(P8::from_raw(0i32)));
    let n250: ZB = zb_not(n249);
    let n252: ZB = zn_eq(r_c407, zn_splat(P8::from_raw(0i32)));
    let n253: ZB = zb_not(n252);
    let n254: ZB = zsel_b(n250, n250, n253, &mut dp);
    let n258: ZI = zi_add(zi_splat(u.c404.0, u.c404.1), zi_of_zn(r_c406));
    let n260: ZI = zi_add(n258, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n261: ZI = zsel_i(n254, n260, zi_splat(u.c404.0, u.c404.1), &mut dp);
    let n276: ZB = zsel_b(n254, zb_splat(u.c312), zb_splat(true), &mut dp);
    let n301: ZN = zn_add(n105, zn_splat(P8::from_raw(0i32)));
    let n303: ZB = zsel_b(n254, zb_splat(true), zb_splat(true), &mut dp);
    let n899: ZI = zi_add(zi_splat(u.c405.0, u.c405.1), zi_of_zn(r_c407));
    let n900: ZI = zi_add(n899, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n901: ZI = zsel_i(n254, n900, zi_splat(u.c405.0, u.c405.1), &mut dp);
    let n1778: bool = !u.c43;
    let n1781: bool = u.c45 >= P8::from_raw(0i32);
    let n1784: bool = u.c45 <= P8::from_raw(327680i32);
    let n1788: bool = u.c44 >= P8::from_raw(0i32);
    let n1790: bool = u.c44 <= P8::from_raw(327680i32);
    let n1830: P8 = u.c161 * P8::from_raw(1048576i32);
    let n1832: P8 = u.c162 * P8::from_raw(1048576i32);
    let n2147: bool = u.c48 >= P8::from_raw(0i32);
    let n2149: bool = u.c48 <= P8::from_raw(327680i32);
    let n2153: bool = u.c49 >= P8::from_raw(0i32);
    let n2155: bool = u.c49 <= P8::from_raw(327680i32);
    let n2160: bool = u.c300 < u.c88;
    let n2161: P8 = if n2160 { u.c88 } else { u.c300 };
    let n2163: ZB = zn_gt(r_c302, zn_splat(P8::from_raw(0i32)));
    let n2164: ZN = zn_sub(r_c302, zn_splat(P8::from_raw(65536i32)));
    let n2165: ZN = zsel_n(n2163, n2164, r_c302, &mut dp);
    let n2174: ZN = zn_sub(r_c297, zn_splat(P8::from_raw(65536i32)));
    let n2176: bool = u.c299 > P8::from_raw(0i32);
    let n2178: P8 = u.c299 - P8::from_raw(65536i32);
    let n2206: bool = n19 == P8::from_raw(2031616i32);
    let n2207: bool = !n2206;
    if !n29 { *bd = true; }
    if !n32 { *bd = true; }
    if !n38 { *bd = true; }
    if !n47 { *bd = true; }
    zguard(n120, &mut dp);
    if !n127 { *bd = true; }
    if !n132 { *bd = true; }
    if !n144 { *bd = true; }
    if !n148 { *bd = true; }
    if !n152 { *bd = true; }
    zguard(n186, &mut dp);
    if !n192 { *bd = true; }
    if !n201 { *bd = true; }
    if !n205 { *bd = true; }
    if !n208 { *bd = true; }
    zguard(n240, &mut dp);
    if !n246 { *bd = true; }
    zguard(n276, &mut dp);
    zguard(n303, &mut dp);
    if !n1778 { *bd = true; }
    if !n1781 { *bd = true; }
    if !n1784 { *bd = true; }
    if !n1788 { *bd = true; }
    if !n1790 { *bd = true; }
    if !n2147 { *bd = true; }
    if !n2149 { *bd = true; }
    if !n2153 { *bd = true; }
    if !n2155 { *bd = true; }
    if !n2176 { *bd = true; }
    if !n2207 { *bd = true; }
    for c0 in 0..2usize {
    let mut dp = dp;
    let mut bd_l: bool = *bd;
    let bd: &mut bool = &mut bd_l;
    let (f0, f0_fv): (ZI, u16) = zi_fork_flr(n261, c0, &mut dp);
    let valid0: u16 = ALL & f0_fv;
    if valid0 == 0 { continue; }
    let n268: ZN = zi_flr(f0, &mut dp);
    let n271: ZI = zi_sub(f0, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n272: ZI = zi_sub(n271, zi_of_zn(n268));
    let n273: ZI = zsel_i(n254, n272, f0, &mut dp);
    let n281: ZB = zn_gt(n268, zn_splat(P8::from_raw(0i32)));
    let n282: ZB = zn_lt(n268, zn_splat(P8::from_raw(0i32)));
    let n283: ZB = zsel_b(n281, n281, n282, &mut dp);
    let n287: ZN = zsel_n(n281, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)), &mut dp);
    let n289: ZN = zsel_n(n283, n287, zn_splat(P8::from_raw(0i32)), &mut dp);
    let n292: ZN = zn_abs(n268);
    let n293: ZB = zn_le(n292, zn_splat(P8::from_raw(524288i32)));
    let n294: ZB = zsel_b(n254, n293, zb_splat(true), &mut dp);
    let n299: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n292);
    let n300: ZN = zn_add(n97, n289);
    let n302: ZB = zn_tile_flag_at(g.cache, g.cart, n300, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n335: ZB = zsel_b(n302, n302, zb_splat(false), &mut dp);
    let n346: ZB = zsel_b(n335, n335, zb_splat(false), &mut dp);
    let n349: ZB = zb_not(n346);
    let n350: ZB = zsel_b(n299, n349, n299, &mut dp);
    let n353: ZB = zb_not(n349);
    let n354: ZB = zsel_b(n299, n353, n299, &mut dp);
    let n356: ZN = zn_add(r_c316, n289);
    let n357: ZN = zsel_n(n350, n356, r_c316, &mut dp);
    let n360: ZN = zsel_n(n254, n357, r_c316, &mut dp);
    let n362: ZN = zsel_n(n354, zn_splat(P8::from_raw(0i32)), r_c406, &mut dp);
    let n365: ZN = zsel_n(n254, n362, r_c406, &mut dp);
    let n367: ZI = zsel_i(n354, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n273, &mut dp);
    let n369: ZI = zsel_i(n254, n367, n273, &mut dp);
    let n371: ZN = zsel_n(n350, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)), &mut dp);
    let n373: ZB = zsel_b(n354, zb_splat(false), zb_splat(true), &mut dp);
    let n375: ZB = zn_le(n371, n292);
    let n376: ZN = zn_add(n360, zn_splat(u.c402));
    let n377: ZN = zn_add(n376, n289);
    let n378: ZB = zn_tile_flag_at(g.cache, g.cart, n377, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n397: ZB = zsel_b(n378, n378, zb_splat(false), &mut dp);
    let n408: ZB = zsel_b(n397, n397, zb_splat(false), &mut dp);
    let n411: ZB = zb_not(n408);
    let n412: ZB = zsel_b(n373, n375, n373, &mut dp);
    let n415: ZB = zsel_b(n412, n411, n412, &mut dp);
    let n418: ZB = zb_not(n411);
    let n419: ZB = zsel_b(n412, n418, n412, &mut dp);
    let n421: ZN = zn_add(n360, n289);
    let n422: ZN = zsel_n(n415, n421, n360, &mut dp);
    let n425: ZN = zsel_n(n254, n422, n360, &mut dp);
    let n427: ZN = zn_add(n371, zn_splat(P8::from_raw(65536i32)));
    let n428: ZN = zsel_n(n419, zn_splat(P8::from_raw(0i32)), n365, &mut dp);
    let n431: ZN = zsel_n(n254, n428, n365, &mut dp);
    let n433: ZI = zsel_i(n419, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n369, &mut dp);
    let n435: ZI = zsel_i(n254, n433, n369, &mut dp);
    let n437: ZN = zsel_n(n415, n427, n371, &mut dp);
    let n439: ZB = zsel_b(n419, zb_splat(false), n373, &mut dp);
    let n441: ZB = zn_le(n437, n292);
    let n442: ZN = zn_add(n425, zn_splat(u.c402));
    let n443: ZN = zn_add(n442, n289);
    let n444: ZB = zn_tile_flag_at(g.cache, g.cart, n443, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n463: ZB = zsel_b(n444, n444, zb_splat(false), &mut dp);
    let n474: ZB = zsel_b(n463, n463, zb_splat(false), &mut dp);
    let n477: ZB = zb_not(n474);
    let n478: ZB = zsel_b(n439, n441, n439, &mut dp);
    let n481: ZB = zsel_b(n478, n477, n478, &mut dp);
    let n484: ZB = zb_not(n477);
    let n485: ZB = zsel_b(n478, n484, n478, &mut dp);
    let n487: ZN = zn_add(n425, n289);
    let n488: ZN = zsel_n(n481, n487, n425, &mut dp);
    let n491: ZN = zsel_n(n254, n488, n425, &mut dp);
    let n493: ZN = zn_add(n437, zn_splat(P8::from_raw(65536i32)));
    let n494: ZN = zsel_n(n485, zn_splat(P8::from_raw(0i32)), n431, &mut dp);
    let n497: ZN = zsel_n(n254, n494, n431, &mut dp);
    let n499: ZI = zsel_i(n485, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n435, &mut dp);
    let n501: ZI = zsel_i(n254, n499, n435, &mut dp);
    let n503: ZN = zsel_n(n481, n493, n437, &mut dp);
    let n505: ZB = zsel_b(n485, zb_splat(false), n439, &mut dp);
    let n507: ZB = zn_le(n503, n292);
    let n508: ZN = zn_add(n491, zn_splat(u.c402));
    let n509: ZN = zn_add(n508, n289);
    let n510: ZB = zn_tile_flag_at(g.cache, g.cart, n509, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n529: ZB = zsel_b(n510, n510, zb_splat(false), &mut dp);
    let n540: ZB = zsel_b(n529, n529, zb_splat(false), &mut dp);
    let n543: ZB = zb_not(n540);
    let n544: ZB = zsel_b(n505, n507, n505, &mut dp);
    let n547: ZB = zsel_b(n544, n543, n544, &mut dp);
    let n550: ZB = zb_not(n543);
    let n551: ZB = zsel_b(n544, n550, n544, &mut dp);
    let n553: ZN = zn_add(n491, n289);
    let n554: ZN = zsel_n(n547, n553, n491, &mut dp);
    let n557: ZN = zsel_n(n254, n554, n491, &mut dp);
    let n559: ZN = zn_add(n503, zn_splat(P8::from_raw(65536i32)));
    let n560: ZN = zsel_n(n551, zn_splat(P8::from_raw(0i32)), n497, &mut dp);
    let n563: ZN = zsel_n(n254, n560, n497, &mut dp);
    let n565: ZI = zsel_i(n551, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n501, &mut dp);
    let n567: ZI = zsel_i(n254, n565, n501, &mut dp);
    let n569: ZN = zsel_n(n547, n559, n503, &mut dp);
    let n571: ZB = zsel_b(n551, zb_splat(false), n505, &mut dp);
    let n573: ZB = zn_le(n569, n292);
    let n574: ZN = zn_add(n557, zn_splat(u.c402));
    let n575: ZN = zn_add(n574, n289);
    let n576: ZB = zn_tile_flag_at(g.cache, g.cart, n575, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n595: ZB = zsel_b(n576, n576, zb_splat(false), &mut dp);
    let n606: ZB = zsel_b(n595, n595, zb_splat(false), &mut dp);
    let n609: ZB = zb_not(n606);
    let n610: ZB = zsel_b(n571, n573, n571, &mut dp);
    let n613: ZB = zsel_b(n610, n609, n610, &mut dp);
    let n616: ZB = zb_not(n609);
    let n617: ZB = zsel_b(n610, n616, n610, &mut dp);
    let n619: ZN = zn_add(n557, n289);
    let n620: ZN = zsel_n(n613, n619, n557, &mut dp);
    let n623: ZN = zsel_n(n254, n620, n557, &mut dp);
    let n625: ZN = zn_add(n569, zn_splat(P8::from_raw(65536i32)));
    let n626: ZN = zsel_n(n617, zn_splat(P8::from_raw(0i32)), n563, &mut dp);
    let n629: ZN = zsel_n(n254, n626, n563, &mut dp);
    let n631: ZI = zsel_i(n617, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n567, &mut dp);
    let n633: ZI = zsel_i(n254, n631, n567, &mut dp);
    let n635: ZN = zsel_n(n613, n625, n569, &mut dp);
    let n637: ZB = zsel_b(n617, zb_splat(false), n571, &mut dp);
    let n639: ZB = zn_le(n635, n292);
    let n640: ZN = zn_add(n623, zn_splat(u.c402));
    let n641: ZN = zn_add(n640, n289);
    let n642: ZB = zn_tile_flag_at(g.cache, g.cart, n641, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n661: ZB = zsel_b(n642, n642, zb_splat(false), &mut dp);
    let n672: ZB = zsel_b(n661, n661, zb_splat(false), &mut dp);
    let n675: ZB = zb_not(n672);
    let n676: ZB = zsel_b(n637, n639, n637, &mut dp);
    let n679: ZB = zsel_b(n676, n675, n676, &mut dp);
    let n682: ZB = zb_not(n675);
    let n683: ZB = zsel_b(n676, n682, n676, &mut dp);
    let n685: ZN = zn_add(n623, n289);
    let n686: ZN = zsel_n(n679, n685, n623, &mut dp);
    let n689: ZN = zsel_n(n254, n686, n623, &mut dp);
    let n691: ZN = zn_add(n635, zn_splat(P8::from_raw(65536i32)));
    let n692: ZN = zsel_n(n683, zn_splat(P8::from_raw(0i32)), n629, &mut dp);
    let n695: ZN = zsel_n(n254, n692, n629, &mut dp);
    let n697: ZI = zsel_i(n683, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n633, &mut dp);
    let n699: ZI = zsel_i(n254, n697, n633, &mut dp);
    let n701: ZN = zsel_n(n679, n691, n635, &mut dp);
    let n703: ZB = zsel_b(n683, zb_splat(false), n637, &mut dp);
    let n705: ZB = zn_le(n701, n292);
    let n706: ZN = zn_add(n689, zn_splat(u.c402));
    let n707: ZN = zn_add(n706, n289);
    let n708: ZB = zn_tile_flag_at(g.cache, g.cart, n707, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n727: ZB = zsel_b(n708, n708, zb_splat(false), &mut dp);
    let n738: ZB = zsel_b(n727, n727, zb_splat(false), &mut dp);
    let n741: ZB = zb_not(n738);
    let n742: ZB = zsel_b(n703, n705, n703, &mut dp);
    let n745: ZB = zsel_b(n742, n741, n742, &mut dp);
    let n748: ZB = zb_not(n741);
    let n749: ZB = zsel_b(n742, n748, n742, &mut dp);
    let n751: ZN = zn_add(n689, n289);
    let n752: ZN = zsel_n(n745, n751, n689, &mut dp);
    let n755: ZN = zsel_n(n254, n752, n689, &mut dp);
    let n757: ZN = zn_add(n701, zn_splat(P8::from_raw(65536i32)));
    let n758: ZN = zsel_n(n749, zn_splat(P8::from_raw(0i32)), n695, &mut dp);
    let n761: ZN = zsel_n(n254, n758, n695, &mut dp);
    let n763: ZI = zsel_i(n749, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n699, &mut dp);
    let n765: ZI = zsel_i(n254, n763, n699, &mut dp);
    let n767: ZN = zsel_n(n745, n757, n701, &mut dp);
    let n769: ZB = zsel_b(n749, zb_splat(false), n703, &mut dp);
    let n771: ZB = zn_le(n767, n292);
    let n772: ZN = zn_add(n755, zn_splat(u.c402));
    let n773: ZN = zn_add(n772, n289);
    let n774: ZB = zn_tile_flag_at(g.cache, g.cart, n773, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n793: ZB = zsel_b(n774, n774, zb_splat(false), &mut dp);
    let n804: ZB = zsel_b(n793, n793, zb_splat(false), &mut dp);
    let n807: ZB = zb_not(n804);
    let n808: ZB = zsel_b(n769, n771, n769, &mut dp);
    let n811: ZB = zsel_b(n808, n807, n808, &mut dp);
    let n814: ZB = zb_not(n807);
    let n815: ZB = zsel_b(n808, n814, n808, &mut dp);
    let n817: ZN = zn_add(n755, n289);
    let n818: ZN = zsel_n(n811, n817, n755, &mut dp);
    let n821: ZN = zsel_n(n254, n818, n755, &mut dp);
    let n823: ZN = zn_add(n767, zn_splat(P8::from_raw(65536i32)));
    let n824: ZN = zsel_n(n815, zn_splat(P8::from_raw(0i32)), n761, &mut dp);
    let n827: ZN = zsel_n(n254, n824, n761, &mut dp);
    let n829: ZI = zsel_i(n815, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n765, &mut dp);
    let n831: ZI = zsel_i(n254, n829, n765, &mut dp);
    let n833: ZN = zsel_n(n811, n823, n767, &mut dp);
    let n835: ZB = zsel_b(n815, zb_splat(false), n769, &mut dp);
    let n837: ZB = zn_le(n833, n292);
    let n838: ZN = zn_add(n821, zn_splat(u.c402));
    let n839: ZN = zn_add(n838, n289);
    let n840: ZB = zn_tile_flag_at(g.cache, g.cart, n839, n301, u.c401, u.c400, P8::from_raw(0i32));
    let n859: ZB = zsel_b(n840, n840, zb_splat(false), &mut dp);
    let n870: ZB = zsel_b(n859, n859, zb_splat(false), &mut dp);
    let n873: ZB = zb_not(n870);
    let n874: ZB = zsel_b(n835, n837, n835, &mut dp);
    let n877: ZB = zsel_b(n874, n873, n874, &mut dp);
    let n880: ZB = zb_not(n873);
    let n881: ZB = zsel_b(n874, n880, n874, &mut dp);
    let n883: ZN = zn_add(n821, n289);
    let n884: ZN = zsel_n(n877, n883, n821, &mut dp);
    let n887: ZN = zsel_n(n254, n884, n821, &mut dp);
    let n889: ZN = zsel_n(n881, zn_splat(P8::from_raw(0i32)), n827, &mut dp);
    let n892: ZN = zsel_n(n254, n889, n827, &mut dp);
    let n894: ZI = zsel_i(n881, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n831, &mut dp);
    let n896: ZI = zsel_i(n254, n894, n831, &mut dp);
    let n934: ZN = zn_add(n887, zn_splat(u.c402));
    let n935: ZN = zn_add(n934, zn_splat(P8::from_raw(0i32)));
    let n937: ZN = zn_add(n934, zn_splat(u.c401));
    let n1794: ZN = zn_div(n934, zn_splat(P8::from_raw(524288i32)));
    let n1795: ZN = zn_flr(n1794);
    let n1796: ZN = zn_max(zn_splat(P8::from_raw(0i32)), n1795);
    let n1797: ZN = zn_sub(n937, zn_splat(P8::from_raw(65536i32)));
    let n1798: ZN = zn_div(n1797, zn_splat(P8::from_raw(524288i32)));
    let n1800: ZN = zn_min(zn_splat(P8::from_raw(983040i32)), n1798);
    let n1801: ZB = zn_ge(n1796, zn_splat(P8::from_raw(0i32)));
    let n1805: ZN = zn_sub(n1800, n1796);
    let n1807: ZB = zn_lt(n1805, zn_splat(P8::from_raw(131072i32)));
    let n1811: ZB = zn_le(n1796, n1800);
    let n1831: ZN = zn_add(zn_splat(n1830), n1796);
    let n1869: ZN = zn_rem(n934, zn_splat(P8::from_raw(524288i32)));
    let n1870: ZB = zn_le(n1869, zn_splat(P8::from_raw(131072i32)));
    let n1874: ZB = zn_le(n892, zn_splat(P8::from_raw(0i32)));
    let n1883: ZN = zn_rem(n1797, zn_splat(P8::from_raw(524288i32)));
    let n1884: ZB = zn_ge(n1883, zn_splat(P8::from_raw(393216i32)));
    let n1885: ZN = zn_mul(n1796, zn_splat(P8::from_raw(524288i32)));
    let n1886: ZN = zn_add(n1885, zn_splat(P8::from_raw(524288i32)));
    let n1887: ZB = zn_eq(n937, n1886);
    let n1888: ZB = zsel_b(n1884, n1884, n1887, &mut dp);
    let n1894: ZB = zn_ge(n892, zn_splat(P8::from_raw(0i32)));
    let n1968: ZN = zn_add(n1796, zn_splat(P8::from_raw(65536i32)));
    let n2180: ZB = zn_gt(n892, r_c396);
    let n2182: ZN = zn_sub(n892, r_c394);
    let n2183: ZN = zn_max(n2182, r_c396);
    let n2184: ZN = zn_add(n892, r_c394);
    let n2185: ZN = zn_min(n2184, r_c396);
    let n2186: ZN = zsel_n(n2180, n2183, n2185, &mut dp);
    let n2210: ZB = zn_lt(n887, zn_splat(P8::from_raw(-65536i32)));
    let n2212: ZB = zn_gt(n887, zn_splat(P8::from_raw(7929856i32)));
    let n2213: ZB = zsel_b(n2210, n2210, n2212, &mut dp);
    let n2216: ZN = zn_min(zn_splat(P8::from_raw(7929856i32)), n887);
    let n2217: ZN = zn_max(zn_splat(P8::from_raw(-65536i32)), n2216);
    let n2218: ZN = zsel_n(n2213, zn_splat(P8::from_raw(0i32)), n2186, &mut dp);
    let n2221: ZN = zsel_n(n2213, n2217, n887, &mut dp);
    zguard(n294, &mut dp);
    zguard(n1801, &mut dp);
    zguard(n1807, &mut dp);
    for c1 in 0..2usize {
    let mut dp = dp;
    let mut bd_l: bool = *bd;
    let bd: &mut bool = &mut bd_l;
    let (f1, f1_fv): (ZI, u16) = zi_fork_flr(n901, c1, &mut dp);
    let valid1: u16 = valid0 & f1_fv;
    if valid1 == 0 { continue; }
    let n908: ZN = zi_flr(f1, &mut dp);
    let n911: ZI = zi_sub(f1, zi_splat(P8::from_raw(32768i32), P8::from_raw(32768i32)));
    let n912: ZI = zi_sub(n911, zi_of_zn(n908));
    let n913: ZI = zsel_i(n254, n912, f1, &mut dp);
    let n915: ZB = zn_gt(n908, zn_splat(P8::from_raw(0i32)));
    let n916: ZB = zn_lt(n908, zn_splat(P8::from_raw(0i32)));
    let n917: ZB = zsel_b(n915, n915, n916, &mut dp);
    let n920: ZN = zsel_n(n915, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(-65536i32)), &mut dp);
    let n922: ZN = zsel_n(n917, n920, zn_splat(P8::from_raw(0i32)), &mut dp);
    let n925: ZN = zn_abs(n908);
    let n926: ZB = zn_le(n925, zn_splat(P8::from_raw(524288i32)));
    let n927: ZB = zsel_b(n254, n926, zb_splat(true), &mut dp);
    let n932: ZB = zn_le(zn_splat(P8::from_raw(0i32)), n925);
    let n933: ZB = zn_gt(n922, zn_splat(P8::from_raw(0i32)));
    let n954: ZB = zsel_b(n933, zb_splat(true), n933, &mut dp);
    let n957: ZN = zn_add(n105, n922);
    let n975: ZB = zsel_b(n954, zb_splat(false), n954, &mut dp);
    let n978: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n957, u.c401, u.c400, P8::from_raw(0i32));
    let n987: ZB = zsel_b(n978, n978, zb_splat(false), &mut dp);
    let n998: ZB = zsel_b(n987, n987, zb_splat(false), &mut dp);
    let n1001: ZB = zsel_b(n975, zb_splat(true), n998, &mut dp);
    let n1004: ZB = zb_not(n1001);
    let n1005: ZB = zsel_b(n932, n1004, n932, &mut dp);
    let n1008: ZB = zb_not(n1004);
    let n1009: ZB = zsel_b(n932, n1008, n932, &mut dp);
    let n1011: ZN = zn_add(r_c317, n922);
    let n1012: ZN = zsel_n(n1005, n1011, r_c317, &mut dp);
    let n1015: ZN = zsel_n(n254, n1012, r_c317, &mut dp);
    let n1017: ZN = zsel_n(n1009, zn_splat(P8::from_raw(0i32)), r_c407, &mut dp);
    let n1020: ZN = zsel_n(n254, n1017, r_c407, &mut dp);
    let n1022: ZI = zsel_i(n1009, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n913, &mut dp);
    let n1024: ZI = zsel_i(n254, n1022, n913, &mut dp);
    let n1026: ZN = zsel_n(n1005, zn_splat(P8::from_raw(65536i32)), zn_splat(P8::from_raw(0i32)), &mut dp);
    let n1028: ZB = zsel_b(n1009, zb_splat(false), zb_splat(true), &mut dp);
    let n1030: ZB = zn_le(n1026, n925);
    let n1031: ZN = zn_add(n1015, zn_splat(u.c403));
    let n1051: ZN = zn_add(n1031, n922);
    let n1069: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1051, u.c401, u.c400, P8::from_raw(0i32));
    let n1078: ZB = zsel_b(n1069, n1069, zb_splat(false), &mut dp);
    let n1089: ZB = zsel_b(n1078, n1078, zb_splat(false), &mut dp);
    let n1092: ZB = zsel_b(n975, zb_splat(true), n1089, &mut dp);
    let n1094: ZB = zb_not(n1092);
    let n1095: ZB = zsel_b(n1028, n1030, n1028, &mut dp);
    let n1098: ZB = zsel_b(n1095, n1094, n1095, &mut dp);
    let n1101: ZB = zb_not(n1094);
    let n1102: ZB = zsel_b(n1095, n1101, n1095, &mut dp);
    let n1104: ZN = zn_add(n1015, n922);
    let n1105: ZN = zsel_n(n1098, n1104, n1015, &mut dp);
    let n1108: ZN = zsel_n(n254, n1105, n1015, &mut dp);
    let n1110: ZN = zn_add(n1026, zn_splat(P8::from_raw(65536i32)));
    let n1111: ZN = zsel_n(n1102, zn_splat(P8::from_raw(0i32)), n1020, &mut dp);
    let n1114: ZN = zsel_n(n254, n1111, n1020, &mut dp);
    let n1116: ZI = zsel_i(n1102, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1024, &mut dp);
    let n1118: ZI = zsel_i(n254, n1116, n1024, &mut dp);
    let n1120: ZN = zsel_n(n1098, n1110, n1026, &mut dp);
    let n1122: ZB = zsel_b(n1102, zb_splat(false), n1028, &mut dp);
    let n1124: ZB = zn_le(n1120, n925);
    let n1125: ZN = zn_add(n1108, zn_splat(u.c403));
    let n1145: ZN = zn_add(n1125, n922);
    let n1163: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1145, u.c401, u.c400, P8::from_raw(0i32));
    let n1172: ZB = zsel_b(n1163, n1163, zb_splat(false), &mut dp);
    let n1183: ZB = zsel_b(n1172, n1172, zb_splat(false), &mut dp);
    let n1186: ZB = zsel_b(n975, zb_splat(true), n1183, &mut dp);
    let n1188: ZB = zb_not(n1186);
    let n1189: ZB = zsel_b(n1122, n1124, n1122, &mut dp);
    let n1192: ZB = zsel_b(n1189, n1188, n1189, &mut dp);
    let n1195: ZB = zb_not(n1188);
    let n1196: ZB = zsel_b(n1189, n1195, n1189, &mut dp);
    let n1198: ZN = zn_add(n1108, n922);
    let n1199: ZN = zsel_n(n1192, n1198, n1108, &mut dp);
    let n1202: ZN = zsel_n(n254, n1199, n1108, &mut dp);
    let n1204: ZN = zn_add(n1120, zn_splat(P8::from_raw(65536i32)));
    let n1205: ZN = zsel_n(n1196, zn_splat(P8::from_raw(0i32)), n1114, &mut dp);
    let n1208: ZN = zsel_n(n254, n1205, n1114, &mut dp);
    let n1210: ZI = zsel_i(n1196, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1118, &mut dp);
    let n1212: ZI = zsel_i(n254, n1210, n1118, &mut dp);
    let n1214: ZN = zsel_n(n1192, n1204, n1120, &mut dp);
    let n1216: ZB = zsel_b(n1196, zb_splat(false), n1122, &mut dp);
    let n1218: ZB = zn_le(n1214, n925);
    let n1219: ZN = zn_add(n1202, zn_splat(u.c403));
    let n1239: ZN = zn_add(n1219, n922);
    let n1257: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1239, u.c401, u.c400, P8::from_raw(0i32));
    let n1266: ZB = zsel_b(n1257, n1257, zb_splat(false), &mut dp);
    let n1277: ZB = zsel_b(n1266, n1266, zb_splat(false), &mut dp);
    let n1280: ZB = zsel_b(n975, zb_splat(true), n1277, &mut dp);
    let n1282: ZB = zb_not(n1280);
    let n1283: ZB = zsel_b(n1216, n1218, n1216, &mut dp);
    let n1286: ZB = zsel_b(n1283, n1282, n1283, &mut dp);
    let n1289: ZB = zb_not(n1282);
    let n1290: ZB = zsel_b(n1283, n1289, n1283, &mut dp);
    let n1292: ZN = zn_add(n1202, n922);
    let n1293: ZN = zsel_n(n1286, n1292, n1202, &mut dp);
    let n1296: ZN = zsel_n(n254, n1293, n1202, &mut dp);
    let n1298: ZN = zn_add(n1214, zn_splat(P8::from_raw(65536i32)));
    let n1299: ZN = zsel_n(n1290, zn_splat(P8::from_raw(0i32)), n1208, &mut dp);
    let n1302: ZN = zsel_n(n254, n1299, n1208, &mut dp);
    let n1304: ZI = zsel_i(n1290, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1212, &mut dp);
    let n1306: ZI = zsel_i(n254, n1304, n1212, &mut dp);
    let n1308: ZN = zsel_n(n1286, n1298, n1214, &mut dp);
    let n1310: ZB = zsel_b(n1290, zb_splat(false), n1216, &mut dp);
    let n1312: ZB = zn_le(n1308, n925);
    let n1313: ZN = zn_add(n1296, zn_splat(u.c403));
    let n1333: ZN = zn_add(n1313, n922);
    let n1351: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1333, u.c401, u.c400, P8::from_raw(0i32));
    let n1360: ZB = zsel_b(n1351, n1351, zb_splat(false), &mut dp);
    let n1371: ZB = zsel_b(n1360, n1360, zb_splat(false), &mut dp);
    let n1374: ZB = zsel_b(n975, zb_splat(true), n1371, &mut dp);
    let n1376: ZB = zb_not(n1374);
    let n1377: ZB = zsel_b(n1310, n1312, n1310, &mut dp);
    let n1380: ZB = zsel_b(n1377, n1376, n1377, &mut dp);
    let n1383: ZB = zb_not(n1376);
    let n1384: ZB = zsel_b(n1377, n1383, n1377, &mut dp);
    let n1386: ZN = zn_add(n1296, n922);
    let n1387: ZN = zsel_n(n1380, n1386, n1296, &mut dp);
    let n1390: ZN = zsel_n(n254, n1387, n1296, &mut dp);
    let n1392: ZN = zn_add(n1308, zn_splat(P8::from_raw(65536i32)));
    let n1393: ZN = zsel_n(n1384, zn_splat(P8::from_raw(0i32)), n1302, &mut dp);
    let n1396: ZN = zsel_n(n254, n1393, n1302, &mut dp);
    let n1398: ZI = zsel_i(n1384, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1306, &mut dp);
    let n1400: ZI = zsel_i(n254, n1398, n1306, &mut dp);
    let n1402: ZN = zsel_n(n1380, n1392, n1308, &mut dp);
    let n1404: ZB = zsel_b(n1384, zb_splat(false), n1310, &mut dp);
    let n1406: ZB = zn_le(n1402, n925);
    let n1407: ZN = zn_add(n1390, zn_splat(u.c403));
    let n1427: ZN = zn_add(n1407, n922);
    let n1445: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1427, u.c401, u.c400, P8::from_raw(0i32));
    let n1454: ZB = zsel_b(n1445, n1445, zb_splat(false), &mut dp);
    let n1465: ZB = zsel_b(n1454, n1454, zb_splat(false), &mut dp);
    let n1468: ZB = zsel_b(n975, zb_splat(true), n1465, &mut dp);
    let n1470: ZB = zb_not(n1468);
    let n1471: ZB = zsel_b(n1404, n1406, n1404, &mut dp);
    let n1474: ZB = zsel_b(n1471, n1470, n1471, &mut dp);
    let n1477: ZB = zb_not(n1470);
    let n1478: ZB = zsel_b(n1471, n1477, n1471, &mut dp);
    let n1480: ZN = zn_add(n1390, n922);
    let n1481: ZN = zsel_n(n1474, n1480, n1390, &mut dp);
    let n1484: ZN = zsel_n(n254, n1481, n1390, &mut dp);
    let n1486: ZN = zn_add(n1402, zn_splat(P8::from_raw(65536i32)));
    let n1487: ZN = zsel_n(n1478, zn_splat(P8::from_raw(0i32)), n1396, &mut dp);
    let n1490: ZN = zsel_n(n254, n1487, n1396, &mut dp);
    let n1492: ZI = zsel_i(n1478, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1400, &mut dp);
    let n1494: ZI = zsel_i(n254, n1492, n1400, &mut dp);
    let n1496: ZN = zsel_n(n1474, n1486, n1402, &mut dp);
    let n1498: ZB = zsel_b(n1478, zb_splat(false), n1404, &mut dp);
    let n1500: ZB = zn_le(n1496, n925);
    let n1501: ZN = zn_add(n1484, zn_splat(u.c403));
    let n1521: ZN = zn_add(n1501, n922);
    let n1539: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1521, u.c401, u.c400, P8::from_raw(0i32));
    let n1548: ZB = zsel_b(n1539, n1539, zb_splat(false), &mut dp);
    let n1559: ZB = zsel_b(n1548, n1548, zb_splat(false), &mut dp);
    let n1562: ZB = zsel_b(n975, zb_splat(true), n1559, &mut dp);
    let n1564: ZB = zb_not(n1562);
    let n1565: ZB = zsel_b(n1498, n1500, n1498, &mut dp);
    let n1568: ZB = zsel_b(n1565, n1564, n1565, &mut dp);
    let n1571: ZB = zb_not(n1564);
    let n1572: ZB = zsel_b(n1565, n1571, n1565, &mut dp);
    let n1574: ZN = zn_add(n1484, n922);
    let n1575: ZN = zsel_n(n1568, n1574, n1484, &mut dp);
    let n1578: ZN = zsel_n(n254, n1575, n1484, &mut dp);
    let n1580: ZN = zn_add(n1496, zn_splat(P8::from_raw(65536i32)));
    let n1581: ZN = zsel_n(n1572, zn_splat(P8::from_raw(0i32)), n1490, &mut dp);
    let n1584: ZN = zsel_n(n254, n1581, n1490, &mut dp);
    let n1586: ZI = zsel_i(n1572, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1494, &mut dp);
    let n1588: ZI = zsel_i(n254, n1586, n1494, &mut dp);
    let n1590: ZN = zsel_n(n1568, n1580, n1496, &mut dp);
    let n1592: ZB = zsel_b(n1572, zb_splat(false), n1498, &mut dp);
    let n1594: ZB = zn_le(n1590, n925);
    let n1595: ZN = zn_add(n1578, zn_splat(u.c403));
    let n1615: ZN = zn_add(n1595, n922);
    let n1633: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1615, u.c401, u.c400, P8::from_raw(0i32));
    let n1642: ZB = zsel_b(n1633, n1633, zb_splat(false), &mut dp);
    let n1653: ZB = zsel_b(n1642, n1642, zb_splat(false), &mut dp);
    let n1656: ZB = zsel_b(n975, zb_splat(true), n1653, &mut dp);
    let n1658: ZB = zb_not(n1656);
    let n1659: ZB = zsel_b(n1592, n1594, n1592, &mut dp);
    let n1662: ZB = zsel_b(n1659, n1658, n1659, &mut dp);
    let n1665: ZB = zb_not(n1658);
    let n1666: ZB = zsel_b(n1659, n1665, n1659, &mut dp);
    let n1668: ZN = zn_add(n1578, n922);
    let n1669: ZN = zsel_n(n1662, n1668, n1578, &mut dp);
    let n1672: ZN = zsel_n(n254, n1669, n1578, &mut dp);
    let n1674: ZN = zn_add(n1590, zn_splat(P8::from_raw(65536i32)));
    let n1675: ZN = zsel_n(n1666, zn_splat(P8::from_raw(0i32)), n1584, &mut dp);
    let n1678: ZN = zsel_n(n254, n1675, n1584, &mut dp);
    let n1680: ZI = zsel_i(n1666, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1588, &mut dp);
    let n1682: ZI = zsel_i(n254, n1680, n1588, &mut dp);
    let n1684: ZN = zsel_n(n1662, n1674, n1590, &mut dp);
    let n1686: ZB = zsel_b(n1666, zb_splat(false), n1592, &mut dp);
    let n1688: ZB = zn_le(n1684, n925);
    let n1689: ZN = zn_add(n1672, zn_splat(u.c403));
    let n1709: ZN = zn_add(n1689, n922);
    let n1727: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n1709, u.c401, u.c400, P8::from_raw(0i32));
    let n1736: ZB = zsel_b(n1727, n1727, zb_splat(false), &mut dp);
    let n1747: ZB = zsel_b(n1736, n1736, zb_splat(false), &mut dp);
    let n1750: ZB = zsel_b(n975, zb_splat(true), n1747, &mut dp);
    let n1752: ZB = zb_not(n1750);
    let n1753: ZB = zsel_b(n1686, n1688, n1686, &mut dp);
    let n1756: ZB = zsel_b(n1753, n1752, n1753, &mut dp);
    let n1759: ZB = zb_not(n1752);
    let n1760: ZB = zsel_b(n1753, n1759, n1753, &mut dp);
    let n1762: ZN = zn_add(n1672, n922);
    let n1763: ZN = zsel_n(n1756, n1762, n1672, &mut dp);
    let n1766: ZN = zsel_n(n254, n1763, n1672, &mut dp);
    let n1768: ZN = zsel_n(n1760, zn_splat(P8::from_raw(0i32)), n1678, &mut dp);
    let n1771: ZN = zsel_n(n254, n1768, n1678, &mut dp);
    let n1773: ZI = zsel_i(n1760, zi_splat(P8::from_raw(0i32), P8::from_raw(0i32)), n1682, &mut dp);
    let n1775: ZI = zsel_i(n254, n1773, n1682, &mut dp);
    let n1793: ZN = zn_add(n1766, zn_splat(u.c403));
    let n1812: ZN = zn_div(n1793, zn_splat(P8::from_raw(524288i32)));
    let n1813: ZN = zn_flr(n1812);
    let n1814: ZN = zn_max(zn_splat(P8::from_raw(0i32)), n1813);
    let n1815: ZN = zn_add(n1793, zn_splat(u.c400));
    let n1816: ZN = zn_sub(n1815, zn_splat(P8::from_raw(65536i32)));
    let n1817: ZN = zn_div(n1816, zn_splat(P8::from_raw(524288i32)));
    let n1818: ZN = zn_min(zn_splat(P8::from_raw(983040i32)), n1817);
    let n1819: ZB = zn_ge(n1814, zn_splat(P8::from_raw(0i32)));
    let n1823: ZN = zn_sub(n1818, n1814);
    let n1824: ZB = zn_lt(n1823, zn_splat(P8::from_raw(131072i32)));
    let n1828: ZB = zn_le(n1814, n1818);
    let n1833: ZN = zn_add(zn_splat(n1832), n1814);
    let n1834: ZN = zn_mget(g.cart, n1831, n1833);
    let n1836: ZB = zn_eq(n1834, zn_splat(P8::from_raw(1114112i32)));
    let n1837: ZN = zn_rem(n1816, zn_splat(P8::from_raw(524288i32)));
    let n1839: ZB = zn_ge(n1837, zn_splat(P8::from_raw(393216i32)));
    let n1840: ZN = zn_mul(n1814, zn_splat(P8::from_raw(524288i32)));
    let n1841: ZN = zn_add(n1840, zn_splat(P8::from_raw(524288i32)));
    let n1842: ZB = zn_eq(n1815, n1841);
    let n1843: ZB = zsel_b(n1839, n1839, n1842, &mut dp);
    let n1846: ZB = zsel_b(n1836, n1843, n1836, &mut dp);
    let n1849: ZB = zn_ge(n1771, zn_splat(P8::from_raw(0i32)));
    let n1850: ZB = zsel_b(n1846, n1849, n1846, &mut dp);
    let n1854: ZB = zn_eq(n1834, zn_splat(P8::from_raw(1769472i32)));
    let n1855: ZN = zn_rem(n1793, zn_splat(P8::from_raw(524288i32)));
    let n1856: ZB = zn_le(n1855, zn_splat(P8::from_raw(131072i32)));
    let n1857: ZB = zsel_b(n1854, n1856, n1854, &mut dp);
    let n1860: ZB = zn_le(n1771, zn_splat(P8::from_raw(0i32)));
    let n1861: ZB = zsel_b(n1857, n1860, n1857, &mut dp);
    let n1864: ZB = zsel_b(n1850, n1850, n1861, &mut dp);
    let n1868: ZB = zn_eq(n1834, zn_splat(P8::from_raw(2818048i32)));
    let n1871: ZB = zsel_b(n1868, n1870, n1868, &mut dp);
    let n1875: ZB = zsel_b(n1871, n1874, n1871, &mut dp);
    let n1878: ZB = zsel_b(n1864, n1864, n1875, &mut dp);
    let n1882: ZB = zn_eq(n1834, zn_splat(P8::from_raw(3866624i32)));
    let n1891: ZB = zsel_b(n1882, n1888, n1882, &mut dp);
    let n1895: ZB = zsel_b(n1891, n1894, n1891, &mut dp);
    let n1898: ZB = zsel_b(n1878, n1878, n1895, &mut dp);
    let n1901: ZB = zb_not(n1898);
    let n1902: ZB = zsel_b(n1828, n1901, n1828, &mut dp);
    let n1905: ZB = zsel_b(n1828, n1898, n1828, &mut dp);
    let n1907: ZN = zn_add(n1814, zn_splat(P8::from_raw(65536i32)));
    let n1908: ZN = zsel_n(n1902, n1907, n1814, &mut dp);
    let n1911: ZB = zsel_b(n1905, zb_splat(false), zb_splat(true), &mut dp);
    let n1914: ZB = zn_le(n1908, n1818);
    let n1915: ZN = zn_add(zn_splat(n1832), n1908);
    let n1916: ZN = zn_mget(g.cart, n1831, n1915);
    let n1917: ZB = zn_eq(n1916, zn_splat(P8::from_raw(1114112i32)));
    let n1918: ZN = zn_mul(n1908, zn_splat(P8::from_raw(524288i32)));
    let n1919: ZN = zn_add(n1918, zn_splat(P8::from_raw(524288i32)));
    let n1920: ZB = zn_eq(n1815, n1919);
    let n1921: ZB = zsel_b(n1839, n1839, n1920, &mut dp);
    let n1923: ZB = zsel_b(n1917, n1921, n1917, &mut dp);
    let n1926: ZB = zsel_b(n1923, n1849, n1923, &mut dp);
    let n1929: ZB = zn_eq(n1916, zn_splat(P8::from_raw(1769472i32)));
    let n1930: ZB = zsel_b(n1929, n1856, n1929, &mut dp);
    let n1933: ZB = zsel_b(n1930, n1860, n1930, &mut dp);
    let n1936: ZB = zsel_b(n1926, n1926, n1933, &mut dp);
    let n1939: ZB = zn_eq(n1916, zn_splat(P8::from_raw(2818048i32)));
    let n1940: ZB = zsel_b(n1939, n1870, n1939, &mut dp);
    let n1943: ZB = zsel_b(n1940, n1874, n1940, &mut dp);
    let n1946: ZB = zsel_b(n1936, n1936, n1943, &mut dp);
    let n1949: ZB = zn_eq(n1916, zn_splat(P8::from_raw(3866624i32)));
    let n1950: ZB = zsel_b(n1949, n1888, n1949, &mut dp);
    let n1953: ZB = zsel_b(n1950, n1894, n1950, &mut dp);
    let n1956: ZB = zsel_b(n1946, n1946, n1953, &mut dp);
    let n1959: ZB = zsel_b(n1911, n1914, n1911, &mut dp);
    let n1962: ZB = zsel_b(n1959, n1956, n1959, &mut dp);
    let n1965: ZB = zsel_b(n1962, zb_splat(false), n1911, &mut dp);
    let n1969: ZB = zsel_b(n1811, n1965, n1811, &mut dp);
    let n1972: ZB = zb_not(n1965);
    let n1973: ZB = zsel_b(n1811, n1972, n1811, &mut dp);
    let n1975: ZN = zsel_n(n1969, n1968, n1796, &mut dp);
    let n1978: ZB = zsel_b(n1973, zb_splat(false), zb_splat(true), &mut dp);
    let n1981: ZB = zn_le(n1975, n1800);
    let n1984: ZN = zn_add(zn_splat(n1830), n1975);
    let n1985: ZN = zn_mget(g.cart, n1984, n1833);
    let n1986: ZB = zn_eq(n1985, zn_splat(P8::from_raw(1114112i32)));
    let n1988: ZB = zsel_b(n1986, n1843, n1986, &mut dp);
    let n1991: ZB = zsel_b(n1988, n1849, n1988, &mut dp);
    let n1994: ZB = zn_eq(n1985, zn_splat(P8::from_raw(1769472i32)));
    let n1995: ZB = zsel_b(n1994, n1856, n1994, &mut dp);
    let n1998: ZB = zsel_b(n1995, n1860, n1995, &mut dp);
    let n2001: ZB = zsel_b(n1991, n1991, n1998, &mut dp);
    let n2004: ZB = zn_eq(n1985, zn_splat(P8::from_raw(2818048i32)));
    let n2005: ZB = zsel_b(n2004, n1870, n2004, &mut dp);
    let n2008: ZB = zsel_b(n2005, n1874, n2005, &mut dp);
    let n2011: ZB = zsel_b(n2001, n2001, n2008, &mut dp);
    let n2014: ZB = zn_eq(n1985, zn_splat(P8::from_raw(3866624i32)));
    let n2015: ZN = zn_mul(n1975, zn_splat(P8::from_raw(524288i32)));
    let n2016: ZN = zn_add(n2015, zn_splat(P8::from_raw(524288i32)));
    let n2017: ZB = zn_eq(n937, n2016);
    let n2018: ZB = zsel_b(n1884, n1884, n2017, &mut dp);
    let n2020: ZB = zsel_b(n2014, n2018, n2014, &mut dp);
    let n2023: ZB = zsel_b(n2020, n1894, n2020, &mut dp);
    let n2026: ZB = zsel_b(n2011, n2011, n2023, &mut dp);
    let n2029: ZB = zb_not(n2026);
    let n2030: ZB = zsel_b(n1828, n2029, n1828, &mut dp);
    let n2032: ZB = zsel_b(n1828, n2026, n1828, &mut dp);
    let n2034: ZN = zsel_n(n2030, n1907, n1814, &mut dp);
    let n2037: ZB = zsel_b(n2032, zb_splat(false), zb_splat(true), &mut dp);
    let n2040: ZB = zn_le(n2034, n1818);
    let n2041: ZN = zn_add(zn_splat(n1832), n2034);
    let n2042: ZN = zn_mget(g.cart, n1984, n2041);
    let n2043: ZB = zn_eq(n2042, zn_splat(P8::from_raw(1114112i32)));
    let n2044: ZN = zn_mul(n2034, zn_splat(P8::from_raw(524288i32)));
    let n2045: ZN = zn_add(n2044, zn_splat(P8::from_raw(524288i32)));
    let n2046: ZB = zn_eq(n1815, n2045);
    let n2047: ZB = zsel_b(n1839, n1839, n2046, &mut dp);
    let n2049: ZB = zsel_b(n2043, n2047, n2043, &mut dp);
    let n2052: ZB = zsel_b(n2049, n1849, n2049, &mut dp);
    let n2055: ZB = zn_eq(n2042, zn_splat(P8::from_raw(1769472i32)));
    let n2056: ZB = zsel_b(n2055, n1856, n2055, &mut dp);
    let n2059: ZB = zsel_b(n2056, n1860, n2056, &mut dp);
    let n2062: ZB = zsel_b(n2052, n2052, n2059, &mut dp);
    let n2065: ZB = zn_eq(n2042, zn_splat(P8::from_raw(2818048i32)));
    let n2066: ZB = zsel_b(n2065, n1870, n2065, &mut dp);
    let n2069: ZB = zsel_b(n2066, n1874, n2066, &mut dp);
    let n2072: ZB = zsel_b(n2062, n2062, n2069, &mut dp);
    let n2075: ZB = zn_eq(n2042, zn_splat(P8::from_raw(3866624i32)));
    let n2076: ZB = zsel_b(n2075, n2018, n2075, &mut dp);
    let n2079: ZB = zsel_b(n2076, n1894, n2076, &mut dp);
    let n2082: ZB = zsel_b(n2072, n2072, n2079, &mut dp);
    let n2085: ZB = zsel_b(n2037, n2040, n2037, &mut dp);
    let n2088: ZB = zsel_b(n2085, n2082, n2085, &mut dp);
    let n2091: ZB = zsel_b(n2088, zb_splat(false), n2037, &mut dp);
    let n2094: ZB = zsel_b(n1978, n1981, n1978, &mut dp);
    let n2097: ZB = zb_not(n2091);
    let n2098: ZB = zsel_b(n2094, n2097, n2094, &mut dp);
    let n2101: ZB = zsel_b(n2098, zb_splat(false), n1978, &mut dp);
    let n2104: ZB = zsel_b(n2101, zb_splat(false), zb_splat(true), &mut dp);
    let n2107: ZB = zb_not(n2104);
    let n2112: ZB = zn_gt(n1766, zn_splat(P8::from_raw(8388608i32)));
    let n2113: ZB = zb_not(n2112);
    let n2127: ZN = zn_add(n1793, zn_splat(P8::from_raw(65536i32)));
    let n2137: ZB = zn_tile_flag_at(g.cache, g.cart, n935, n2127, u.c401, u.c400, P8::from_raw(0i32));
    let n2138: ZB = zsel_b(n2137, n2137, zb_splat(false), &mut dp);
    let n2141: ZB = zsel_b(n2138, n2138, zb_splat(false), &mut dp);
    let n2168: ZN = zsel_n(n2141, zn_splat(P8::from_raw(393216i32)), n2165, &mut dp);
    let n2171: ZN = zsel_n(n2141, zn_splat(n2161), zn_splat(u.c300), &mut dp);
    let n2190: ZB = zn_gt(n1771, r_c397);
    let n2192: ZN = zn_sub(n1771, r_c395);
    let n2193: ZN = zn_max(n2192, r_c397);
    let n2194: ZN = zn_add(n1771, r_c395);
    let n2195: ZN = zn_min(n2194, r_c397);
    let n2196: ZN = zsel_n(n2190, n2193, n2195, &mut dp);
    let n2200: ZB = zn_lt(n1766, zn_splat(P8::from_raw(-262144i32)));
    let n2201: ZB = zb_not(n2200);
    zguard(n927, &mut dp);
    zguard(n1819, &mut dp);
    zguard(n1824, &mut dp);
    zguard(n2107, &mut dp);
    zguard(n2113, &mut dp);
    zguard(n2201, &mut dp);
    let p = Pre {
        valid: valid1,
        dp,
        bd: *bd,
    };
    let osh = KOutShared {
        c84: n11,
        c85: n26,
        c246: n125,
        c254: n136,
        c297: n2174,
        c299: n2178,
        c300: n2171,
        c302: n2168,
        c316: n2221,
        c317: n1766,
        c404: n896,
        c405: n1775,
        c406: n2218,
        c407: n2196,
    };
    // suffix observes button bits [4, 5]: 4 distinct variant(s)
    suffix::<0>(u, g, &p, &osh, out);
    suffix::<16>(u, g, &p, &osh, out);
    suffix::<32>(u, g, &p, &osh, out);
    suffix::<48>(u, g, &p, &osh, out);
    }
    }
}

#[inline(never)]
fn suffix<const B: u8>(u: &Uni, g: &G, p: &Pre, osh: &KOutShared, out: &mut impl FnMut(u8, &KOutShared, &KOut)) {
    let mut dp: u16 = p.dp;
    let mut bd_flag: bool = p.bd;
    let bd: &mut bool = &mut bd_flag;
    let kb0: bool = (B >> 0) & 1 != 0;
    let kb1: bool = (B >> 1) & 1 != 0;
    let kb2: bool = (B >> 2) & 1 != 0;
    let kb3: bool = (B >> 3) & 1 != 0;
    let kb4: bool = (B >> 4) & 1 != 0;
    let kb5: bool = (B >> 5) & 1 != 0;
    out(B, osh, &KOut {
        valid: p.valid,
        deopt: dp,
        bd: *bd,
        c309: kb5,
        c310: kb4,
    });
}
