[package]
name = "celeste-interp"
version = "0.1.0"
edition = "2021"

[dependencies]
celeste-core = { path = "../celeste-core" }
anyhow = "1.0.62"
im = { version = "15.1.0", features = ["serde"] }
lazy_static = "1.4.0"
rustc-hash = "1.1.0"
itertools = "0.12.0"
indexmap = "2.2.6"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
elsa = "1.10"
bincode = "1.3"
