// GENERATED by `trace::kernel::merge_kernel_sets`. Do not edit.
//
// One submodule per generated ROOM; each holds one kernel per
// heap shape that room reaches, and `SETS` is what
// `Dispatch::new_multi` flattens into the one shape-hash
// registry. Every kernel here is CONSTANT-LATTICE specialized
// (plans/specialize.md): baked constants are guarded by the
// kernel's `ok`, so a lane that disagrees declines loudly.
#![allow(clippy::all)]
pub use celeste_engine::traced::Kernel;

pub mod room00;
pub mod room10;
pub mod room20;

pub const SETS: &[&[Kernel]] = &[
    room00::KERNELS,
    room10::KERNELS,
    room20::KERNELS,
];

/// Content hash of every kernel source in every room of this
/// set. Hashed into the campaign fingerprint so two different
/// kernel sets can never share a checkpoint.
pub const FINGERPRINT: u64 = 15267347155670815689;
